
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_DEBUG_AGENT)




	
	

	
# copying directory hostfs/h to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/hostFsLib.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/hostFsLib.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/hostFsLib.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/hostfs/h/hostFsLib.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory src/tcf-c-core/agent to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public




# copying directory src/tcf-c-core/agent/tcf to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf




# copying directory src/tcf-c-core/agent/tcf/main to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/cmdline.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/cmdline.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/cmdline.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/main/cmdline.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/gdb-rsp.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/gdb-rsp.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/gdb-rsp.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/main/gdb-rsp.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/logfilter.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/logfilter.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/logfilter.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/main/logfilter.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/main_hooks.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/main_hooks.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/main_hooks.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/main/main_hooks.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/server.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/server.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/server.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/main/server.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/services.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/services.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/services.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/main/services.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/test.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/test.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/test.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/main/test.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory src/tcf-c-core/agent/tcf/framework to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/asyncreq.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/asyncreq.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/asyncreq.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/asyncreq.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/channel_tcp.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/channel_tcp.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/channel_tcp.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/channel_tcp.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-mux-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-mux-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-mux-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/context-mux-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs-mux.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs-mux.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs-mux.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/cpudefs-mux.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/funccall.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/funccall.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/funccall.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/funccall.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep-fs.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep-fs.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep-fs.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/mdep-fs.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/outputbuf.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/outputbuf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/outputbuf.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/outputbuf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/proxy.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/proxy.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/proxy.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/proxy.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/tcf.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/tcf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/tcf.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/tcf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/base64.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/base64.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/base64.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/base64.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-dispatcher-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-dispatcher-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-dispatcher-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/context-dispatcher-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-mux.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-mux.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-mux.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/context-mux.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/errors.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/errors.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/errors.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/errors.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/inputbuf.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/inputbuf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/inputbuf.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/inputbuf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/peer.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/peer.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/peer.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/peer.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/shutdown.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/shutdown.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/shutdown.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/shutdown.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/timed_event_queue.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/timed_event_queue.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/timed_event_queue.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/timed_event_queue.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cache.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cache.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cache.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/cache.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-dispatcher.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-dispatcher.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-dispatcher.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/context-dispatcher.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/cpudefs-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/event_queue.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/event_queue.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/event_queue.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/event_queue.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/ip_ifc.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/ip_ifc.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/ip_ifc.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/ip_ifc.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/pid-hash.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/pid-hash.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/pid-hash.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/pid-hash.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/signames.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/signames.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/signames.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/signames.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/trace.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/trace.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/trace.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/trace.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/channel.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/channel.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/channel.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/channel.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/context-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/cpudefs.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/events.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/events.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/events.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/events.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/json.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/json.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/json.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/json.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep-threads.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep-threads.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep-threads.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/mdep-threads.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/plugins.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/plugins.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/plugins.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/plugins.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/sigsets.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/sigsets.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/sigsets.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/sigsets.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/waitpid.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/waitpid.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/waitpid.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/waitpid.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/channel_pipe.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/channel_pipe.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/channel_pipe.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/channel_pipe.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/context.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/context.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs-mdep-mux.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs-mdep-mux.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/cpudefs-mdep-mux.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/cpudefs-mdep-mux.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/exceptions.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/exceptions.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/exceptions.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/exceptions.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/link.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/link.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/link.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/link.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/myalloc.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/myalloc.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/myalloc.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/myalloc.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/protocol.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/protocol.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/protocol.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/protocol.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/streams.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/streams.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/streams.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/framework/streams.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory src/tcf-c-core/agent/tcf/services to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/discovery.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/discovery.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/discovery.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/discovery.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfecomp.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfecomp.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfecomp.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/dwarfecomp.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfreloc-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfreloc-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfreloc-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/dwarfreloc-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/expressions.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/expressions.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/expressions.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/expressions.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/linenumbers_mux.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/linenumbers_mux.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/linenumbers_mux.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/linenumbers_mux.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/profiler.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/profiler.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/profiler.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/profiler.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/stacktrace-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/stacktrace-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/stacktrace-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/stacktrace-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/sysmon.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/sysmon.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/sysmon.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/sysmon.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/breakpoints.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/breakpoints.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/breakpoints.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/breakpoints.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/discovery_udp.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/discovery_udp.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/discovery_udp.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/discovery_udp.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfexpr.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfexpr.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfexpr.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/dwarfexpr.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfreloc.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfreloc.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfreloc.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/dwarfreloc.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/filesystem.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/filesystem.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/filesystem.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/filesystem.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/memorymap.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/memorymap.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/memorymap.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/memorymap.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/profiler_sst.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/profiler_sst.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/profiler_sst.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/profiler_sst.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/stacktrace.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/stacktrace.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/stacktrace.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/stacktrace.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/tcf_elf.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/tcf_elf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/tcf_elf.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/tcf_elf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/contextquery.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/contextquery.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/contextquery.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/contextquery.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dprintf.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dprintf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dprintf.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/dprintf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfframe.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfframe.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfframe.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/dwarfframe.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/elf-loader.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/elf-loader.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/elf-loader.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/elf-loader.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/funccall.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/funccall.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/funccall.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/funccall.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/memoryservice.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/memoryservice.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/memoryservice.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/memoryservice.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/registers.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/registers.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/registers.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/registers.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/streamsservice.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/streamsservice.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/streamsservice.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/streamsservice.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/terminals.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/terminals.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/terminals.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/terminals.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/diagnostics.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/diagnostics.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/diagnostics.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/diagnostics.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfcache.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfcache.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfcache.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/dwarfcache.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarf.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarf.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/dwarf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/elf-symbols-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/elf-symbols-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/elf-symbols-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/elf-symbols-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/pathmap.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/pathmap.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/pathmap.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/pathmap.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/symbols.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/symbols.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/symbols.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/symbols.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/vm.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/vm.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/vm.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/vm.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/disassembly.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/disassembly.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/disassembly.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/disassembly.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfecomp-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfecomp-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfecomp-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/dwarfecomp-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfio.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfio.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/dwarfio.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/dwarfio.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/elf-symbols.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/elf-symbols.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/elf-symbols.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/elf-symbols.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/linenumbers.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/linenumbers.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/linenumbers.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/linenumbers.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/runctrl.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/runctrl.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/runctrl.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/runctrl.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/symbols_mux.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/symbols_mux.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/symbols_mux.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/agent/tcf/services/symbols_mux.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



 
# copying directory src/tcf-c-core/proprietary/agent to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public




# copying directory src/tcf-c-core/proprietary/agent/tcf to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/wr-renameconfig.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/wr-renameconfig.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/wr-renameconfig.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary/agent/tcf/wr-renameconfig.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


 
# copying directory src/tcf-c-core/proprietary_vx/agent to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public




# copying directory src/tcf-c-core/proprietary_vx/agent/tcf to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/config.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/config.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/config.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/config.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory src/tcf-c-core/proprietary_vx/agent/tcf/main to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/services-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/services-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main/services-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/main/services-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory src/tcf-c-core/proprietary_vx/agent/tcf/framework to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/framework/mdep.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep-inet.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep-inet.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework/mdep-inet.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/framework/mdep-inet.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory src/tcf-c-core/proprietary_vx/agent/tcf/services to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/linenumbers_elf-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/linenumbers_elf-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/linenumbers_elf-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/linenumbers_elf-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/breakpoints-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/breakpoints-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/breakpoints-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/breakpoints-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_LivePatch_proxy.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_LivePatch_proxy.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_LivePatch_proxy.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/WR_LivePatch_proxy.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_SymbolsList_proxy.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_SymbolsList_proxy.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_SymbolsList_proxy.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/WR_SymbolsList_proxy.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_HostFs.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_HostFs.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_HostFs.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/WR_HostFs.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_Module.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_Module.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_Module.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/WR_Module.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/runctrl-ext.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/runctrl-ext.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/runctrl-ext.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/runctrl-ext.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_FileSystem_proxy.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_FileSystem_proxy.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/WR_FileSystem_proxy.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/WR_FileSystem_proxy.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/processes.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/processes.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/processes.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/processes.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/profiler_spy.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/profiler_spy.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/profiler_spy.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/profiler_spy.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/patch_linenumbers_elf.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/patch_linenumbers_elf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services/patch_linenumbers_elf.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcf-c-core/proprietary_vx/agent/tcf/services/patch_linenumbers_elf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif






	
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcfLib.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcfLib.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcfLib.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcflib/tcfLib.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/debugAgent.h

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/debugAgent.h





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/debugAgent.h : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/tcflib/debugAgent.h | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	


	
	
	
	
	
	
	
BUILD : DEBUG_AGENT_hostfs/src_diab__BUILD

.PHONY : DEBUG_AGENT_hostfs/src_diab__BUILD

__BUILD_FB_IDS += kernel_top_DEBUG_AGENT_hostfs_src_diab

DEBUG_AGENT_hostfs/src_diab__BUILD : 
	@ echo building DEBUG_AGENT directory hostfs/src
	+ @ cd C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/hostfs/src && C:/WindRiverSR500New/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=kernel _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=DEBUG_AGENT VSB_DIR=C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_DEBUG_AGENT_hostfs_src_diab BSPNAME=ti_sitara_ctxa9_branson_1_0_0_0 BUILDSTAGE=BUILD
 
BUILD : DEBUG_AGENT_src_diab__BUILD

.PHONY : DEBUG_AGENT_src_diab__BUILD

__BUILD_FB_IDS += kernel_top_DEBUG_AGENT_src_diab

DEBUG_AGENT_src_diab__BUILD : 
	@ echo building DEBUG_AGENT directory src
	+ @ cd C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src && C:/WindRiverSR500New/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=kernel _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=DEBUG_AGENT VSB_DIR=C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_DEBUG_AGENT_src_diab BSPNAME=ti_sitara_ctxa9_branson_1_0_0_0 BUILDSTAGE=BUILD


	
	
	

	
	
	

	

	


	
# copying directory hostfs/cdf to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/01comp_hostFs.cdf

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/01comp_hostFs.cdf





 

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/01comp_hostFs.cdf : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/hostfs/cdf/01comp_hostFs.cdf | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory src/osconfig/vxworks/cdf to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/01comp_agent.cdf

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/01comp_agent.cdf





C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/01comp_agent.cdf : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/osconfig/vxworks/cdf/01comp_agent.cdf | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	
hostfs_cdf_PRENOBUILD_DEBUG_AGENT_FILES = hostfs/cdf/01comp_hostFs.cdf

hostfs_cdf_PRENOBUILD_DEBUG_AGENT_DIR = C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5

PRENOBUILD_FILES += $(addprefix $(hostfs_cdf_PRENOBUILD_DEBUG_AGENT_DIR)/,$(hostfs_cdf_PRENOBUILD_DEBUG_AGENT_FILES))

PRENOBUILD : PRENOBUILD_DEBUG_AGENT

PRENOBUILD_DEBUG_AGENT : hostfs/cdf_PRENOBUILD_DEBUG_AGENT

hostfs/cdf_PRENOBUILD_DEBUG_AGENT : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/hostfs_cdf_PRENOBUILD_DEBUG_AGENT.cdf

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/hostfs_cdf_PRENOBUILD_DEBUG_AGENT.cdf : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/hostfs_cdf_PRENOBUILD_DEBUG_AGENT.tmp
	$(CDFCOMP) -i $^ -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer DEBUG_AGENT

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/hostfs_cdf_PRENOBUILD_DEBUG_AGENT.tmp : | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf
	$(file >$@,$(call __vsb_tmpl_cdf_inter,$(addprefix $(hostfs_cdf_PRENOBUILD_DEBUG_AGENT_DIR)/,$(sort $(hostfs_cdf_PRENOBUILD_DEBUG_AGENT_FILES))),DEBUG_AGENT))


 
src_osconfig_vxworks_cdf_PRENOBUILD_DEBUG_AGENT_FILES = src/osconfig/vxworks/cdf/01comp_agent.cdf

src_osconfig_vxworks_cdf_PRENOBUILD_DEBUG_AGENT_DIR = C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5

PRENOBUILD_FILES += $(addprefix $(src_osconfig_vxworks_cdf_PRENOBUILD_DEBUG_AGENT_DIR)/,$(src_osconfig_vxworks_cdf_PRENOBUILD_DEBUG_AGENT_FILES))

PRENOBUILD : PRENOBUILD_DEBUG_AGENT

PRENOBUILD_DEBUG_AGENT : src/osconfig/vxworks/cdf_PRENOBUILD_DEBUG_AGENT

src/osconfig/vxworks/cdf_PRENOBUILD_DEBUG_AGENT : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/src_osconfig_vxworks_cdf_PRENOBUILD_DEBUG_AGENT.cdf

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/src_osconfig_vxworks_cdf_PRENOBUILD_DEBUG_AGENT.cdf : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/src_osconfig_vxworks_cdf_PRENOBUILD_DEBUG_AGENT.tmp
	$(CDFCOMP) -i $^ -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer DEBUG_AGENT

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/src_osconfig_vxworks_cdf_PRENOBUILD_DEBUG_AGENT.tmp : | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf
	$(file >$@,$(call __vsb_tmpl_cdf_inter,$(addprefix $(src_osconfig_vxworks_cdf_PRENOBUILD_DEBUG_AGENT_DIR)/,$(sort $(src_osconfig_vxworks_cdf_PRENOBUILD_DEBUG_AGENT_FILES))),DEBUG_AGENT))



	

	
# copying directory src/osconfig/vxworks/src to C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/configlette




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/configlette/usrDebugAgent.c

__FILES_TO_COPY_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/configlette/usrDebugAgent.c





 

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/configlette/usrDebugAgent.c : C:/WindRiverSR500New/vxworks-7/pkgs/rttools/agent-1.2.3.5/src/osconfig/vxworks/src/usrDebugAgent.c | C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



	
__DIR_TARGETS += $(__DIR_TARGETS_DEBUG_AGENT)

__DIR_TARGETS_DEBUG_AGENT += C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/configlette C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/framework C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/main C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tcf/services C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/share/h C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/usr/h C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/vsblCdf

