
ifndef __HEADER_ACCESS_USB_TARGET_INCLUDED
__HEADER_ACCESS_USB_TARGET_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_USB_TARGET = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_TARGET),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), USB_TARGET))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_TARGET
endif
endif

endif

endif

