
ifndef __HEADER_ACCESS_BRANSON_LAYER_DRIVERS_INCLUDED
__HEADER_ACCESS_BRANSON_LAYER_DRIVERS_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BRANSON_LAYER_DRIVERS = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/BRANSON_LAYER_DRIVERS),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BRANSON_LAYER_DRIVERS))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/BRANSON_LAYER_DRIVERS
endif
endif

endif

endif

