
ifndef __HEADER_ACCESS_ARM_ARMV7A_INCLUDED
__HEADER_ACCESS_ARM_ARMV7A_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_ARM_ARMV7A = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/ARM_ARMV7A),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), ARM_ARMV7A))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/ARM_ARMV7A
endif
endif

endif

endif

