
#
# This file is automatically generated by mk/krnl/defs.fastlibgen.mk .
#
# build configuration :
#	VSB : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB
#	CPU : ARMARCH7
#	TOOL : diab
#	FP : vector
# 	ENDIAN : little
#	LIB_DIR_TAG = 
#	LIBDIRBASE = krnl/ARMARCH7/common
#	LIBDIRBASE = krnl/$(CPU)$(CPU_OPTION_SUFFIX)/$(TOOL_COMMON_DIR)$(LIB_DIR_TAG)$(MINOR_OPTION_SUFFIX)






LIBOBJS = $(LIBOBJS_fsRomfs)

# DEP_OBJS = (DEP_OBJS)

 
LIBOBJS_krnl_ARMARCH7_common_fsRomfs_kernel_top_FS_ROMFS_src_diab =  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/objfsRomfs/romfs.o  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/objfsRomfs/romfsDrv.o  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/objfsRomfs/romfsLib.o 

arcmdfile_krnl_ARMARCH7_common_fsRomfs : $(LIBOBJS_krnl_ARMARCH7_common_fsRomfs_kernel_top_FS_ROMFS_src_diab)

LIBOBJS_krnl_ARMARCH7_common_fsRomfs_FS_ROMFS += $(LIBOBJS_krnl_ARMARCH7_common_fsRomfs_kernel_top_FS_ROMFS_src_diab)

LIBOBJS_krnl_ARMARCH7_common_fsRomfs += $(LIBOBJS_krnl_ARMARCH7_common_fsRomfs_kernel_top_FS_ROMFS_src_diab)

__OBJS_TO_CLEAN_FS_ROMFS += $(LIBOBJS_krnl_ARMARCH7_common_fsRomfs_kernel_top_FS_ROMFS_src_diab) $(LIBOBJS_krnl_ARMARCH7_common_fsRomfs_kernel_top_FS_ROMFS_src_diab:.o=.d)

ifndef _DONEBASE_LIB_krnl_ARMARCH7_common_fsRomfs

_DONEBASE_LIB_krnl_ARMARCH7_common_fsRomfs = TRUE

# LIBBASES += fsRomfs

__LIBS_TO_BUILD += krnl_ARMARCH7_common_fsRomfs

__LIBS_TO_BUILD_FS_ROMFS += krnl_ARMARCH7_common_fsRomfs

__BUILT_LIBS += krnl_ARMARCH7_common_fsRomfs

__LIB_krnl_ARMARCH7_common_fsRomfs = C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs$(OPT).a


C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/objfsRomfs :
	$(MKDIR) $@


lib : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs$(OPT).a  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs.cdf

# need to pass the lib.a file twice to C:/WindRiverSR500New/compilers/diab-5.9.6.1/WIN32/bin/ddump -Ng to workaround ddump problem
C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs.nm : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs$(OPT).a
	$(if $(wildcard $<),cd C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common && $(NM) libfsRomfs$(OPT).a libfsRomfs$(OPT).a > $@, $(info skipping $@ : non existant $<))

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs.cdf : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs.nm 
	$(if $(wildcard $<),$(LIB2CDF) -i $< -a libfsRomfs.a -o $@, $(info skipping $@ : non existant $<))

arcmdfiles : arcmdfile_krnl_ARMARCH7_common_fsRomfs

arcmdfile_krnl_ARMARCH7_common_fsRomfs :
	$(file >$@,$(LIBOBJS_krnl_ARMARCH7_common_fsRomfs))
	@echo created $@

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs$(OPT).a : arcmdfile_krnl_ARMARCH7_common_fsRomfs
	C:/WindRiverSR500New/compilers/diab-5.9.6.1/WIN32/bin/dar crusv $@ @arcmdfile_krnl_ARMARCH7_common_fsRomfs


clean _layer_clean_FS_ROMFS : _clean_LIB_BASE_krnl_ARMARCH7_common_fsRomfs

_clean_LIB_BASE_krnl_ARMARCH7_common_fsRomfs :
	rm -f C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs$(OPT).a


endif

ifndef _DONEBASE_LIB_FS_ROMFS_krnl_ARMARCH7_common_fsRomfs

_DONEBASE_LIB_FS_ROMFS_krnl_ARMARCH7_common_fsRomfs = TRUE

lib : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/layerFS_ROMFS_libfsRomfs.cdf

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/layerFS_ROMFS_libfsRomfs.cdf :  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs$(OPT).a
	$(file >$@, $(call __tmpl_layercdf,FS_ROMFS,libfsRomfs.a,$(LIBOBJS_krnl_ARMARCH7_common_fsRomfs)))

endif


C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libfsRomfs$(OPT).a : $(LIBOBJS_krnl_ARMARCH7_common_fsRomfs)




 

################
# rules defined locally in Makefile
##



################

objs : $(LIBOBJS)
 
# this is the end of the file 
