
#
# This file is automatically generated by mk/krnl/defs.fastlibgen.mk .
#
# build configuration :
#	VSB : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB
#	CPU : ARMARCH7
#	TOOL : diab
#	FP : vector
# 	ENDIAN : little
#	LIB_DIR_TAG = 
#	LIBDIRBASE = krnl/ARMARCH7/common
#	LIBDIRBASE = krnl/$(CPU)$(CPU_OPTION_SUFFIX)/$(TOOL_COMMON_DIR)$(LIB_DIR_TAG)$(MINOR_OPTION_SUFFIX)






LIBOBJS = $(LIBOBJS_vdfs)

# DEP_OBJS = (DEP_OBJS)

 
LIBOBJS_krnl_ARMARCH7_common_vdfs_kernel_top_FS_VDFS_src_diab =  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/objvdfs/vdFsLib.o 

arcmdfile_krnl_ARMARCH7_common_vdfs : $(LIBOBJS_krnl_ARMARCH7_common_vdfs_kernel_top_FS_VDFS_src_diab)

LIBOBJS_krnl_ARMARCH7_common_vdfs_FS_VDFS += $(LIBOBJS_krnl_ARMARCH7_common_vdfs_kernel_top_FS_VDFS_src_diab)

LIBOBJS_krnl_ARMARCH7_common_vdfs += $(LIBOBJS_krnl_ARMARCH7_common_vdfs_kernel_top_FS_VDFS_src_diab)

__OBJS_TO_CLEAN_FS_VDFS += $(LIBOBJS_krnl_ARMARCH7_common_vdfs_kernel_top_FS_VDFS_src_diab) $(LIBOBJS_krnl_ARMARCH7_common_vdfs_kernel_top_FS_VDFS_src_diab:.o=.d)

ifndef _DONEBASE_LIB_krnl_ARMARCH7_common_vdfs

_DONEBASE_LIB_krnl_ARMARCH7_common_vdfs = TRUE

# LIBBASES += vdfs

__LIBS_TO_BUILD += krnl_ARMARCH7_common_vdfs

__LIBS_TO_BUILD_FS_VDFS += krnl_ARMARCH7_common_vdfs

__BUILT_LIBS += krnl_ARMARCH7_common_vdfs

__LIB_krnl_ARMARCH7_common_vdfs = C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs$(OPT).a


C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/objvdfs :
	$(MKDIR) $@


lib : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs$(OPT).a  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs.cdf

# need to pass the lib.a file twice to C:/WindRiverSR500New/compilers/diab-5.9.6.1/WIN32/bin/ddump -Ng to workaround ddump problem
C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs.nm : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs$(OPT).a
	$(if $(wildcard $<),cd C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common && $(NM) libvdfs$(OPT).a libvdfs$(OPT).a > $@, $(info skipping $@ : non existant $<))

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs.cdf : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs.nm 
	$(if $(wildcard $<),$(LIB2CDF) -i $< -a libvdfs.a -o $@, $(info skipping $@ : non existant $<))

arcmdfiles : arcmdfile_krnl_ARMARCH7_common_vdfs

arcmdfile_krnl_ARMARCH7_common_vdfs :
	$(file >$@,$(LIBOBJS_krnl_ARMARCH7_common_vdfs))
	@echo created $@

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs$(OPT).a : arcmdfile_krnl_ARMARCH7_common_vdfs
	C:/WindRiverSR500New/compilers/diab-5.9.6.1/WIN32/bin/dar crusv $@ @arcmdfile_krnl_ARMARCH7_common_vdfs


clean _layer_clean_FS_VDFS : _clean_LIB_BASE_krnl_ARMARCH7_common_vdfs

_clean_LIB_BASE_krnl_ARMARCH7_common_vdfs :
	rm -f C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs$(OPT).a


endif

ifndef _DONEBASE_LIB_FS_VDFS_krnl_ARMARCH7_common_vdfs

_DONEBASE_LIB_FS_VDFS_krnl_ARMARCH7_common_vdfs = TRUE

lib : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/layerFS_VDFS_libvdfs.cdf

C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/layerFS_VDFS_libvdfs.cdf :  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs$(OPT).a
	$(file >$@, $(call __tmpl_layercdf,FS_VDFS,libvdfs.a,$(LIBOBJS_krnl_ARMARCH7_common_vdfs)))

endif


C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/libvdfs$(OPT).a : $(LIBOBJS_krnl_ARMARCH7_common_vdfs)




 

################
# rules defined locally in Makefile
##



################

objs : $(LIBOBJS)
 
# this is the end of the file 
