
#
# This file is automatically generated by mk/usr/defs.fastlibgen.mk.
#
# build configuration :
#	VSB : C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB
#	CPU : ARMARCH7
#	TOOL : gnu
#	FP : vector
# 	ENDIAN : little
#	LIB_DIR_TAG = 
#	LIBDIRBASE = 
#	LIBDIRBASE = 





include user_static_top_LANG_LIB_TOOL_TOOLSRC_GNU_USER_src_gnu_libc_simple.mk 
include user_static_top_LANG_LIB_TOOL_TOOLSRC_GNU_USER_src_gnu_libc_pic.mk 
include user_static_top_LANG_LIB_TOOL_TOOLSRC_GNU_USER_src_gnu_libc_internal_simple.mk 
include user_static_top_LANG_LIB_TOOL_TOOLSRC_GNU_USER_src_gnu_libc_internal_pic.mk

ifeq (,)



endif


# DEP_OBJS = (DEP_OBJS)

# LIB_BASE_NAMES = 







################
# rules defined locally in Makefile
##





################

objs : $(LIBOBJS)
 
# this is the end of the file 
