C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/ARMARCH7/common/objruntime_analysis_usereventdemo/mybuffer.o: \
  src/demo/cafe_user_event_demo/mybuffer.c \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/stdlib.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/types/vxANSI.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/stdint.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/vsbConfig.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/h/config/vsbConfig.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/h/config/autoconf.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/types/vxCpu.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/types/vxArch.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/arch/arm/archArm.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/arch/arm/arm.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/arch/arm/archArmCommon.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/types/vxParams.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/types/vxTypesBase.h \
  C:/WindRiverSR500New/compilers/diab-5.9.6.1/include/diab/stddef.h \
  C:/WindRiverSR500New/compilers/diab-5.9.6.1/include/diab/xmacros.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/string.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/base/b_swab.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/base/b_rsize_t.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/base/b_errno_t.h \
  phoenix/cafe/include/cafe/ep/user_event.h \
  phoenix/cafe/include/cafe/cafe.h \
  phoenix/cafe/include/cafe/allocator.h \
  phoenix/cafe/include/cafe/ccdiff.h \
  phoenix/cafe/include/cafe/inttypes.h \
  phoenix/cafe/include/cafe/stdbool.h \
  phoenix/cafe/include/cafe/library.h \
  phoenix/cafe/include/cafe/types.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/limits.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/tool/diab/limits.h \
  phoenix/cafe/include/cafe/list.h \
  phoenix/cafe/include/cafe/value_type.h \
  C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/h/public/assert.h \
  phoenix/cafe/include/cafe/array.h \
  phoenix/cafe/include/cafe/session.h \
  phoenix/cafe/include/cafe/spec.h phoenix/cafe/include/cafe/inst.h \
  phoenix/cafe/include/cafe/action_list.h \
  phoenix/cafe/include/cafe/lock.h phoenix/cafe/include/cafe/dict.h \
  phoenix/cafe/include/cafe/autogenerated/user_event.type.h \
  phoenix/cafe/include/cafe/autogenerated/cafe.type.h \
  src/demo/cafe_user_event_demo/mybuffer.h

