/* am335xEvmSKClkData.c - am335x EVM SK clock data */

/*
 * Copyright (c) 2014 Wind River Systems, Inc.
 *
 * The right to copy, distribute, modify or otherwise make use
 * of this software may be licensed only pursuant to the terms
 * of an applicable Wind River license agreement.
 */

/*
modification history
--------------------
09may14,c_t  fix build issue (V7PRO-789)
17apr14,sye  created. (US36393)
*/

/*
DESCRIPTION

This file describes the static clock tree of am335x EVM SK target.
The clock tree relationship are static defined, and the clock multiplexer
registers are set according to the static parent selection.
*/

#include <vxWorks.h>
#include <vxbAm3Prcm.h>

/* forward declaration */

LOCAL VXB_CLK sys_clkin_ck;
LOCAL VXB_CLK dpll_core_ck;
LOCAL VXB_CLK dpll_core_x2_ck;
LOCAL VXB_CLK dpll_mpu_ck;
LOCAL VXB_CLK dpll_ddr_ck;
LOCAL VXB_CLK dpll_disp_ck;
LOCAL VXB_CLK dpll_per_ck;
LOCAL VXB_CLK sysclk1_ck;
LOCAL VXB_CLK sysclk2_ck;
LOCAL VXB_CLK l3_gclk;
LOCAL VXB_CLK clk_32khz_ck;
LOCAL VXB_CLK clk_32khz_timer;
LOCAL VXB_CLK disp_pll_clk;
LOCAL VXB_CLK per_192mhz_clk;

DEFINE_CLOCK_REG (mpu_fck_regs         , AM335X_CM_MPU_MPU_CLKCTRL          , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (emif_fck_regs        , AM335X_CM_PER_EMIF_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (l4_wkup_aon_gclk_regs, AM335X_CM_L4_WKUP_AON_CLKSTCTRL    , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (l3_ick_regs          , AM335X_CM_PER_L3_CLKCTRL           , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (l3_instr_ick_regs    , AM335X_CM_PER_L3_INSTR_CLKCTRL     , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (l4ls_gclk_regs       , AM335X_CM_PER_L4LS_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (cefuse_fck_regs      , AM335X_CM_CEFUSE_CEFUSE_CLKCTRL    , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (adc_tsc_ick_regs     , AM335X_CM_WKUP_ADC_TSC_CLKCTRL     , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (aes0_fck_regs        , AM335X_CM_PER_AES0_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (clkdiv32k_ick_regs   , AM335X_CM_PER_CLKDIV32K_CLKCTRL    , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (control_fck_regs     , AM335X_CM_WKUP_CONTROL_CLKCTRL     , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (dcan0_fck_regs       , AM335X_CM_PER_DCAN0_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (dcan1_fck_regs       , AM335X_CM_PER_DCAN1_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (debugss_ick_regs     , AM335X_CM_WKUP_DEBUGSS_CLKCTRL     , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_NO_WAIT     );
DEFINE_CLOCK_REG (elm_fck_regs         , AM335X_CM_PER_ELM_CLKCTRL          , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (emif_fw_fck_regs     , AM335X_CM_PER_EMIF_FW_CLKCTRL      , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (epwmss0_fck_regs     , AM335X_CM_PER_EPWMSS0_CLKCTRL      , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (epwmss1_fck_regs     , AM335X_CM_PER_EPWMSS1_CLKCTRL      , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (epwmss2_fck_regs     , AM335X_CM_PER_EPWMSS2_CLKCTRL      , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (gpmc_fck_regs        , AM335X_CM_PER_GPMC_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (i2c1_fck_regs        , AM335X_CM_WKUP_I2C0_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (i2c2_fck_regs        , AM335X_CM_PER_I2C1_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (i2c3_fck_regs        , AM335X_CM_PER_I2C2_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (ieee5000_fck_regs    , AM335X_CM_PER_IEEE5000_CLKCTRL     , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (l4hs_ick_regs        , AM335X_CM_PER_L4HS_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (l4wkup_ick_regs      , AM335X_CM_L4_WKUP_AON_CLKSTCTRL    , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_NO_WAIT     );
DEFINE_CLOCK_REG (l4fw_ick_regs        , AM335X_CM_PER_L4FW_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (l4ls_ick_regs        , AM335X_CM_PER_L4LS_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (mailbox0_fck_regs    , AM335X_CM_PER_MAILBOX0_CLKCTRL     , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (mcasp0_fck_regs      , AM335X_CM_PER_MCASP0_CLKCTRL       , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (mcasp1_fck_regs      , AM335X_CM_PER_MCASP1_CLKCTRL       , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (mlb_fck_regs         , AM335X_CM_PER_MLB_CLKCTRL          , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (mmu_fck_regs         , AM335X_CM_GFX_MMUDATA_CLKCTRL      , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (ocmcram_ick_regs     , AM335X_CM_PER_OCMCRAM_CLKCTRL      , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (ocpwp_fck_regs       , AM335X_CM_PER_OCPWP_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (pka_fck_regs         , AM335X_CM_PER_PKA_CLKCTRL          , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (rng_fck_regs         , AM335X_CM_PER_RNG_CLKCTRL          , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (rtc_fck_regs         , AM335X_CM_RTC_RTC_CLKCTRL          , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (sha0_fck_regs        , AM335X_CM_PER_SHA0_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (smartreflex0_fck_regs, AM335X_CM_WKUP_SMARTREFLEX0_CLKCTRL, AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (smartreflex1_fck_regs, AM335X_CM_WKUP_SMARTREFLEX1_CLKCTRL, AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (spi0_fck_regs        , AM335X_CM_PER_SPI0_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (spi1_fck_regs        , AM335X_CM_PER_SPI1_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (spinlock_fck_regs    , AM335X_CM_PER_SPINLOCK_CLKCTRL     , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (timer0_fck_regs      , AM335X_CM_WKUP_TIMER0_CLKCTRL      , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (timer1_fck_regs      , AM335X_CM_WKUP_TIMER1_CLKCTRL      , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (timer2_fck_regs      , AM335X_CM_PER_TIMER2_CLKCTRL       , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (timer3_fck_regs      , AM335X_CM_PER_TIMER3_CLKCTRL       , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (timer4_fck_regs      , AM335X_CM_PER_TIMER4_CLKCTRL       , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (timer5_fck_regs      , AM335X_CM_PER_TIMER5_CLKCTRL       , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (timer6_fck_regs      , AM335X_CM_PER_TIMER6_CLKCTRL       , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (timer7_fck_regs      , AM335X_CM_PER_TIMER7_CLKCTRL       , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (tpcc_ick_regs        , AM335X_CM_PER_TPCC_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (tptc0_ick_regs       , AM335X_CM_PER_TPTC0_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (tptc1_ick_regs       , AM335X_CM_PER_TPTC1_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (tptc2_ick_regs       , AM335X_CM_PER_TPTC2_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (uart1_fck_regs       , AM335X_CM_WKUP_UART0_CLKCTRL       , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (uart2_fck_regs       , AM335X_CM_PER_UART1_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (uart3_fck_regs       , AM335X_CM_PER_UART2_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (uart4_fck_regs       , AM335X_CM_PER_UART3_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (uart5_fck_regs       , AM335X_CM_PER_UART4_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (uart6_fck_regs       , AM335X_CM_PER_UART5_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (wkup_m3_fck_regs     , AM335X_CM_WKUP_WKUP_M3_CLKCTRL     , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (cpgmac0_ick_regs     , AM335X_CM_PER_CPGMAC0_CLKCTRL      , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (usbotg_ick_regs      , AM335X_CM_PER_USB0_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (gpio0_ick_regs       , AM335X_CM_WKUP_GPIO0_CLKCTRL       , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (gpio1_ick_regs       , AM335X_CM_PER_GPIO1_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (gpio2_ick_regs       , AM335X_CM_PER_GPIO2_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (gpio3_ick_regs       , AM335X_CM_PER_GPIO3_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (pruss_uart_gclk_regs , AM335X_CM_PER_PRUSS_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (lcdc_fck_regs        , AM335X_CM_PER_LCDC_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (mmc0_fck_regs        , AM335X_CM_PER_MMC0_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (mmc1_fck_regs        , AM335X_CM_PER_MMC1_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (mmc2_fck_regs        , AM335X_CM_PER_MMC2_CLKCTRL         , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (gfx_fclk_regs        , AM335X_CM_GFX_GFX_CLKCTRL          , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (wdt0_fck_regs        , AM335X_CM_WKUP_WDT0_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (wdt1_fck_regs        , AM335X_CM_WKUP_WDT1_CLKCTRL        , AM335X_MODULEMODE_MASK, AM335X_MODULEMODE_EN, AM335X_MODULEMODE_DIS, AM335X_IDLEST_MASK, 0x0, AM335X_IDLEST_DIS, AM3_CLK_DFLT_TIMEOUT);
DEFINE_CLOCK_REG (ehrpwm0_tbclk_regs   , AM335X_CONTROL_PWMSS_CTRL          , AM335X_PWMSS0_TBCLKEN_MASK          , AM335X_PWMSS0_TBCLKEN             , AM335X_PWMSS0_TBCLKDIS             , 0x0, 0x0, 0x0, AM3_CLK_NO_WAIT);
DEFINE_CLOCK_REG (ehrpwm1_tbclk_regs   , AM335X_CONTROL_PWMSS_CTRL          , AM335X_PWMSS1_TBCLKEN_MASK          , AM335X_PWMSS1_TBCLKEN             , AM335X_PWMSS1_TBCLKDIS             , 0x0, 0x0, 0x0, AM3_CLK_NO_WAIT);
DEFINE_CLOCK_REG (ehrpwm2_tbclk_regs   , AM335X_CONTROL_PWMSS_CTRL          , AM335X_PWMSS2_TBCLKEN_MASK          , AM335X_PWMSS2_TBCLKEN             , AM335X_PWMSS2_TBCLKDIS             , 0x0, 0x0, 0x0, AM3_CLK_NO_WAIT);
DEFINE_CLOCK_REG (clkout2_ck_regs      , AM335X_CM_CLKOUT_CTRL              , AM335X_CLKOUT2MASK                  , AM335X_CLKOUT2EN                  , AM335X_CLKOUT2DIS                  , 0x0, 0x0, 0x0, AM3_CLK_NO_WAIT);
DEFINE_CLOCK_REG (usbotg_fck_regs      , AM335X_CM_CLKDCOLDO_DPLL_PER       , AM335X_DPLL_CLKDCOLDO_GATE_CTRL_MASK, AM335X_DPLL_CLKDCOLDO_GATE_CTRL_EN, AM335X_DPLL_CLKDCOLDO_GATE_CTRL_DIS, 0x0, 0x0, 0x0, AM3_CLK_NO_WAIT);
DEFINE_CLOCK_REG (gpio0_dbclk_regs     , AM335X_CM_WKUP_GPIO0_CLKCTRL       , AM335X_OPTFCLKEN_GPIO_GDBCLK_MASK   , AM335X_OPTFCLKEN_GPIO0_GDBCLK_EN  , 0x0                                , 0x0, 0x0, 0x0, AM3_CLK_NO_WAIT);
DEFINE_CLOCK_REG (gpio1_dbclk_regs     , AM335X_CM_PER_GPIO1_CLKCTRL        , AM335X_OPTFCLKEN_GPIO_GDBCLK_MASK   , AM335X_OPTFCLKEN_GPIO1_GDBCLK_EN  , 0x0                                , 0x0, 0x0, 0x0, AM3_CLK_NO_WAIT);
DEFINE_CLOCK_REG (gpio2_dbclk_regs     , AM335X_CM_PER_GPIO2_CLKCTRL        , AM335X_OPTFCLKEN_GPIO_GDBCLK_MASK   , AM335X_OPTFCLKEN_GPIO2_GDBCLK_EN  , 0x0                                , 0x0, 0x0, 0x0, AM3_CLK_NO_WAIT);
DEFINE_CLOCK_REG (gpio3_dbclk_regs     , AM335X_CM_PER_GPIO3_CLKCTRL        , AM335X_OPTFCLKEN_GPIO_GDBCLK_MASK   , AM335X_OPTFCLKEN_GPIO3_GDBCLK_EN  , 0x0                                , 0x0, 0x0, 0x0, AM3_CLK_NO_WAIT);

DEFINE_DPLL_REG  (dpll_mpu , AM335X_CM_IDLEST_DPLL_MPU   , AM335X_CM_CLKSEL_DPLL_MPU   , AM335X_CM_CLKMODE_DPLL_MPU , AM335X_DPLL_DIV_MASK, AM335X_DPLL_DIV_SHIFT, AM335X_DPLL_MULT_MASK, AM335X_DPLL_MULT_SHIFT, AM335x_DPLL_N_MAX    , AM335x_DPLL_N_MIN    , AM335x_DPLL_M_MAX    , AM335x_DPLL_M_MIN    , AM335X_DPLL_MODE_MASK, AM335X_DPLL_EN, AM335X_DPLL_BYPASS, AM335X_DPLL_ST_MN_BYPASS, AM335X_DPLL_ST_DPLL_CLK);
DEFINE_DPLL_REG  (dpll_ddr , AM335X_CM_IDLEST_DPLL_DDR   , AM335X_CM_CLKSEL_DPLL_DDR   , AM335X_CM_CLKMODE_DPLL_DDR , AM335X_DPLL_DIV_MASK, AM335X_DPLL_DIV_SHIFT, AM335X_DPLL_MULT_MASK, AM335X_DPLL_MULT_SHIFT, AM335x_DPLL_N_MAX    , AM335x_DPLL_N_MIN    , AM335x_DPLL_M_MAX    , AM335x_DPLL_M_MIN    , AM335X_DPLL_MODE_MASK, AM335X_DPLL_EN, AM335X_DPLL_BYPASS, AM335X_DPLL_ST_MN_BYPASS, AM335X_DPLL_ST_DPLL_CLK);
DEFINE_DPLL_REG  (dpll_core, AM335X_CM_IDLEST_DPLL_CORE  , AM335X_CM_CLKSEL_DPLL_CORE  , AM335X_CM_CLKMODE_DPLL_CORE, AM335X_DPLL_DIV_MASK, AM335X_DPLL_DIV_SHIFT, AM335X_DPLL_MULT_MASK, AM335X_DPLL_MULT_SHIFT, AM335x_DPLL_N_MAX    , AM335x_DPLL_N_MIN    , AM335x_DPLL_M_MAX    , AM335x_DPLL_M_MIN    , AM335X_DPLL_MODE_MASK, AM335X_DPLL_EN, AM335X_DPLL_BYPASS, AM335X_DPLL_ST_MN_BYPASS, AM335X_DPLL_ST_DPLL_CLK);
DEFINE_DPLL_REG  (dpll_per , AM335X_CM_IDLEST_DPLL_PER   , AM335X_CM_CLKSEL_DPLL_PERIPH, AM335X_CM_CLKMODE_DPLL_PER , AM335X_DPLL_DIV_MASK, AM335X_DPLL_DIV_SHIFT, AM335X_DPLL_MULT_MASK, AM335X_DPLL_MULT_SHIFT, AM335x_DPLL_PER_N_MAX, AM335x_DPLL_PER_N_MIN, AM335x_DPLL_PER_M_MAX, AM335x_DPLL_PER_M_MIN, AM335X_DPLL_MODE_MASK, AM335X_DPLL_EN, AM335X_DPLL_BYPASS, AM335X_DPLL_ST_MN_BYPASS, AM335X_DPLL_ST_DPLL_CLK);
DEFINE_DPLL_REG  (dpll_disp, AM335X_CM_IDLEST_DPLL_DISP  , AM335X_CM_CLKSEL_DPLL_DISP  , AM335X_CM_CLKMODE_DPLL_DISP, AM335X_DPLL_DIV_MASK, AM335X_DPLL_DIV_SHIFT, AM335X_DPLL_MULT_MASK, AM335X_DPLL_MULT_SHIFT, AM335x_DPLL_N_MAX    , AM335x_DPLL_N_MIN    , AM335x_DPLL_M_MAX    , AM335x_DPLL_M_MIN    , AM335X_DPLL_MODE_MASK, AM335X_DPLL_EN, AM335X_DPLL_BYPASS, AM335X_DPLL_ST_MN_BYPASS, AM335X_DPLL_ST_DPLL_CLK);

DEFINE_CLOCK_CTX (generic_root_clk_data, NULL, AM3_CLK_ROOT, NULL);

/* DEFINE_VXB_CLOCK (name, initial rate, flags, parent clock, clock domain, register data, function table, clock sel) */

DEFINE_VXB_CLOCK (clk_32768_ck      , 32768   , NULL, NULL, NULL, &generic_root_clk_data);
DEFINE_VXB_CLOCK (clk_rc32k_ck      , 32000   , NULL, NULL, NULL, &generic_root_clk_data);
DEFINE_VXB_CLOCK (virt_19_2m_ck     , 19200000, NULL, NULL, NULL, &generic_root_clk_data);
DEFINE_VXB_CLOCK (virt_24m_ck       , 24000000, NULL, NULL, NULL, &generic_root_clk_data);
DEFINE_VXB_CLOCK (virt_25m_ck       , 25000000, NULL, NULL, NULL, &generic_root_clk_data);
DEFINE_VXB_CLOCK (virt_26m_ck       , 26000000, NULL, NULL, NULL, &generic_root_clk_data);
DEFINE_VXB_CLOCK (tclkin_ck         , 12000000, NULL, NULL, NULL, &generic_root_clk_data);

LOCAL AM3_CLOCK_SEL sys_clkin_ck_clksel_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CTRL_STATUS, (0 << 22), (AM335X_CLKSEL_MASK << 22), 1, &virt_19_2m_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CTRL_STATUS, (1 << 22), (AM335X_CLKSEL_MASK << 22), 1, &virt_24m_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CTRL_STATUS, (2 << 22), (AM335X_CLKSEL_MASK << 22), 1, &virt_25m_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CTRL_STATUS, (3 << 22), (AM335X_CLKSEL_MASK << 22), 1, &virt_26m_ck)
    CLOCK_SEL_END()
    };

DEFINE_CLOCK_CTX (sys_clkin_ck_clksel_data, &sys_clkin_ck_clksel_div, AM3_CLKSEL_CLK, NULL);
DEFINE_CLOCK_CTX (dpll_core_x2_ck_data    , -2, AM3_CLKSEL_FIXED_DIV, NULL);
DEFINE_CLOCK_CTX (dpll_core_ck_data       , NULL, AM3_CLKSEL_DPLL, NULL);

LOCAL AM3_CLOCK_SEL dpll_core_m4_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_DIV_M4_DPLL_CORE, 0, AM335X_HSDIVIDER_CLKOUT_DIV_MASK, 0, &dpll_core_x2_ck)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL dpll_core_m5_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_DIV_M5_DPLL_CORE, 0, AM335X_HSDIVIDER_CLKOUT_DIV_MASK, 0, &dpll_core_x2_ck)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL dpll_core_m6_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_DIV_M6_DPLL_CORE, 0, AM335X_HSDIVIDER_CLKOUT_DIV_MASK, 0, &dpll_core_x2_ck)
    CLOCK_SEL_END()
    };

DEFINE_CLOCK_CTX (dpll_mpu_ck_data       , NULL, AM3_CLKSEL_DPLL, &dpll_mpu);
DEFINE_CLOCK_CTX (dpll_ddr_ck_data       , NULL, AM3_CLKSEL_DPLL, &dpll_ddr);
DEFINE_CLOCK_CTX (dpll_disp_ck_data      , NULL, AM3_CLKSEL_DPLL, &dpll_disp);
DEFINE_CLOCK_CTX (dpll_per_ck_data       , NULL, AM3_CLKSEL_DPLL, &dpll_per);


LOCAL AM3_CLOCK_SEL dpll_mpu_m2_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_DIV_M2_DPLL_MPU, 0, AM335X_DPLL_CLKOUT_DIV_MASK, 0, &dpll_mpu_ck)
    CLOCK_SEL_END()
    };
LOCAL AM3_CLOCK_SEL dpll_ddr_m2_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_DIV_M2_DPLL_DDR, 0, AM335X_DPLL_CLKOUT_DIV_MASK, 0, &dpll_ddr_ck)
    CLOCK_SEL_END()
    };
LOCAL AM3_CLOCK_SEL dpll_disp_m2_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_DIV_M2_DPLL_DISP, 0, AM335X_DPLL_CLKOUT_DIV_MASK, 0, &dpll_disp_ck)
    CLOCK_SEL_END()
    };
LOCAL AM3_CLOCK_SEL dpll_per_m2_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_DIV_M2_DPLL_PER, 0, AM335X_DPLL_CLKOUT_DIV_MASK, 0, &dpll_per_ck)
    CLOCK_SEL_END()
    };

DEFINE_CLOCK_CTX (dpll_core_m4_data     ,  &dpll_core_m4_div, AM3_CLKSEL_DPLL_DIV, NULL);
DEFINE_CLOCK_CTX (dpll_core_m5_data     ,  &dpll_core_m5_div, AM3_CLKSEL_DPLL_DIV, NULL);
DEFINE_CLOCK_CTX (dpll_core_m6_data     ,  &dpll_core_m6_div, AM3_CLKSEL_DPLL_DIV, NULL);
DEFINE_CLOCK_CTX (dpll_mpu_m2_data      ,  &dpll_mpu_m2_div,  AM3_CLKSEL_DPLL_DIV, NULL);
DEFINE_CLOCK_CTX (dpll_ddr_m2_data      ,  &dpll_ddr_m2_div,  AM3_CLKSEL_DPLL_DIV, NULL);
DEFINE_CLOCK_CTX (dpll_disp_m2_data     ,  &dpll_disp_m2_div, AM3_CLKSEL_DPLL_DIV, NULL);
DEFINE_CLOCK_CTX (dpll_per_m2_data      ,  &dpll_per_m2_div,  AM3_CLKSEL_DPLL_DIV, NULL);

DEFINE_CLOCK_CTX (emif_fck_data         ,  2,   AM3_CLKSEL_FIXED_DIV, &emif_fck_regs);
DEFINE_CLOCK_CTX (core_100mhz_ck_data   ,  2,   AM3_CLKSEL_FIXED_DIV, NULL);
DEFINE_CLOCK_CTX (l4_wkup_aon_gclk_data ,  2,   AM3_CLKSEL_FIXED_DIV, &l4_wkup_aon_gclk_regs);
DEFINE_CLOCK_CTX (l4_wkup_gclk_data     ,  2,   AM3_CLKSEL_FIXED_DIV, NULL);
DEFINE_CLOCK_CTX (l4_rtc_gclk_data      ,  2,   AM3_CLKSEL_FIXED_DIV, NULL);
DEFINE_CLOCK_CTX (clk_24mhz_data        ,  8,   AM3_CLKSEL_FIXED_DIV, NULL);
DEFINE_CLOCK_CTX (i2c1_fck_data         ,  4,   AM3_CLKSEL_FIXED_DIV, &i2c1_fck_regs);
DEFINE_CLOCK_CTX (i2c2_fck_data         ,  4,   AM3_CLKSEL_FIXED_DIV, &i2c2_fck_regs);
DEFINE_CLOCK_CTX (i2c3_fck_data         ,  4,   AM3_CLKSEL_FIXED_DIV, &i2c3_fck_regs);
DEFINE_CLOCK_CTX (spi0_fck_data         ,  4,   AM3_CLKSEL_FIXED_DIV, &spi0_fck_regs);
DEFINE_CLOCK_CTX (spi1_fck_data         ,  4,   AM3_CLKSEL_FIXED_DIV, &spi1_fck_regs);
DEFINE_CLOCK_CTX (uart1_fck_data        ,  4,   AM3_CLKSEL_FIXED_DIV, &uart1_fck_regs);
DEFINE_CLOCK_CTX (uart2_fck_data        ,  4,   AM3_CLKSEL_FIXED_DIV, &uart2_fck_regs);
DEFINE_CLOCK_CTX (uart3_fck_data        ,  4,   AM3_CLKSEL_FIXED_DIV, &uart3_fck_regs);
DEFINE_CLOCK_CTX (uart4_fck_data        ,  4,   AM3_CLKSEL_FIXED_DIV, &uart4_fck_regs);
DEFINE_CLOCK_CTX (uart5_fck_data        ,  4,   AM3_CLKSEL_FIXED_DIV, &uart5_fck_regs);
DEFINE_CLOCK_CTX (uart6_fck_data        ,  4,   AM3_CLKSEL_FIXED_DIV, &uart6_fck_regs);
DEFINE_CLOCK_CTX (cpsw_125mhz_gclk_data ,  2,   AM3_CLKSEL_FIXED_DIV, NULL);
DEFINE_CLOCK_CTX (cpsw_50mhz_clk_data   ,  5,   AM3_CLKSEL_FIXED_DIV, NULL);
DEFINE_CLOCK_CTX (cpsw_5mhz_clk_data    ,  10,  AM3_CLKSEL_FIXED_DIV, NULL);
DEFINE_CLOCK_CTX (mmc_clk_data          ,  2,   AM3_CLKSEL_FIXED_DIV, NULL);
DEFINE_CLOCK_CTX (vtp_clk_data          ,  2,   AM3_CLKSEL_FIXED_DIV, NULL);

DEFINE_CLOCK_CTX (generic_sel_clk_data  , NULL, AM3_CLKSEL_CLK, NULL);
DEFINE_CLOCK_CTX (mpu_fck_data          , NULL, AM3_CLKSEL_CLK, &mpu_fck_regs);
DEFINE_CLOCK_CTX (l3_ick_data           , NULL, AM3_CLKSEL_CLK, &l3_ick_regs);
DEFINE_CLOCK_CTX (l3_instr_ick_data     , NULL, AM3_CLKSEL_CLK, &l3_instr_ick_regs);
DEFINE_CLOCK_CTX (l4ls_gclk_data        , NULL, AM3_CLKSEL_CLK, &l4ls_gclk_regs);
DEFINE_CLOCK_CTX (cefuse_fck_data       , NULL, AM3_CLKSEL_CLK, &cefuse_fck_regs);
DEFINE_CLOCK_CTX (adc_tsc_ick_data      , NULL, AM3_CLKSEL_CLK, &adc_tsc_ick_regs);
DEFINE_CLOCK_CTX (aes0_fck_data         , NULL, AM3_CLKSEL_CLK, &aes0_fck_regs);
DEFINE_CLOCK_CTX (clkdiv32k_ick_data    , NULL, AM3_CLKSEL_CLK | AM3_CLKSEL_IGNORE_PARENT, &clkdiv32k_ick_regs);
DEFINE_CLOCK_CTX (control_fck_data      , NULL, AM3_CLKSEL_CLK, &control_fck_regs);
DEFINE_CLOCK_CTX (dcan0_fck_data        , NULL, AM3_CLKSEL_CLK, &dcan0_fck_regs);
DEFINE_CLOCK_CTX (dcan1_fck_data        , NULL, AM3_CLKSEL_CLK, &dcan1_fck_regs);
DEFINE_CLOCK_CTX (debugss_ick_data      , NULL, AM3_CLKSEL_CLK, &debugss_ick_regs);
DEFINE_CLOCK_CTX (elm_fck_data          , NULL, AM3_CLKSEL_CLK, &elm_fck_regs);
DEFINE_CLOCK_CTX (emif_fw_fck_data      , NULL, AM3_CLKSEL_CLK, &emif_fw_fck_regs);
DEFINE_CLOCK_CTX (epwmss0_fck_data      , NULL, AM3_CLKSEL_CLK, &epwmss0_fck_regs);
DEFINE_CLOCK_CTX (epwmss1_fck_data      , NULL, AM3_CLKSEL_CLK, &epwmss1_fck_regs);
DEFINE_CLOCK_CTX (epwmss2_fck_data      , NULL, AM3_CLKSEL_CLK, &epwmss2_fck_regs);
DEFINE_CLOCK_CTX (gpmc_fck_data         , NULL, AM3_CLKSEL_CLK, &gpmc_fck_regs);
DEFINE_CLOCK_CTX (ieee5000_fck_data     , NULL, AM3_CLKSEL_CLK, &ieee5000_fck_regs);
DEFINE_CLOCK_CTX (l4hs_ick_data         , NULL, AM3_CLKSEL_CLK, &l4hs_ick_regs);
DEFINE_CLOCK_CTX (l4wkup_ick_data       , NULL, AM3_CLKSEL_CLK, &l4wkup_ick_regs);
DEFINE_CLOCK_CTX (l4fw_ick_data         , NULL, AM3_CLKSEL_CLK, &l4fw_ick_regs);
DEFINE_CLOCK_CTX (l4ls_ick_data         , NULL, AM3_CLKSEL_CLK, &l4ls_ick_regs);
DEFINE_CLOCK_CTX (mailbox0_fck_data     , NULL, AM3_CLKSEL_CLK, &mailbox0_fck_regs);
DEFINE_CLOCK_CTX (mcasp0_fck_data       , NULL, AM3_CLKSEL_CLK, &mcasp0_fck_regs);
DEFINE_CLOCK_CTX (mcasp1_fck_data       , NULL, AM3_CLKSEL_CLK, &mcasp1_fck_regs);
DEFINE_CLOCK_CTX (mlb_fck_data          , NULL, AM3_CLKSEL_CLK, &mlb_fck_regs);
DEFINE_CLOCK_CTX (mmu_fck_data          , NULL, AM3_CLKSEL_CLK, &mmu_fck_regs);
DEFINE_CLOCK_CTX (ocmcram_ick_data      , NULL, AM3_CLKSEL_CLK, &ocmcram_ick_regs);
DEFINE_CLOCK_CTX (ocpwp_fck_data        , NULL, AM3_CLKSEL_CLK, &ocpwp_fck_regs);
DEFINE_CLOCK_CTX (pka_fck_data          , NULL, AM3_CLKSEL_CLK, &pka_fck_regs);
DEFINE_CLOCK_CTX (rng_fck_data          , NULL, AM3_CLKSEL_CLK, &rng_fck_regs);
DEFINE_CLOCK_CTX (rtc_fck_data          , NULL, AM3_CLKSEL_CLK, &rtc_fck_regs);
DEFINE_CLOCK_CTX (sha0_fck_data         , NULL, AM3_CLKSEL_CLK, &sha0_fck_regs);
DEFINE_CLOCK_CTX (smartreflex0_fck_data , NULL, AM3_CLKSEL_CLK, &smartreflex0_fck_regs);
DEFINE_CLOCK_CTX (smartreflex1_fck_data , NULL, AM3_CLKSEL_CLK, &smartreflex1_fck_regs);
DEFINE_CLOCK_CTX (spinlock_fck_data     , NULL, AM3_CLKSEL_CLK, &spinlock_fck_regs);
DEFINE_CLOCK_CTX (timer0_fck_data       , NULL, AM3_CLKSEL_CLK, &timer0_fck_regs);
DEFINE_CLOCK_CTX (tpcc_ick_data         , NULL, AM3_CLKSEL_CLK, &tpcc_ick_regs);
DEFINE_CLOCK_CTX (tptc0_ick_data        , NULL, AM3_CLKSEL_CLK, &tptc0_ick_regs);
DEFINE_CLOCK_CTX (tptc1_ick_data        , NULL, AM3_CLKSEL_CLK, &tptc1_ick_regs);
DEFINE_CLOCK_CTX (tptc2_ick_data        , NULL, AM3_CLKSEL_CLK, &tptc2_ick_regs);
DEFINE_CLOCK_CTX (wkup_m3_fck_data      , NULL, AM3_CLKSEL_CLK, &wkup_m3_fck_regs);
DEFINE_CLOCK_CTX (usbotg_ick_data       , NULL, AM3_CLKSEL_CLK, &usbotg_ick_regs);
DEFINE_CLOCK_CTX (usbotg_fck_data       , NULL, AM3_CLKSEL_CLK, &usbotg_fck_regs);
DEFINE_CLOCK_CTX (gpio0_ick_data        , NULL, AM3_CLKSEL_CLK, &gpio0_ick_regs);
DEFINE_CLOCK_CTX (gpio1_dbclk_data      , NULL, AM3_CLKSEL_CLK, &gpio1_dbclk_regs);
DEFINE_CLOCK_CTX (gpio1_ick_data        , NULL, AM3_CLKSEL_CLK, &gpio1_ick_regs);
DEFINE_CLOCK_CTX (gpio2_dbclk_data      , NULL, AM3_CLKSEL_CLK, &gpio2_dbclk_regs);
DEFINE_CLOCK_CTX (gpio2_ick_data        , NULL, AM3_CLKSEL_CLK, &gpio2_ick_regs);
DEFINE_CLOCK_CTX (gpio3_dbclk_data      , NULL, AM3_CLKSEL_CLK, &gpio3_dbclk_regs);
DEFINE_CLOCK_CTX (gpio3_ick_data        , NULL, AM3_CLKSEL_CLK, &gpio3_ick_regs);
DEFINE_CLOCK_CTX (pruss_uart_gclk_data  , NULL, AM3_CLKSEL_CLK, &pruss_uart_gclk_regs);
DEFINE_CLOCK_CTX (mmc0_fck_data         , NULL, AM3_CLKSEL_CLK, &mmc0_fck_regs);
DEFINE_CLOCK_CTX (mmc1_fck_data         , NULL, AM3_CLKSEL_CLK, &mmc1_fck_regs);
DEFINE_CLOCK_CTX (mmc2_fck_data         , NULL, AM3_CLKSEL_CLK, &mmc2_fck_regs);
DEFINE_CLOCK_CTX (gfx_fclk_data         , NULL, AM3_CLKSEL_CLK, &gfx_fclk_regs);
DEFINE_CLOCK_CTX (clkout2_ck_data       , NULL, AM3_CLKSEL_CLK, &clkout2_ck_regs);
DEFINE_CLOCK_CTX (wdt0_fck_data         , NULL, AM3_CLKSEL_CLK, &wdt0_fck_regs);
DEFINE_CLOCK_CTX (ehrpwm0_tbclk_data    , NULL, AM3_CLKSEL_CLK, &ehrpwm0_tbclk_regs);
DEFINE_CLOCK_CTX (ehrpwm1_tbclk_data    , NULL, AM3_CLKSEL_CLK, &ehrpwm1_tbclk_regs);
DEFINE_CLOCK_CTX (ehrpwm2_tbclk_data    , NULL, AM3_CLKSEL_CLK, &ehrpwm2_tbclk_regs);

LOCAL AM3_CLOCK_SEL clksel_timer7_clk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER7_CLK, 0, AM335X_CLKSEL_MASK, 1, &tclkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER7_CLK, 1, AM335X_CLKSEL_MASK, 1, &sys_clkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER7_CLK, 2, AM335X_CLKSEL_MASK, 1, &clk_32khz_timer)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL clksel_timer2_clk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER2_CLK, 0, AM335X_CLKSEL_MASK, 1, &tclkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER2_CLK, 1, AM335X_CLKSEL_MASK, 1, &sys_clkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER2_CLK, 2, AM335X_CLKSEL_MASK, 1, &clk_32khz_timer)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL clksel_timer3_clk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER3_CLK, 0, AM335X_CLKSEL_MASK, 1, &tclkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER3_CLK, 1, AM335X_CLKSEL_MASK, 1, &sys_clkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER3_CLK, 2, AM335X_CLKSEL_MASK, 1, &clk_32khz_timer)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL clksel_timer4_clk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER4_CLK, 0, AM335X_CLKSEL_MASK, 1, &tclkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER4_CLK, 1, AM335X_CLKSEL_MASK, 1, &sys_clkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER4_CLK, 2, AM335X_CLKSEL_MASK, 1, &clk_32khz_timer)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL cm_mac_clk_sel_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_MAC_CLKSEL, 0, AM335X_CLKSEL_MASK, 2, &sysclk2_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_MAC_CLKSEL, 1, AM335X_CLKSEL_MASK, 5, &sysclk2_ck)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL clksel_timer5_clk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER5_CLK, 0, AM335X_CLKSEL_MASK, 1, &tclkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER5_CLK, 1, AM335X_CLKSEL_MASK, 1, &sys_clkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER5_CLK, 2, AM335X_CLKSEL_MASK, 1, &clk_32khz_timer)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL clksel_timer6_clk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER6_CLK, 0, AM335X_CLKSEL_MASK, 1, &tclkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER6_CLK, 1, AM335X_CLKSEL_MASK, 1, &sys_clkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER6_CLK, 2, AM335X_CLKSEL_MASK, 1, &clk_32khz_timer)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL cm_cpts_rft_clksel_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_CPTS_RFT_CLKSEL, 0, AM335X_CLKSEL_MASK, 1, &sysclk2_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CM_CPTS_RFT_CLKSEL, 1, AM335X_CLKSEL_MASK, 1, &sysclk1_ck)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL clksel_timer1ms_clk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER1MS_CLK, 0, AM335X_CLKSEL_MASK, 1, &sys_clkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER1MS_CLK, 1, AM335X_CLKSEL_MASK, 1, &clk_32khz_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER1MS_CLK, 2, AM335X_CLKSEL_MASK, 1, &tclkin_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER1MS_CLK, 3, AM335X_CLKSEL_MASK, 1, &clk_rc32k_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_TIMER1MS_CLK, 4, AM335X_CLKSEL_MASK, 1, &clk_32768_ck)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL clksel_pruss_ocp_clk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_PRUSS_OCP_CLK, 0, AM335X_CLKSEL_MASK, 1, &l3_gclk)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_PRUSS_OCP_CLK, 1, AM335X_CLKSEL_MASK, 1, &disp_pll_clk)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL clksel_lcd_pixel_clk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_LCDC_PIXEL_CLK, 0, AM335X_CLKSEL_MASK, 1, &disp_pll_clk)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_LCDC_PIXEL_CLK, 1, AM335X_CLKSEL_MASK, 1, &sysclk2_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_LCDC_PIXEL_CLK, 2, AM335X_CLKSEL_MASK, 1, &per_192mhz_clk)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL clksel_wdt1_clk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_WDT1_CLK, 0, AM335X_CLKSEL_MASK, 1, &clk_rc32k_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_WDT1_CLK, 1, AM335X_CLKSEL_MASK, 1, &clk_32khz_ck)
    CLOCK_SEL_END()
    };

LOCAL AM3_CLOCK_SEL clksel_gpio0_dbclk_div[] =
    {
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_GPIO0_DBCLK, 0, AM335X_CLKSEL_MASK, 1, &clk_rc32k_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_GPIO0_DBCLK, 1, AM335X_CLKSEL_MASK, 1, &clk_32768_ck)
    DEFINE_CLOCK_SEL_ONE(AM335X_CLKSEL_GPIO0_DBCLK, 2, AM335X_CLKSEL_MASK, 1, &clk_32khz_ck)
    CLOCK_SEL_END()
    };

DEFINE_CLOCK_CTX (clksel_timer7_clk_data   , &clksel_timer7_clk_div   , AM3_CLKSEL_CLK, &timer7_fck_regs);
DEFINE_CLOCK_CTX (clksel_timer2_clk_data   , &clksel_timer2_clk_div   , AM3_CLKSEL_CLK, &timer2_fck_regs);
DEFINE_CLOCK_CTX (clksel_timer3_clk_data   , &clksel_timer3_clk_div   , AM3_CLKSEL_CLK, &timer3_fck_regs);
DEFINE_CLOCK_CTX (clksel_timer4_clk_data   , &clksel_timer4_clk_div   , AM3_CLKSEL_CLK, &timer4_fck_regs);
DEFINE_CLOCK_CTX (cm_mac_clk_sel_data      , &cm_mac_clk_sel_div      , AM3_CLKSEL_CLK, &cpgmac0_ick_regs);
DEFINE_CLOCK_CTX (clksel_timer5_clk_data   , &clksel_timer5_clk_div   , AM3_CLKSEL_CLK, &timer5_fck_regs);
DEFINE_CLOCK_CTX (clksel_timer6_clk_data   , &clksel_timer6_clk_div   , AM3_CLKSEL_CLK, &timer6_fck_regs);
DEFINE_CLOCK_CTX (cm_cpts_rft_clksel_data  , &cm_cpts_rft_clksel_div  , AM3_CLKSEL_CLK, NULL);
DEFINE_CLOCK_CTX (clksel_timer1ms_clk_data , &clksel_timer1ms_clk_div , AM3_CLKSEL_CLK, &timer1_fck_regs);
DEFINE_CLOCK_CTX (clksel_pruss_ocp_clk_data, &clksel_pruss_ocp_clk_div, AM3_CLKSEL_CLK, NULL);
DEFINE_CLOCK_CTX (clksel_lcd_pixel_clk_data, &clksel_lcd_pixel_clk_div, AM3_CLKSEL_CLK, NULL);
DEFINE_CLOCK_CTX (clksel_wdt1_clk_data     , &clksel_wdt1_clk_div     , AM3_CLKSEL_CLK, &wdt1_fck_regs);
DEFINE_CLOCK_CTX (clksel_gpio0_dbclk_data  , &clksel_gpio0_dbclk_div  , AM3_CLKSEL_CLK, NULL);
DEFINE_CLOCK_CTX (gpio0_dbclk_data         , &clksel_gpio0_dbclk_div  , AM3_CLKSEL_CLK, &gpio0_dbclk_regs);
DEFINE_CLOCK_CTX (lcdc_fck_data            , &clksel_gpio0_dbclk_div  , AM3_CLKSEL_CLK, &lcdc_fck_regs);

DEFINE_VXB_CLOCK (sys_clkin_ck      , 0, &virt_24m_ck       , NULL, NULL, &sys_clkin_ck_clksel_data);
DEFINE_VXB_CLOCK (dpll_core_ck      , 0, &sys_clkin_ck      , NULL, NULL, &dpll_core_ck_data);
DEFINE_VXB_CLOCK (dpll_core_x2_ck   , 0, &dpll_core_ck      , NULL, NULL, &dpll_core_x2_ck_data);
DEFINE_VXB_CLOCK (dpll_mpu_ck       , 0, &sys_clkin_ck      , NULL, NULL, &dpll_mpu_ck_data);
DEFINE_VXB_CLOCK (dpll_ddr_ck       , 0, &sys_clkin_ck      , NULL, NULL, &dpll_ddr_ck_data);
DEFINE_VXB_CLOCK (dpll_disp_ck      , 0, &sys_clkin_ck      , NULL, NULL, &dpll_disp_ck_data);
DEFINE_VXB_CLOCK (dpll_per_ck       , 0, &sys_clkin_ck      , NULL, NULL, &dpll_per_ck_data);
DEFINE_VXB_CLOCK (dpll_core_m4_ck   , 0, &dpll_core_x2_ck   , NULL, NULL, &dpll_core_m4_data);
DEFINE_VXB_CLOCK (dpll_core_m5_ck   , 0, &dpll_core_x2_ck   , NULL, NULL, &dpll_core_m5_data);
DEFINE_VXB_CLOCK (dpll_core_m6_ck   , 0, &dpll_core_x2_ck   , NULL, NULL, &dpll_core_m6_data);
DEFINE_VXB_CLOCK (sysclk1_ck        , 0, &dpll_core_m4_ck   , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (sysclk2_ck        , 0, &dpll_core_m5_ck   , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (core_clk_out      , 0, &dpll_core_m4_ck   , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (dpll_mpu_m2_ck    , 0, &dpll_mpu_ck       , NULL, NULL, &dpll_mpu_m2_data);
DEFINE_VXB_CLOCK (mpu_fck           , 0, &dpll_mpu_m2_ck    , NULL, NULL, &mpu_fck_data);
DEFINE_VXB_CLOCK (dpll_ddr_m2_ck    , 0, &dpll_ddr_ck       , NULL, NULL, &dpll_ddr_m2_data);
DEFINE_VXB_CLOCK (ddr_pll_clk       , 0, &dpll_ddr_m2_ck    , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (emif_fck          , 0, &ddr_pll_clk       , NULL, NULL, &emif_fck_data);
DEFINE_VXB_CLOCK (dpll_disp_m2_ck   , 0, &dpll_disp_ck      , NULL, NULL, &dpll_disp_m2_data);
DEFINE_VXB_CLOCK (disp_pll_clk      , 0, &dpll_disp_m2_ck   , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (dpll_per_m2_ck    , 0, &dpll_per_ck       , NULL, NULL, &dpll_per_m2_data);
DEFINE_VXB_CLOCK (per_192mhz_clk    , 0, &dpll_per_m2_ck    , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (usb_pll_clk       , 0, &dpll_per_ck       , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (core_100mhz_ck    , 0, &sysclk1_ck        , NULL, NULL, &core_100mhz_ck_data);
DEFINE_VXB_CLOCK (l3_aon_gclk       , 0, &sysclk1_ck        , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (l4_wkup_aon_gclk  , 0, &sysclk1_ck        , NULL, NULL, &l4_wkup_aon_gclk_data);
DEFINE_VXB_CLOCK (l3_gclk           , 0, &sysclk1_ck        , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (l3_ick            , 0, &l3_gclk           , NULL, NULL, &l3_ick_data);
DEFINE_VXB_CLOCK (l3_instr_ick      , 0, &l3_gclk           , NULL, NULL, &l3_instr_ick_data);
DEFINE_VXB_CLOCK (l4_wkup_gclk      , 0, &sysclk1_ck        , NULL, NULL, &l4_wkup_gclk_data);
DEFINE_VXB_CLOCK (l4hs_gclk         , 0, &sysclk1_ck        , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (gfx_l3_gclk       , 0, &sysclk1_ck        , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (debug_clka_gclk   , 0, &sysclk1_ck        , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (l4_rtc_gclk       , 0, &sysclk1_ck        , NULL, NULL, &l4_rtc_gclk_data);
DEFINE_VXB_CLOCK (rtc_ick           , 0, &l4_rtc_gclk       , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (l3s_gclk          , 0, &core_100mhz_ck    , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (l4fw_gclk         , 0, &core_100mhz_ck    , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (l4ls_gclk         , 0, &core_100mhz_ck    , NULL, NULL, &l4ls_gclk_data);
DEFINE_VXB_CLOCK (clk_24mhz         , 0, &per_192mhz_clk    , NULL, NULL, &clk_24mhz_data);
DEFINE_VXB_CLOCK (l4_cefuse_gclk    , 0, &core_100mhz_ck    , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (cefuse_iclk       , 0, &l4_cefuse_gclk    , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (cefuse_fck        , 0, &sys_clkin_ck      , NULL, NULL, &cefuse_fck_data);
DEFINE_VXB_CLOCK (sysclk_div_ck     , 0, &dpll_core_m4_ck   , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (adc_tsc_fck       , 0, &sys_clkin_ck      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (adc_tsc_ick       , 0, &l4_wkup_gclk      , NULL, NULL, &adc_tsc_ick_data);
DEFINE_VXB_CLOCK (aes0_fck          , 0, &l3_gclk           , NULL, NULL, &aes0_fck_data);
DEFINE_VXB_CLOCK (clkdiv32k_ick     , 32768, &clk_24mhz         , NULL  , NULL, &clkdiv32k_ick_data);
DEFINE_VXB_CLOCK (clk_32khz_ck      , 0, &clkdiv32k_ick     , NULL  , NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (control_fck       , 0, &l4_wkup_gclk      , NULL, NULL, &control_fck_data);
DEFINE_VXB_CLOCK (dcan0_ick         , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (dcan0_fck         , 0, &sys_clkin_ck      , NULL, NULL, &dcan0_fck_data);
DEFINE_VXB_CLOCK (dcan1_ick         , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (dcan1_fck         , 0, &sys_clkin_ck      , NULL, NULL, &dcan1_fck_data);
DEFINE_VXB_CLOCK (debugss_ick       , 0, &l3_aon_gclk       , NULL, NULL, &debugss_ick_data);
DEFINE_VXB_CLOCK (elm_fck           , 0, &l4ls_gclk         , NULL, NULL, &elm_fck_data);
DEFINE_VXB_CLOCK (emif_fw_fck       , 0, &l4fw_gclk         , NULL, NULL, &emif_fw_fck_data);
DEFINE_VXB_CLOCK (epwmss0_fck       , 0, &l4ls_gclk         , NULL, NULL, &epwmss0_fck_data);
DEFINE_VXB_CLOCK (epwmss1_fck       , 0, &l4ls_gclk         , NULL, NULL, &epwmss1_fck_data);
DEFINE_VXB_CLOCK (epwmss2_fck       , 0, &l4ls_gclk         , NULL, NULL, &epwmss2_fck_data);
DEFINE_VXB_CLOCK (gpmc_fck          , 0, &l3s_gclk          , NULL, NULL, &gpmc_fck_data);
DEFINE_VXB_CLOCK (i2c1_ick          , 0, &l4_wkup_gclk      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (i2c1_fck          , 0, &per_192mhz_clk    , NULL, NULL, &i2c1_fck_data);
DEFINE_VXB_CLOCK (i2c2_ick          , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (i2c2_fck          , 0, &per_192mhz_clk    , NULL, NULL, &i2c2_fck_data);
DEFINE_VXB_CLOCK (i2c3_ick          , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (i2c3_fck          , 0, &per_192mhz_clk    , NULL, NULL, &i2c3_fck_data);
DEFINE_VXB_CLOCK (ieee5000_fck      , 0, &l3s_gclk          , NULL, NULL, &ieee5000_fck_data);
DEFINE_VXB_CLOCK (l4hs_ick          , 0, &l4hs_gclk         , NULL, NULL, &l4hs_ick_data);
DEFINE_VXB_CLOCK (l4wkup_ick        , 0, &l4_wkup_aon_gclk  , NULL, NULL, &l4wkup_ick_data);
DEFINE_VXB_CLOCK (l4fw_ick          , 0, &core_100mhz_ck    , NULL, NULL, &l4fw_ick_data);
DEFINE_VXB_CLOCK (l4ls_ick          , 0, &l4ls_gclk         , NULL, NULL, &l4ls_ick_data);
DEFINE_VXB_CLOCK (mailbox0_fck      , 0, &l4ls_gclk         , NULL, NULL, &mailbox0_fck_data);
DEFINE_VXB_CLOCK (mcasp0_ick        , 0, &l3s_gclk          , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (mcasp0_fck        , 0, &sys_clkin_ck      , NULL, NULL, &mcasp0_fck_data);
DEFINE_VXB_CLOCK (mcasp1_ick        , 0, &l3s_gclk          , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (mcasp1_fck        , 0, &sys_clkin_ck      , NULL, NULL, &mcasp1_fck_data);
DEFINE_VXB_CLOCK (mlb_fck           , 0, &sysclk_div_ck     , NULL, NULL, &mlb_fck_data);
DEFINE_VXB_CLOCK (mmu_fck           , 0, &gfx_l3_gclk       , NULL, NULL, &mmu_fck_data    );
DEFINE_VXB_CLOCK (ocmcram_ick       , 0, &l3_gclk           , NULL, NULL, &ocmcram_ick_data);
DEFINE_VXB_CLOCK (ocpwp_fck         , 0, &l4ls_gclk         , NULL, NULL, &ocpwp_fck_data  );
DEFINE_VXB_CLOCK (pka_fck           , 0, &l4ls_gclk         , NULL, NULL, &pka_fck_data    );
DEFINE_VXB_CLOCK (rng_fck           , 0, &l4ls_gclk         , NULL, NULL, &rng_fck_data    );
DEFINE_VXB_CLOCK (rtc_fck           , 0, &clk_32768_ck      , NULL, NULL, &rtc_fck_data    );
DEFINE_VXB_CLOCK (sha0_fck          , 0, &l3_gclk           , NULL, NULL, &sha0_fck_data   );
DEFINE_VXB_CLOCK (smartreflex0_ick  , 0, &l4_wkup_gclk      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (smartreflex0_fck  , 0, &sys_clkin_ck      , NULL, NULL, &smartreflex0_fck_data);
DEFINE_VXB_CLOCK (smartreflex1_ick  , 0, &l4_wkup_gclk      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (smartreflex1_fck  , 0, &sys_clkin_ck      , NULL, NULL, &smartreflex1_fck_data);
DEFINE_VXB_CLOCK (spi0_ick          , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (spi0_fck          , 0, &per_192mhz_clk    , NULL, NULL, &spi0_fck_data);
DEFINE_VXB_CLOCK (spi1_ick          , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (spi1_fck          , 0, &per_192mhz_clk    , NULL, NULL, &spi1_fck_data);
DEFINE_VXB_CLOCK (spinlock_fck      , 0, &l4ls_gclk         , NULL, NULL, &spinlock_fck_data);
DEFINE_VXB_CLOCK (clk_32khz_timer   , 0, &clk_32khz_ck      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (timer0_ick        , 0, &l4_wkup_gclk      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (timer0_fck        , 0, &clk_rc32k_ck      , NULL, NULL, &timer0_fck_data);
DEFINE_VXB_CLOCK (timer1_ick        , 0, &l4_wkup_gclk      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (timer2_ick        , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (timer3_ick        , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (timer4_ick        , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (timer5_ick        , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (timer6_ick        , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (timer7_ick        , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (tpcc_ick          , 0, &l3_gclk           , NULL, NULL, &tpcc_ick_data);
DEFINE_VXB_CLOCK (tptc0_ick         , 0, &l3_gclk           , NULL, NULL, &tptc0_ick_data);
DEFINE_VXB_CLOCK (tptc1_ick         , 0, &l3_gclk           , NULL, NULL, &tptc1_ick_data);
DEFINE_VXB_CLOCK (tptc2_ick         , 0, &l3_gclk           , NULL, NULL, &tptc2_ick_data);
DEFINE_VXB_CLOCK (uart1_ick         , 0, &l4_wkup_gclk      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (uart1_fck         , 0, &per_192mhz_clk    , NULL, NULL, &uart1_fck_data);
DEFINE_VXB_CLOCK (uart2_ick         , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (uart2_fck         , 0, &per_192mhz_clk    , NULL, NULL, &uart2_fck_data);
DEFINE_VXB_CLOCK (uart3_ick         , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (uart3_fck         , 0, &per_192mhz_clk    , NULL, NULL, &uart3_fck_data);
DEFINE_VXB_CLOCK (uart4_ick         , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (uart4_fck         , 0, &per_192mhz_clk    , NULL, NULL, &uart4_fck_data);
DEFINE_VXB_CLOCK (uart5_ick         , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (uart5_fck         , 0, &per_192mhz_clk    , NULL, NULL, &uart5_fck_data);
DEFINE_VXB_CLOCK (uart6_ick         , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (uart6_fck         , 0, &per_192mhz_clk    , NULL, NULL, &uart6_fck_data);
DEFINE_VXB_CLOCK (wkup_m3_fck       , 0, &l4_wkup_aon_gclk  , NULL, NULL, &wkup_m3_fck_data);
DEFINE_VXB_CLOCK (cpsw_250mhz_clk   , 0, &sysclk2_ck        , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (cpsw_125mhz_gclk  , 0, &sysclk2_ck        , NULL, NULL, &cpsw_125mhz_gclk_data);
DEFINE_VXB_CLOCK (cpsw_50mhz_clk    , 0, &sysclk2_ck        , NULL, NULL, &cpsw_50mhz_clk_data);
DEFINE_VXB_CLOCK (cpsw_5mhz_clk     , 0, &cpsw_50mhz_clk    , NULL, NULL, &cpsw_5mhz_clk_data);
DEFINE_VXB_CLOCK (usbotg_ick        , 0, &l3s_gclk          , NULL, NULL, &usbotg_ick_data);
DEFINE_VXB_CLOCK (usbotg_fck        , 0, &usb_pll_clk       , NULL, NULL, &usbotg_fck_data);
DEFINE_VXB_CLOCK (gpio0_ick         , 0, &l4_wkup_gclk      , NULL, NULL, &gpio0_ick_data);
DEFINE_VXB_CLOCK (gpio1_dbclk       , 0, &clkdiv32k_ick     , NULL, NULL, &gpio1_dbclk_data);
DEFINE_VXB_CLOCK (gpio1_ick         , 0, &l4ls_gclk         , NULL, NULL, &gpio1_ick_data);
DEFINE_VXB_CLOCK (gpio2_dbclk       , 0, &clkdiv32k_ick     , NULL, NULL, &gpio2_dbclk_data);
DEFINE_VXB_CLOCK (gpio2_ick         , 0, &l4ls_gclk         , NULL, NULL, &gpio2_ick_data);
DEFINE_VXB_CLOCK (gpio3_dbclk       , 0, &clkdiv32k_ick     , NULL, NULL, &gpio3_dbclk_data);
DEFINE_VXB_CLOCK (gpio3_ick         , 0, &l4ls_gclk         , NULL, NULL, &gpio3_ick_data);
DEFINE_VXB_CLOCK (pruss_iep_gclk    , 0, &l3_gclk           , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (pruss_uart_gclk   , 0, &per_192mhz_clk    , NULL, NULL, &pruss_uart_gclk_data);
DEFINE_VXB_CLOCK (lcdc_ick          , 0, &sysclk1_ck        , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (mmc_clk           , 0, &per_192mhz_clk    , NULL, NULL, &mmc_clk_data);
DEFINE_VXB_CLOCK (mmc0_ick          , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (mmc0_fck          , 0, &mmc_clk           , NULL, NULL, &mmc0_fck_data);
DEFINE_VXB_CLOCK (mmc1_ick          , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (mmc1_fck          , 0, &mmc_clk           , NULL, NULL, &mmc1_fck_data);
DEFINE_VXB_CLOCK (mmc2_ick          , 0, &l4ls_gclk         , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (mmc2_fck          , 0, &mmc_clk           , NULL, NULL, &mmc2_fck_data);
DEFINE_VXB_CLOCK (gfx_fclk_clksel_ck, 0, &sysclk1_ck        , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (gfx_ick           , 0, &gfx_l3_gclk       , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (gfx_fclk          , 0, &gfx_fclk_clksel_ck, NULL, NULL, &gfx_fclk_data);
DEFINE_VXB_CLOCK (sysclkout_pre_ck  , 0, &clk_32768_ck      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (clkout2_ck        , 0, &sysclkout_pre_ck  , NULL, NULL, &clkout2_ck_data);
DEFINE_VXB_CLOCK (vtp_clk           , 0, &sys_clkin_ck      , NULL, NULL, &vtp_clk_data);
DEFINE_VXB_CLOCK (wdt0_ick          , 0, &l4_wkup_gclk      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (wdt0_fck          , 0, &clk_rc32k_ck      , NULL, NULL, &wdt0_fck_data);
DEFINE_VXB_CLOCK (wdt1_ick          , 0, &l4_wkup_gclk      , NULL, NULL, &generic_sel_clk_data);
DEFINE_VXB_CLOCK (ehrpwm0_tbclk     , 0, &dpll_per_m2_ck    , NULL, NULL, &ehrpwm0_tbclk_data);
DEFINE_VXB_CLOCK (ehrpwm1_tbclk     , 0, &dpll_per_m2_ck    , NULL, NULL, &ehrpwm1_tbclk_data);
DEFINE_VXB_CLOCK (ehrpwm2_tbclk     , 0, &dpll_per_m2_ck    , NULL, NULL, &ehrpwm2_tbclk_data);
DEFINE_VXB_CLOCK (timer1_fck        , 0, &sys_clkin_ck      , NULL, NULL, &clksel_timer1ms_clk_data);
DEFINE_VXB_CLOCK (timer2_fck        , 0, &sys_clkin_ck      , NULL, NULL, &clksel_timer2_clk_data);
DEFINE_VXB_CLOCK (timer3_fck        , 0, &sys_clkin_ck      , NULL, NULL, &clksel_timer3_clk_data);
DEFINE_VXB_CLOCK (timer4_fck        , 0, &sys_clkin_ck      , NULL, NULL, &clksel_timer4_clk_data);
DEFINE_VXB_CLOCK (timer5_fck        , 0, &sys_clkin_ck      , NULL, NULL, &clksel_timer5_clk_data);
DEFINE_VXB_CLOCK (timer6_fck        , 0, &sys_clkin_ck      , NULL, NULL, &clksel_timer6_clk_data);
DEFINE_VXB_CLOCK (timer7_fck        , 0, &sys_clkin_ck      , NULL, NULL, &clksel_timer7_clk_data);
DEFINE_VXB_CLOCK (cpgmac0_ick       , 0, &cpsw_125mhz_gclk  , NULL, NULL, &cm_mac_clk_sel_data);
DEFINE_VXB_CLOCK (cpsw_cpts_rft_clk , 0, &sysclk2_ck        , NULL, NULL, &cm_cpts_rft_clksel_data);
DEFINE_VXB_CLOCK (gpio0_dbclk_mux_ck, 0, &clk_rc32k_ck      , NULL, NULL, &clksel_gpio0_dbclk_data);
DEFINE_VXB_CLOCK (pruss_ocp_gclk    , 0, &l3_gclk           , NULL, NULL, &clksel_pruss_ocp_clk_data);
DEFINE_VXB_CLOCK (lcd_gclk          , 0, &disp_pll_clk      , NULL, NULL, &clksel_lcd_pixel_clk_data);
DEFINE_VXB_CLOCK (wdt1_fck          , 0, &clk_32khz_ck      , NULL, NULL, &clksel_wdt1_clk_data);
DEFINE_VXB_CLOCK (gpio0_dbclk       , 0, &gpio0_dbclk_mux_ck, NULL, NULL, &gpio0_dbclk_data);
DEFINE_VXB_CLOCK (lcdc_fck          , 0, &lcd_gclk          , NULL, NULL, &lcdc_fck_data);

LOCAL VXB_CLK * usrClocks [] =
    {
    &clk_32768_ck      ,
    &clk_rc32k_ck      ,
    &virt_19_2m_ck     ,
    &virt_24m_ck       ,
    &virt_25m_ck       ,
    &virt_26m_ck       ,
    &tclkin_ck         ,
    &sys_clkin_ck      ,
    &dpll_core_ck      ,
    &dpll_core_x2_ck   ,
    &dpll_mpu_ck       ,
    &dpll_ddr_ck       ,
    &dpll_disp_ck      ,
    &dpll_per_ck       ,
    &dpll_core_m4_ck   ,
    &dpll_core_m5_ck   ,
    &dpll_core_m6_ck   ,
    &sysclk1_ck        ,
    &sysclk2_ck        ,
    &core_clk_out      ,
    &dpll_mpu_m2_ck    ,
    &mpu_fck           ,
    &dpll_ddr_m2_ck    ,
    &ddr_pll_clk       ,
    &emif_fck          ,
    &dpll_disp_m2_ck   ,
    &disp_pll_clk      ,
    &dpll_per_m2_ck    ,
    &per_192mhz_clk    ,
    &usb_pll_clk       ,
    &core_100mhz_ck    ,
    &l3_aon_gclk       ,
    &l4_wkup_aon_gclk  ,
    &l3_gclk           ,
    &l3_ick            ,
    &l3_instr_ick      ,
    &l4_wkup_gclk      ,
    &l4hs_gclk         ,
    &gfx_l3_gclk       ,
    &debug_clka_gclk   ,
    &l4_rtc_gclk       ,
    &rtc_ick           ,
    &l3s_gclk          ,
    &l4fw_gclk         ,
    &l4ls_gclk         ,
    &clk_24mhz         ,
    &l4_cefuse_gclk    ,
    &cefuse_iclk       ,
    &cefuse_fck        ,
    &sysclk_div_ck     ,
    &adc_tsc_fck       ,
    &adc_tsc_ick       ,
    &aes0_fck          ,
    &clkdiv32k_ick     ,
    &clk_32khz_ck      ,
    &control_fck       ,
    &dcan0_ick         ,
    &dcan0_fck         ,
    &dcan1_ick         ,
    &dcan1_fck         ,
    &debugss_ick       ,
    &elm_fck           ,
    &emif_fw_fck       ,
    &epwmss0_fck       ,
    &epwmss1_fck       ,
    &epwmss2_fck       ,
    &gpmc_fck          ,
    &i2c1_ick          ,
    &i2c1_fck          ,
    &i2c2_ick          ,
    &i2c2_fck          ,
    &i2c3_ick          ,
    &i2c3_fck          ,
    &ieee5000_fck      ,
    &l4hs_ick          ,
    &l4wkup_ick        ,
    &l4fw_ick          ,
    &l4ls_ick          ,
    &mailbox0_fck      ,
    &mcasp0_ick        ,
    &mcasp0_fck        ,
    &mcasp1_ick        ,
    &mcasp1_fck        ,
    &mlb_fck           ,
    &mmu_fck           ,
    &ocmcram_ick       ,
    &ocpwp_fck         ,
    &pka_fck           ,
    &rng_fck           ,
    &rtc_fck           ,
    &sha0_fck          ,
    &smartreflex0_ick  ,
    &smartreflex0_fck  ,
    &smartreflex1_ick  ,
    &smartreflex1_fck  ,
    &spi0_ick          ,
    &spi0_fck          ,
    &spi1_ick          ,
    &spi1_fck          ,
    &spinlock_fck      ,
    &clk_32khz_timer   ,
    &timer0_ick        ,
    &timer0_fck        ,
    &timer1_ick        ,
    &timer2_ick        ,
    &timer3_ick        ,
    &timer4_ick        ,
    &timer5_ick        ,
    &timer6_ick        ,
    &timer7_ick        ,
    &tpcc_ick          ,
    &tptc0_ick         ,
    &tptc1_ick         ,
    &tptc2_ick         ,
    &uart1_ick         ,
    &uart1_fck         ,
    &uart2_ick         ,
    &uart2_fck         ,
    &uart3_ick         ,
    &uart3_fck         ,
    &uart4_ick         ,
    &uart4_fck         ,
    &uart5_ick         ,
    &uart5_fck         ,
    &uart6_ick         ,
    &uart6_fck         ,
    &wkup_m3_fck       ,
    &cpsw_250mhz_clk   ,
    &cpsw_125mhz_gclk  ,
    &cpsw_50mhz_clk    ,
    &cpsw_5mhz_clk     ,
    &usbotg_ick        ,
    &usbotg_fck        ,
    &gpio0_ick         ,
    &gpio1_dbclk       ,
    &gpio1_ick         ,
    &gpio2_dbclk       ,
    &gpio2_ick         ,
    &gpio3_dbclk       ,
    &gpio3_ick         ,
    &pruss_iep_gclk    ,
    &pruss_uart_gclk   ,
    &lcdc_ick          ,
    &mmc_clk           ,
    &mmc0_ick          ,
    &mmc0_fck          ,
    &mmc1_ick          ,
    &mmc1_fck          ,
    &mmc2_ick          ,
    &mmc2_fck          ,
    &gfx_fclk_clksel_ck,
    &gfx_ick           ,
    &gfx_fclk          ,
    &sysclkout_pre_ck  ,
    &clkout2_ck        ,
    &vtp_clk           ,
    &wdt0_ick          ,
    &wdt0_fck          ,
    &wdt1_ick          ,
    &ehrpwm0_tbclk     ,
    &ehrpwm1_tbclk     ,
    &ehrpwm2_tbclk     ,
    &timer1_fck        ,
    &timer2_fck        ,
    &timer3_fck        ,
    &timer4_fck        ,
    &timer5_fck        ,
    &timer6_fck        ,
    &timer7_fck        ,
    &cpgmac0_ick       ,
    &cpsw_cpts_rft_clk ,
    &gpio0_dbclk_mux_ck,
    &pruss_ocp_gclk    ,
    &lcd_gclk          ,
    &wdt1_fck          ,
    &gpio0_dbclk       ,
    &lcdc_fck          ,
    NULL
    };

LOCAL struct vxb_clk_domain dumbClkDm =
    {
    {NULL, NULL},
    "dumbClkDm",
    {NULL, NULL},
    NULL,
    NULL
    };

LOCAL VXB_CLK_DOMAIN * usrClocksDm [] =
    {
    &dumbClkDm,
    NULL
    };

