# Automatically generated file: do not edit

##########################
# HDC_DEVICE_MANAGER Section
##########################


ifdef _WRS_CONFIG_HDC_DEVICE_MANAGER
VSBL_HDC_DEVICE_MANAGER_SRC = 
VSBL_HDC_DEVICE_MANAGER_DEPEND = 
ifdef _WRS_CONFIG_HDC_2_2_0_1_DEVICE_MANAGER_2_2_0_1
VSBL_HDC_DEVICE_MANAGER_SRC += HDC_DEVICE_MANAGER
VSBL_HDC_DEVICE_MANAGER_DEPEND += MOSQUITTO
HDC_DEVICE_MANAGER_FASTBUILD = YES
VSBL_HDC_DEVICE_MANAGER_PATH = $(WIND_BASE)/pkgs/app/hdc-2.2.0.1/dev-mgr
VSBL_HDC_DEVICE_MANAGER_VERSION = HDC_2_2_0_1_DEVICE_MANAGER_2_2_0_1
endif
endif

