# Automatically generated file: do not edit

##########################
# USER_MANAGEMENT_POLICY Section
##########################


ifdef _WRS_CONFIG_USER_MANAGEMENT_POLICY
VSBL_USER_MANAGEMENT_POLICY_SRC = 
VSBL_USER_MANAGEMENT_POLICY_DEPEND = 
ifdef _WRS_CONFIG_USER_MANAGEMENT_POLICY_1_0_1_0
VSBL_USER_MANAGEMENT_POLICY_SRC += USER_MANAGEMENT_POLICY
VSBL_USER_MANAGEMENT_POLICY_DEPEND += CORE_KERNEL
VSBL_USER_MANAGEMENT_POLICY_DEPEND += SEC_HASH
VSBL_USER_MANAGEMENT_POLICY_DEPEND += USER_MANAGEMENT
VSBL_USER_MANAGEMENT_POLICY_DEPEND += CORE_KERNEL
VSBL_USER_MANAGEMENT_POLICY_DEPEND += CORE_KERNEL
VSBL_USER_MANAGEMENT_POLICY_DEPEND += USER_MANAGEMENT
USER_MANAGEMENT_POLICY_FASTBUILD = YES
VSBL_USER_MANAGEMENT_POLICY_PATH = $(WIND_BASE)/pkgs/security/user_management_policy-1.0.1.0
VSBL_USER_MANAGEMENT_POLICY_VERSION = USER_MANAGEMENT_POLICY_1_0_1_0
endif
endif

