# Automatically generated file: do not edit

##########################
# CRYPTOMISC Section
##########################


ifdef _WRS_CONFIG_CRYPTOMISC
VSBL_CRYPTOMISC_SRC = 
VSBL_CRYPTOMISC_DEPEND = 
ifdef _WRS_CONFIG_CRYPTOMISC_1_0_0_7
ifdef _WRS_CONFIG_CRYPTOMISC_IPFREESCALE
VSBL_CRYPTOMISC_SRC += CRYPTOMISC_IPFREESCALE
endif
ifdef _WRS_CONFIG_CRYPTOMISC_IPHWCRYPTO
VSBL_CRYPTOMISC_SRC += CRYPTOMISC_IPHWCRYPTO
endif
VSBL_CRYPTOMISC_SRC += CRYPTOMISC
VSBL_CRYPTOMISC_DEPEND += OPENSSL
CRYPTOMISC_FASTBUILD = YES
VSBL_CRYPTOMISC_PATH = $(WIND_BASE)/pkgs/security/crypto_misc-1.0.0.7
VSBL_CRYPTOMISC_VERSION = CRYPTOMISC_1_0_0_7
endif
endif

