# Automatically generated file: do not edit

##########################
# DISK_ENCRYPTION Section
##########################


ifdef _WRS_CONFIG_DISK_ENCRYPTION
VSBL_DISK_ENCRYPTION_SRC = 
VSBL_DISK_ENCRYPTION_DEPEND = 
ifdef _WRS_CONFIG_DISK_ENCRYPTION_1_0_0_1
VSBL_DISK_ENCRYPTION_SRC += DISK_ENCRYPTION
VSBL_DISK_ENCRYPTION_DEPEND += BDM_XBD
VSBL_DISK_ENCRYPTION_DEPEND += FS_COMMON
VSBL_DISK_ENCRYPTION_DEPEND += SEC_CRYPTO
VSBL_DISK_ENCRYPTION_DEPEND += SEC_HASH
VSBL_DISK_ENCRYPTION_DEPEND += SEC_CRYPTO
VSBL_DISK_ENCRYPTION_DEPEND += BDM_XBD
VSBL_DISK_ENCRYPTION_DEPEND += FS_COMMON
DISK_ENCRYPTION_FASTBUILD = YES
DISK_ENCRYPTION_FRIEND = FS_COMMON
VSBL_DISK_ENCRYPTION_PATH = $(WIND_BASE)/pkgs/security/diskEncryption-1.0.0.1
VSBL_DISK_ENCRYPTION_VERSION = DISK_ENCRYPTION_1_0_0_1
endif
endif

