# Automatically generated file: do not edit

##########################
# IPNET_IPFREESCALE Section
##########################


ifdef _WRS_CONFIG_IPNET_IPFREESCALE
VSBL_IPNET_IPFREESCALE_SRC = 
VSBL_IPNET_IPFREESCALE_DEPEND = 
ifdef _WRS_CONFIG_IPNET_1_1_1_2_CRYPTO_1_0_0_9_IPFREESCALE_1_0_0_3
VSBL_IPNET_IPFREESCALE_SRC += IPNET_IPFREESCALE
VSBL_IPNET_IPFREESCALE_DEPEND += IPNET_IPHWCRYPTO
IPNET_IPFREESCALE_FASTBUILD = YES
VSBL_IPNET_IPFREESCALE_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/crypto-1.0.0.9/ipfreescale
VSBL_IPNET_IPFREESCALE_VERSION = IPNET_1_1_1_2_CRYPTO_1_0_0_9_IPFREESCALE_1_0_0_3
endif
endif

