# Automatically generated file: do not edit

##########################
# IPNET_FTP Section
##########################


ifdef _WRS_CONFIG_IPNET_FTP
VSBL_IPNET_FTP_SRC = 
VSBL_IPNET_FTP_DEPEND = 
ifdef _WRS_CONFIG_IPNET_1_1_1_2_FTP_1_0_4_3
VSBL_IPNET_FTP_SRC += IPNET_FTP
VSBL_IPNET_FTP_DEPEND += IPNET_COREIP
VSBL_IPNET_FTP_DEPEND += CORE_KERNEL
VSBL_IPNET_FTP_DEPEND += CORE_KERNEL
VSBL_IPNET_FTP_DEPEND += IPNET_COREIP
VSBL_IPNET_FTP_DEPEND += IPNET_COREIP
IPNET_FTP_FASTBUILD = YES
VSBL_IPNET_FTP_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/app/ftp-1.0.4.3
VSBL_IPNET_FTP_VERSION = IPNET_1_1_1_2_FTP_1_0_4_3
endif
endif

