# Automatically generated file: do not edit

##########################
# FS_DOSFS Section
##########################


ifdef _WRS_CONFIG_FS_DOSFS
VSBL_FS_DOSFS_SRC = 
VSBL_FS_DOSFS_DEPEND = 
ifdef _WRS_CONFIG_FS_1_0_0_2_DOSFS_1_0_0_15
VSBL_FS_DOSFS_SRC += FS_DOSFS
VSBL_FS_DOSFS_DEPEND += BDM_XBD
VSBL_FS_DOSFS_DEPEND += ERF
VSBL_FS_DOSFS_DEPEND += FS_COMMON
VSBL_FS_DOSFS_DEPEND += UTF
FS_DOSFS_FASTBUILD = YES
VSBL_FS_DOSFS_PATH = $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/dosfs-1.0.0.15
VSBL_FS_DOSFS_VERSION = FS_1_0_0_2_DOSFS_1_0_0_15
endif
endif

