# Automatically generated file: do not edit

##########################
# ARM_ARMV7A Section
##########################


ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_ARM_ARMV7A_SRC = 
VSBL_ARM_ARMV7A_DEPEND = 
ifdef _WRS_CONFIG_ARM_1_1_9_1_KERNEL_1_0_12_1_ARMV7A_1_0_9_1
VSBL_ARM_ARMV7A_SRC += ARM_ARMV7A
VSBL_ARM_ARMV7A_DEPEND += CORE_KERNEL
VSBL_ARM_ARMV7A_DEPEND += CORE_KERNEL
ARM_ARMV7A_FASTBUILD = YES
VSBL_ARM_ARMV7A_PATH = $(WIND_BASE)/pkgs/os/arch/arm-1.1.9.1/kernel/armv7a
VSBL_ARM_ARMV7A_VERSION = ARM_1_1_9_1_KERNEL_1_0_12_1_ARMV7A_1_0_9_1
endif
endif

