# Automatically generated file: do not edit

##########################
# BRANSON_LAYER_BRANSONHTTP Section
##########################


ifdef _WRS_CONFIG_BRANSON_LAYER_BRANSONHTTP
VSBL_BRANSON_LAYER_BRANSONHTTP_SRC = 
VSBL_BRANSON_LAYER_BRANSONHTTP_DEPEND = 
ifdef _WRS_CONFIG_BRANSON_LAYER_1_0_0_0_DRIVERS_1_0_0_0_BRANSONHTTP_1_1_1_1
VSBL_BRANSON_LAYER_BRANSONHTTP_SRC += BRANSON_LAYER_BRANSONHTTP
VSBL_BRANSON_LAYER_BRANSONHTTP_DEPEND += FS_DOSFS
VSBL_BRANSON_LAYER_BRANSONHTTP_DEPEND += ZLIB
VSBL_BRANSON_LAYER_BRANSONHTTP_DEPEND += WEBCLI_COMMON
BRANSON_LAYER_BRANSONHTTP_FASTBUILD = YES
VSBL_BRANSON_LAYER_BRANSONHTTP_PATH = C:/ScriptGSX2_4/GSX2_4Stream/_Branson_Driver_Layer/BRANSON_DRV/src/BransonHTTP
VSBL_BRANSON_LAYER_BRANSONHTTP_VERSION = BRANSON_LAYER_1_0_0_0_DRIVERS_1_0_0_0_BRANSONHTTP_1_1_1_1
endif
endif

