# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL_DEPEND = 
ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_DIAB_20_0_4_0_TOOLSRC_DIAB_KERNEL_5_9_3_0
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL_SRC += LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL
LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_diab-20.0.4.0/kernel
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_DIAB_20_0_4_0_TOOLSRC_DIAB_KERNEL_5_9_3_0
endif
endif

