# Automatically generated file: do not edit

##########################
# BRANSON_LAYER Section
##########################


ifdef _WRS_CONFIG_BRANSON_LAYER
VSBL_BRANSON_LAYER_SRC = 
VSBL_BRANSON_LAYER_DEPEND = 
ifdef _WRS_CONFIG_BRANSON_LAYER_1_0_0_0
ifdef _WRS_CONFIG_BRANSON_LAYER_DRIVERS
VSBL_BRANSON_LAYER_SRC += BRANSON_LAYER_DRIVERS
endif
ifdef _WRS_CONFIG_BRANSON_LAYER_BRANSONHTTP
VSBL_BRANSON_LAYER_SRC += BRANSON_LAYER_BRANSONHTTP
endif
ifdef _WRS_CONFIG_BRANSON_LAYER_BRANSONWEBSERVICES
VSBL_BRANSON_LAYER_SRC += BRANSON_LAYER_BRANSONWEBSERVICES
endif
ifdef _WRS_CONFIG_BRANSON_LAYER_TIDSSFB
VSBL_BRANSON_LAYER_SRC += BRANSON_LAYER_TIDSSFB
endif
VSBL_BRANSON_LAYER_SRC += BRANSON_LAYER
BRANSON_LAYER_FASTBUILD = YES
VSBL_BRANSON_LAYER_PATH = C:/ScriptGSX2_4/GSX2_4Stream/_Branson_Driver_Layer
VSBL_BRANSON_LAYER_VERSION = BRANSON_LAYER_1_0_0_0
endif
endif

