# Automatically generated file: do not edit

##########################
# FBDEV_XLNXLCVCFB Section
##########################


ifdef _WRS_CONFIG_FBDEV_XLNXLCVCFB
VSBL_FBDEV_XLNXLCVCFB_SRC = 
VSBL_FBDEV_XLNXLCVCFB_DEPEND = 
ifdef _WRS_CONFIG_FBDEV_1_0_0_2_XLNXLCVCFB_1_0_2_0
VSBL_FBDEV_XLNXLCVCFB_SRC += FBDEV_XLNXLCVCFB
VSBL_FBDEV_XLNXLCVCFB_DEPEND += FBDEV_COMMON
FBDEV_XLNXLCVCFB_FASTBUILD = YES
VSBL_FBDEV_XLNXLCVCFB_PATH = $(WIND_BASE)/pkgs/ui/fbdev-1.0.0.2/xlnxlcvc-1.0.2.0
VSBL_FBDEV_XLNXLCVCFB_VERSION = FBDEV_1_0_0_2_XLNXLCVCFB_1_0_2_0
endif
endif

