# Automatically generated file: do not edit

##########################
# LOADER_VXTEST Section
##########################


ifdef _WRS_CONFIG_LOADER_VXTEST
VSBL_LOADER_VXTEST_SRC = 
VSBL_LOADER_VXTEST_DEPEND = 
ifdef _WRS_CONFIG_LOADER_1_1_2_0_VXTEST_1_0_0_1
VSBL_LOADER_VXTEST_SRC += LOADER_VXTEST
VSBL_LOADER_VXTEST_DEPEND += CORE_KERNEL_VXTEST
LOADER_VXTEST_FASTBUILD = YES
VSBL_LOADER_VXTEST_PATH = $(WIND_BASE)/pkgs/os/utils/loader-1.1.2.0/vxTest
VSBL_LOADER_VXTEST_VERSION = LOADER_1_1_2_0_VXTEST_1_0_0_1
endif
endif

