# Automatically generated file: do not edit

##########################
# IPNET_TSN Section
##########################


ifdef _WRS_CONFIG_IPNET_TSN
VSBL_IPNET_TSN_SRC = 
VSBL_IPNET_TSN_DEPEND = 
ifdef _WRS_CONFIG_IPNET_1_1_1_2_TSN_1_0_0_1
ifdef _WRS_CONFIG_IPNET_QAVQBV
VSBL_IPNET_TSN_SRC += IPNET_QAVQBV
endif
VSBL_IPNET_TSN_SRC += IPNET_TSN
VSBL_IPNET_TSN_DEPEND += END_LIB
VSBL_IPNET_TSN_DEPEND += IPNET_COREIP
VSBL_IPNET_TSN_DEPEND += END
IPNET_TSN_FASTBUILD = YES
VSBL_IPNET_TSN_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/tsn-1.0.0.1
VSBL_IPNET_TSN_VERSION = IPNET_1_1_1_2_TSN_1_0_0_1
endif
endif

