# Automatically generated file: do not edit

##########################
# BRANSON_LAYER_BRANSONWEBSERVICES Section
##########################


ifdef _WRS_CONFIG_BRANSON_LAYER_BRANSONWEBSERVICES
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_SRC = 
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_DEPEND = 
ifdef _WRS_CONFIG_BRANSON_LAYER_1_0_0_0_DRIVERS_1_0_0_0_BRANSONWEBSERVICES_1_1_1_1
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_SRC += BRANSON_LAYER_BRANSONWEBSERVICES
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_DEPEND += FS_DOSFS
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_DEPEND += OPENSSL
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_DEPEND += WEBCLI_BACKPLANE
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_DEPEND += WEBCLI_MIBWAY
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_DEPEND += WEBCLI_COMMON
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_DEPEND += BRANSON_LAYER_BRANSONHTTP
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_DEPEND += WEBCLI_CLI
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_DEPEND += OPENSSL
BRANSON_LAYER_BRANSONWEBSERVICES_FASTBUILD = YES
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_PATH = C:/ScriptGSX2_4/GSX2_4Stream/_Branson_Driver_Layer/BRANSON_DRV/src/BransonWebservices
VSBL_BRANSON_LAYER_BRANSONWEBSERVICES_VERSION = BRANSON_LAYER_1_0_0_0_DRIVERS_1_0_0_0_BRANSONWEBSERVICES_1_1_1_1
endif
endif

