@ $Header: \Branson/AC/app/TestMacros.inc,v 1.1 2011/01/25 16:20:58 Aare Exp $

@ Application implementation of test macros, all empty. For macro usage, refer
@ to TestMacros.inc in uut folder.

.set	UnitTesting, 0

.macro InitDiagnostics
		.endm

.macro UnitTest label
		.endm

.macro Checkpoint number
		.endm

.macro CheckpointNE number
		.endm

.macro FaultNE number
		.endm

.macro ReturnFailed
		.endm

