# Automatically generated file: do not edit

##########################
# BRANSON_LAYER_TIDSSFB Section
##########################


ifdef _WRS_CONFIG_BRANSON_LAYER_TIDSSFB
VSBL_BRANSON_LAYER_TIDSSFB_SRC = 
VSBL_BRANSON_LAYER_TIDSSFB_DEPEND = 
ifdef _WRS_CONFIG_BRANSON_LAYER_1_0_0_0_DRIVERS_1_0_0_0_TIDSSFB_10_0_0_1
VSBL_BRANSON_LAYER_TIDSSFB_SRC += BRANSON_LAYER_TIDSSFB
VSBL_BRANSON_LAYER_TIDSSFB_DEPEND += FBDEV_COMMON
BRANSON_LAYER_TIDSSFB_FASTBUILD = YES
VSBL_BRANSON_LAYER_TIDSSFB_PATH = C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/_Branson_Driver_Layer/BRANSON_DRV/src/tidss
VSBL_BRANSON_LAYER_TIDSSFB_VERSION = BRANSON_LAYER_1_0_0_0_DRIVERS_1_0_0_0_TIDSSFB_10_0_0_1
endif
endif

