# Automatically generated file: do not edit

##########################
# BRANSON_LAYER_DRIVERS Section
##########################


ifdef _WRS_CONFIG_BRANSON_LAYER_DRIVERS
VSBL_BRANSON_LAYER_DRIVERS_SRC = 
VSBL_BRANSON_LAYER_DRIVERS_DEPEND = 
ifdef _WRS_CONFIG_BRANSON_LAYER_1_0_0_0_DRIVERS_1_0_0_0
ifdef _WRS_CONFIG_BRANSON_LAYER_TIDSSFB
VSBL_BRANSON_LAYER_DRIVERS_SRC += BRANSON_LAYER_TIDSSFB
endif
VSBL_BRANSON_LAYER_DRIVERS_SRC += BRANSON_LAYER_DRIVERS
BRANSON_LAYER_DRIVERS_FASTBUILD = YES
VSBL_BRANSON_LAYER_DRIVERS_PATH = C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/_Branson_Driver_Layer/BRANSON_DRV
VSBL_BRANSON_LAYER_DRIVERS_VERSION = BRANSON_LAYER_1_0_0_0_DRIVERS_1_0_0_0
endif
endif

