
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_USB_HCORE)




	
	

	
# copying directory h to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubBusManager.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubBusManager.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubBusManager.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubBusManager.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubMisc.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubMisc.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubMisc.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubMisc.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHcdInstr.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHcdInstr.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHcdInstr.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHcdInstr.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubInitialization.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubInitialization.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubInitialization.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubInitialization.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubTemplate.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubTemplate.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubTemplate.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubTemplate.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbTransUnit.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbTransUnit.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbTransUnit.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbTransUnit.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbdCoreLib.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbdCoreLib.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbdCoreLib.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbdCoreLib.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubCommon.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubCommon.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubCommon.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubCommon.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubUtility.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubUtility.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubUtility.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubUtility.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubPortEventHandler.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubPortEventHandler.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubPortEventHandler.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubPortEventHandler.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubEventHandler.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubEventHandler.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubEventHandler.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubEventHandler.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbdMisc.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbdMisc.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbdMisc.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbdMisc.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubGlobalVariables.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubGlobalVariables.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubGlobalVariables.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubGlobalVariables.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubClassInterface.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubClassInterface.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubClassInterface.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubClassInterface.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubHostStackInterface.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubHostStackInterface.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbHubHostStackInterface.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbHubHostStackInterface.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbd.h

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbd.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/usbd.h : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/h/usbd.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif




	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	


	
	
	
	
	
	
	
BUILD : USB_HCORE_src_diab__BUILD

.PHONY : USB_HCORE_src_diab__BUILD

__BUILD_FB_IDS += kernel_top_USB_HCORE_src_diab

USB_HCORE_src_diab__BUILD : 
	@ echo building USB_HCORE directory src
	+ @ cd C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/src && C:/WindRiverSR500New/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=kernel _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=USB_HCORE VSB_DIR=C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_USB_HCORE_src_diab BSPNAME=ti_sitara_ctxa15_branson_1_0_0_0 BUILDSTAGE=BUILD


	
	
	

	
	
	

	

	


	
# copying directory cdf to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/40usb_host.cdf

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/40usb_host.cdf





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/40usb_host.cdf : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/cdf/40usb_host.cdf | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	
cdf_PRENOBUILD_USB_HCORE_FILES = cdf/40usb_host.cdf

cdf_PRENOBUILD_USB_HCORE_DIR = C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14

PRENOBUILD_FILES += $(addprefix $(cdf_PRENOBUILD_USB_HCORE_DIR)/,$(cdf_PRENOBUILD_USB_HCORE_FILES))

PRENOBUILD : PRENOBUILD_USB_HCORE

PRENOBUILD_USB_HCORE : cdf_PRENOBUILD_USB_HCORE

cdf_PRENOBUILD_USB_HCORE : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_USB_HCORE.cdf

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_USB_HCORE.cdf : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_USB_HCORE.tmp
	$(CDFCOMP) -i $^ -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer USB_HCORE

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_USB_HCORE.tmp : | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf
	$(file >$@,$(call __vsb_tmpl_cdf_inter,$(addprefix $(cdf_PRENOBUILD_USB_HCORE_DIR)/,$(sort $(cdf_PRENOBUILD_USB_HCORE_FILES))),USB_HCORE))



	

	
# copying directory cfg to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/configlette




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/configlette/usrUsbShow.c

__FILES_TO_COPY_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/configlette/usrUsbShow.c





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/configlette/usrUsbShow.c : C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/core-1.0.0.14/cfg/usrUsbShow.c | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



	
__DIR_TARGETS += $(__DIR_TARGETS_USB_HCORE)

__DIR_TARGETS_USB_HCORE += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/configlette C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/share/h C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/vsblCdf

