
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_FONT_FREETYPE2)




	
	

	
# copying directory h to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public




# copying directory h/freetype to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ttnameid.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ttnameid.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ttnameid.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ttnameid.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftimage.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftimage.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftimage.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftimage.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fttrigon.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fttrigon.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fttrigon.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/fttrigon.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fterrdef.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fterrdef.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fterrdef.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/fterrdef.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ttunpat.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ttunpat.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ttunpat.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ttunpat.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/tttags.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/tttags.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/tttags.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/tttags.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsnames.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsnames.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsnames.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftsnames.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftgasp.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftgasp.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftgasp.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftgasp.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmoderr.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmoderr.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmoderr.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftmoderr.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftxf86.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftxf86.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftxf86.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftxf86.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmm.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmm.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmm.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftmm.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftbbox.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftbbox.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftbbox.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftbbox.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftotval.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftotval.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftotval.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftotval.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fttypes.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fttypes.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fttypes.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/fttypes.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/freetype.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/freetype.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/freetype.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/freetype.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmac.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmac.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmac.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftmac.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftwinfnt.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftwinfnt.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftwinfnt.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftwinfnt.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftgzip.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftgzip.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftgzip.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftgzip.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftgxval.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftgxval.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftgxval.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftgxval.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftcache.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftcache.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftcache.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftcache.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftbdf.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftbdf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftbdf.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftbdf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory h/freetype/internal to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/t1types.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/t1types.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/t1types.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/t1types.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/sfnt.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/sfnt.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/sfnt.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/sfnt.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/tttypes.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/tttypes.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/tttypes.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/tttypes.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftcalc.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftcalc.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftcalc.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftcalc.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftmemory.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftmemory.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftmemory.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftmemory.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftrfork.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftrfork.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftrfork.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftrfork.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/pcftypes.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/pcftypes.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/pcftypes.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/pcftypes.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftdriver.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftdriver.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftdriver.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftdriver.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/fttrace.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/fttrace.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/fttrace.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/fttrace.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/autohint.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/autohint.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/autohint.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/autohint.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftvalid.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftvalid.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftvalid.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftvalid.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftgloadr.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftgloadr.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftgloadr.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftgloadr.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftobjs.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftobjs.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftobjs.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftobjs.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory h/freetype/internal/services to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svotval.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svotval.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svotval.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svotval.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svwinfnt.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svwinfnt.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svwinfnt.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svwinfnt.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svgxval.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svgxval.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svgxval.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svgxval.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svkern.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svkern.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svkern.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svkern.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpsinfo.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpsinfo.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpsinfo.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svpsinfo.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svbdf.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svbdf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svbdf.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svbdf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svttcmap.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svttcmap.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svttcmap.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svttcmap.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svmm.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svmm.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svmm.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svmm.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpfr.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpfr.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpfr.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svpfr.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpostnm.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpostnm.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpostnm.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svpostnm.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svtteng.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svtteng.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svtteng.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svtteng.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svxf86nm.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svxf86nm.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svxf86nm.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svxf86nm.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svgldict.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svgldict.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svgldict.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svgldict.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpscmap.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpscmap.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svpscmap.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svpscmap.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svsfnt.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svsfnt.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services/svsfnt.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svsfnt.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftdebug.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftdebug.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftdebug.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftdebug.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftserv.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftserv.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftserv.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftserv.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/pshints.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/pshints.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/pshints.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/pshints.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/psaux.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/psaux.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/psaux.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/psaux.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/internal.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/internal.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/internal.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/internal.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftstream.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftstream.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/ftstream.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftstream.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftchapters.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftchapters.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftchapters.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftchapters.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftincrem.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftincrem.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftincrem.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftincrem.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftlist.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftlist.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftlist.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftlist.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftglyph.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftglyph.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftglyph.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftglyph.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftlzw.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftlzw.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftlzw.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftlzw.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftrender.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftrender.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftrender.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftrender.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsizes.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsizes.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsizes.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftsizes.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftpfr.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftpfr.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftpfr.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftpfr.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftlcdfil.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftlcdfil.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftlcdfil.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftlcdfil.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsynth.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsynth.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsynth.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftsynth.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsystem.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsystem.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftsystem.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftsystem.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmodapi.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmodapi.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftmodapi.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftmodapi.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftbitmap.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftbitmap.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftbitmap.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftbitmap.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory h/freetype/config to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftheader.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftheader.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftheader.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/config/ftheader.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftoption.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftoption.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftoption.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/config/ftoption.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftmodule.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftmodule.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftmodule.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/config/ftmodule.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftconfig.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftconfig.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftconfig.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/config/ftconfig.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftstdlib.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftstdlib.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config/ftstdlib.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/config/ftstdlib.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fterrors.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fterrors.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/fterrors.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/fterrors.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/t1tables.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/t1tables.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/t1tables.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/t1tables.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftstroke.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftstroke.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftstroke.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftstroke.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftoutln.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftoutln.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/ftoutln.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftoutln.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/tttables.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/tttables.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/tttables.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/tttables.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/ft2build.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/ft2build.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/ft2build.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/ft2build.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif




	
	
	
	
	
	
	
	
	
	
# copying directory h to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public




# copying directory h/freetype to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ttnameid.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ttnameid.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ttnameid.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ttnameid.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftimage.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftimage.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftimage.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftimage.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fttrigon.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fttrigon.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fttrigon.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/fttrigon.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fterrdef.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fterrdef.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fterrdef.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/fterrdef.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ttunpat.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ttunpat.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ttunpat.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ttunpat.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/tttags.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/tttags.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/tttags.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/tttags.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsnames.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsnames.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsnames.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftsnames.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftgasp.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftgasp.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftgasp.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftgasp.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmoderr.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmoderr.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmoderr.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftmoderr.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftxf86.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftxf86.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftxf86.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftxf86.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmm.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmm.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmm.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftmm.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftbbox.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftbbox.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftbbox.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftbbox.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftotval.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftotval.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftotval.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftotval.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fttypes.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fttypes.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fttypes.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/fttypes.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/freetype.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/freetype.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/freetype.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/freetype.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmac.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmac.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmac.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftmac.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftwinfnt.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftwinfnt.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftwinfnt.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftwinfnt.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftgzip.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftgzip.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftgzip.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftgzip.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftgxval.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftgxval.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftgxval.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftgxval.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftcache.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftcache.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftcache.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftcache.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftbdf.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftbdf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftbdf.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftbdf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory h/freetype/internal to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/t1types.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/t1types.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/t1types.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/t1types.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/sfnt.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/sfnt.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/sfnt.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/sfnt.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/tttypes.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/tttypes.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/tttypes.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/tttypes.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftcalc.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftcalc.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftcalc.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftcalc.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftmemory.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftmemory.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftmemory.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftmemory.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftrfork.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftrfork.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftrfork.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftrfork.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/pcftypes.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/pcftypes.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/pcftypes.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/pcftypes.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftdriver.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftdriver.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftdriver.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftdriver.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/fttrace.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/fttrace.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/fttrace.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/fttrace.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/autohint.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/autohint.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/autohint.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/autohint.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftvalid.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftvalid.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftvalid.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftvalid.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftgloadr.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftgloadr.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftgloadr.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftgloadr.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftobjs.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftobjs.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftobjs.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftobjs.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory h/freetype/internal/services to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svotval.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svotval.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svotval.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svotval.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svwinfnt.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svwinfnt.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svwinfnt.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svwinfnt.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svgxval.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svgxval.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svgxval.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svgxval.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svkern.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svkern.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svkern.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svkern.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpsinfo.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpsinfo.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpsinfo.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svpsinfo.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svbdf.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svbdf.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svbdf.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svbdf.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svttcmap.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svttcmap.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svttcmap.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svttcmap.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svmm.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svmm.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svmm.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svmm.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpfr.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpfr.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpfr.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svpfr.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpostnm.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpostnm.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpostnm.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svpostnm.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svtteng.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svtteng.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svtteng.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svtteng.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svxf86nm.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svxf86nm.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svxf86nm.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svxf86nm.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svgldict.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svgldict.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svgldict.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svgldict.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpscmap.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpscmap.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svpscmap.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svpscmap.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svsfnt.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svsfnt.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services/svsfnt.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/services/svsfnt.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftdebug.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftdebug.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftdebug.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftdebug.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftserv.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftserv.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftserv.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftserv.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/pshints.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/pshints.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/pshints.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/pshints.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/psaux.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/psaux.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/psaux.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/psaux.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/internal.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/internal.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/internal.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/internal.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftstream.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftstream.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/ftstream.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/internal/ftstream.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftchapters.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftchapters.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftchapters.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftchapters.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftincrem.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftincrem.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftincrem.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftincrem.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftlist.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftlist.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftlist.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftlist.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftglyph.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftglyph.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftglyph.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftglyph.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftlzw.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftlzw.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftlzw.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftlzw.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftrender.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftrender.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftrender.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftrender.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsizes.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsizes.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsizes.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftsizes.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftpfr.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftpfr.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftpfr.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftpfr.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftlcdfil.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftlcdfil.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftlcdfil.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftlcdfil.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsynth.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsynth.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsynth.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftsynth.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsystem.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsystem.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftsystem.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftsystem.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmodapi.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmodapi.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftmodapi.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftmodapi.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftbitmap.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftbitmap.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftbitmap.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftbitmap.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory h/freetype/config to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftheader.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftheader.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftheader.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/config/ftheader.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftoption.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftoption.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftoption.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/config/ftoption.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftmodule.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftmodule.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftmodule.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/config/ftmodule.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftconfig.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftconfig.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftconfig.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/config/ftconfig.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftstdlib.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftstdlib.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config/ftstdlib.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/config/ftstdlib.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fterrors.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fterrors.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/fterrors.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/fterrors.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/t1tables.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/t1tables.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/t1tables.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/t1tables.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftstroke.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftstroke.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftstroke.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftstroke.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftoutln.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftoutln.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/ftoutln.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/ftoutln.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/tttables.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/tttables.h





C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/tttables.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/freetype/tttables.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/ft2build.h

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/ft2build.h





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/ft2build.h : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/h/ft2build.h | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	
	
	
	
	
	
	


	
	
	
	
	
	
	
BUILD : FONT_FREETYPE2_src_diab__BUILD

.PHONY : FONT_FREETYPE2_src_diab__BUILD

__BUILD_FB_IDS += kernel_top_FONT_FREETYPE2_src_diab

FONT_FREETYPE2_src_diab__BUILD : 
	@ echo building FONT_FREETYPE2 directory src
	+ @ cd C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/src && C:/WindRiverSR500New/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=kernel _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=FONT_FREETYPE2 VSB_DIR=C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_FONT_FREETYPE2_src_diab BSPNAME=ti_sitara_ctxa15_branson_1_0_0_0 BUILDSTAGE=BUILD


	
BUILD_USR_STATIC : FONT_FREETYPE2_src_diab__BUILD_USR_STATIC

.PHONY : FONT_FREETYPE2_src_diab__BUILD_USR_STATIC

__BUILD_USR_STATIC_FB_IDS += user_static_top_FONT_FREETYPE2_src_diab

FONT_FREETYPE2_src_diab__BUILD_USR_STATIC : 
	@ echo building FONT_FREETYPE2 directory src
	+ @ cd C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/src && C:/WindRiverSR500New/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=user LAYER_FORMAT=static _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=FONT_FREETYPE2 VSB_DIR=C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=user_static_top_FONT_FREETYPE2_src_diab BSPNAME=ti_sitara_ctxa15_branson_1_0_0_0 BUILDSTAGE=BUILD_USR_STATIC

	
	
BUILD_USR_SHARED : FONT_FREETYPE2_src_diab__BUILD_USR_SHARED

.PHONY : FONT_FREETYPE2_src_diab__BUILD_USR_SHARED

__BUILD_USR_SHARED_FB_IDS += user_shared_top_FONT_FREETYPE2_src_diab

FONT_FREETYPE2_src_diab__BUILD_USR_SHARED : 
	@ echo building FONT_FREETYPE2 directory src
	+ @ cd C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/src && C:/WindRiverSR500New/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=user LAYER_FORMAT=shared _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=FONT_FREETYPE2 VSB_DIR=C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=user_shared_top_FONT_FREETYPE2_src_diab BSPNAME=ti_sitara_ctxa15_branson_1_0_0_0 BUILDSTAGE=BUILD_USR_SHARED


	
	
	

	

	


	
# copying directory cdf to C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf




PRENOBUILD : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/30gfxFreeType2.cdf

__FILES_TO_COPY_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/30gfxFreeType2.cdf





 

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/30gfxFreeType2.cdf : C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/cdf/30gfxFreeType2.cdf | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	
cdf_PRENOBUILD_FONT_FREETYPE2_FILES = cdf/30gfxFreeType2.cdf

cdf_PRENOBUILD_FONT_FREETYPE2_DIR = C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3

PRENOBUILD_FILES += $(addprefix $(cdf_PRENOBUILD_FONT_FREETYPE2_DIR)/,$(cdf_PRENOBUILD_FONT_FREETYPE2_FILES))

PRENOBUILD : PRENOBUILD_FONT_FREETYPE2

PRENOBUILD_FONT_FREETYPE2 : cdf_PRENOBUILD_FONT_FREETYPE2

cdf_PRENOBUILD_FONT_FREETYPE2 : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_FONT_FREETYPE2.cdf

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_FONT_FREETYPE2.cdf : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_FONT_FREETYPE2.tmp
	$(CDFCOMP) -i $^ -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer FONT_FREETYPE2

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_FONT_FREETYPE2.tmp : | C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf
	$(file >$@,$(call __vsb_tmpl_cdf_inter,$(addprefix $(cdf_PRENOBUILD_FONT_FREETYPE2_DIR)/,$(sort $(cdf_PRENOBUILD_FONT_FREETYPE2_FILES))),FONT_FREETYPE2))



	

	

	
__DIR_TARGETS += $(__DIR_TARGETS_FONT_FREETYPE2)

__DIR_TARGETS_FONT_FREETYPE2 += C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/configlette C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/config C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/h/public/freetype/internal/services C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/share/h C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/config C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/usr/h/public/freetype/internal/services C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/vsblCdf

