
ifndef __HEADER_ACCESS_USB_MOUSE_INCLUDED
__HEADER_ACCESS_USB_MOUSE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_USB_MOUSE = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_MOUSE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), USB_MOUSE))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_MOUSE
endif
endif

endif

endif

