
ifndef __HEADER_ACCESS_AUDIO_INCLUDED
__HEADER_ACCESS_AUDIO_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_AUDIO = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/AUDIO),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), AUDIO))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/AUDIO
endif
endif

endif

endif

