
ifndef __HEADER_ACCESS_EVDEV_LIB_INCLUDED
__HEADER_ACCESS_EVDEV_LIB_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_EVDEV_LIB = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/EVDEV_LIB),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), EVDEV_LIB))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/EVDEV_LIB
endif
endif

endif

endif

