
ifndef __HEADER_ACCESS_FBDEV_COMMON_INCLUDED
__HEADER_ACCESS_FBDEV_COMMON_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_FBDEV_COMMON = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FBDEV_COMMON),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), FBDEV_COMMON))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FBDEV_COMMON
endif
endif

endif

endif

