
ifndef __HEADER_ACCESS_WEBCLI_CLI_INCLUDED
__HEADER_ACCESS_WEBCLI_CLI_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_WEBCLI_CLI = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/WEBCLI_CLI),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), WEBCLI_CLI))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/WEBCLI_CLI
endif
endif

endif

endif

