
ifndef __HEADER_ACCESS_USB_CORE_INCLUDED
__HEADER_ACCESS_USB_CORE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_USB_CORE = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_CORE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), USB_CORE))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_CORE
endif
endif

endif

endif

