
ifndef __HEADER_ACCESS_SNMP_ENGINE_INCLUDED
__HEADER_ACCESS_SNMP_ENGINE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_SNMP_ENGINE = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SNMP_ENGINE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), SNMP_ENGINE))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SNMP_ENGINE
endif
endif

endif

endif

