
ifndef __HEADER_ACCESS_USB_STORAGE_INCLUDED
__HEADER_ACCESS_USB_STORAGE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_USB_STORAGE = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_STORAGE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), USB_STORAGE))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_STORAGE
endif
endif

endif

endif

