
ifndef __HEADER_ACCESS_TILCON_DEMO_INCLUDED
__HEADER_ACCESS_TILCON_DEMO_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_TILCON_DEMO = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/TILCON_DEMO),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), TILCON_DEMO))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/TILCON_DEMO
endif
endif

endif

endif

