
ifndef __HEADER_ACCESS_WEBCLI_MIBWAY_INCLUDED
__HEADER_ACCESS_WEBCLI_MIBWAY_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_WEBCLI_MIBWAY = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/WEBCLI_MIBWAY),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), WEBCLI_MIBWAY))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/WEBCLI_MIBWAY
endif
endif

endif

endif

