
ifndef __HEADER_ACCESS_WEBCLI_BACKPLANE_INCLUDED
__HEADER_ACCESS_WEBCLI_BACKPLANE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_WEBCLI_BACKPLANE = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/WEBCLI_BACKPLANE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), WEBCLI_BACKPLANE))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/WEBCLI_BACKPLANE
endif
endif

endif

endif

