
ifndef __HEADER_ACCESS_USB_CLASS_INCLUDED
__HEADER_ACCESS_USB_CLASS_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_USB_CLASS = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_CLASS),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), USB_CLASS))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_CLASS
endif
endif

endif

endif

