
ifndef __HEADER_ACCESS_TILCON_INCLUDED
__HEADER_ACCESS_TILCON_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_TILCON = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/TILCON),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), TILCON))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/TILCON
endif
endif

endif

endif

