
ifndef __HEADER_ACCESS_AUDIO_DRV_INCLUDED
__HEADER_ACCESS_AUDIO_DRV_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_AUDIO_DRV = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/AUDIO_DRV),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), AUDIO_DRV))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/AUDIO_DRV
endif
endif

endif

endif

