
ifndef __HEADER_ACCESS_USB_KEYBOARD_INCLUDED
__HEADER_ACCESS_USB_KEYBOARD_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_USB_KEYBOARD = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_KEYBOARD),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), USB_KEYBOARD))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/USB_KEYBOARD
endif
endif

endif

endif

