
ifndef __HEADER_ACCESS_SNMP_WRSNMP_INCLUDED
__HEADER_ACCESS_SNMP_WRSNMP_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_SNMP_WRSNMP = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SNMP_WRSNMP),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), SNMP_WRSNMP))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SNMP_WRSNMP
endif
endif

endif

endif

