
ifndef __HEADER_ACCESS_EVDEV_DRV_INCLUDED
__HEADER_ACCESS_EVDEV_DRV_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_EVDEV_DRV = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/EVDEV_DRV),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), EVDEV_DRV))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/EVDEV_DRV
endif
endif

endif

endif

