
ifndef __HEADER_ACCESS_BRANSON_LAYER_BRANSONWEBSERVICES_INCLUDED
__HEADER_ACCESS_BRANSON_LAYER_BRANSONWEBSERVICES_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BRANSON_LAYER_BRANSONWEBSERVICES = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/BRANSON_LAYER_BRANSONWEBSERVICES),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BRANSON_LAYER_BRANSONWEBSERVICES))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/BRANSON_LAYER_BRANSONWEBSERVICES
endif
endif

endif

endif

