
ifndef __HEADER_ACCESS_BRANSON_LAYER_INCLUDED
__HEADER_ACCESS_BRANSON_LAYER_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BRANSON_LAYER = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/BRANSON_LAYER),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BRANSON_LAYER))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/BRANSON_LAYER
endif
endif

endif

endif

