
ifndef __HEADER_ACCESS_AUDIO_DEMO_INCLUDED
__HEADER_ACCESS_AUDIO_DEMO_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_AUDIO_DEMO = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/AUDIO_DEMO),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), AUDIO_DEMO))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/AUDIO_DEMO
endif
endif

endif

endif

