
ifndef __HEADER_ACCESS_KHRONOS_INCLUDED
__HEADER_ACCESS_KHRONOS_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_KHRONOS = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/KHRONOS),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), KHRONOS))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/KHRONOS
endif
endif

endif

endif

