
ifndef __HEADER_ACCESS_WEBCLI_INCLUDED
__HEADER_ACCESS_WEBCLI_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_WEBCLI = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/WEBCLI),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), WEBCLI))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/WEBCLI
endif
endif

endif

endif

