
ifndef __HEADER_ACCESS_USB_HID_INCLUDED
__HEADER_ACCESS_USB_HID_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_USB_HID = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/USB_HID),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), USB_HID))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/USB_HID
endif
endif

endif

endif

