
ifndef __HEADER_ACCESS_SEC_CRYPTO_INCLUDED
__HEADER_ACCESS_SEC_CRYPTO_INCLUDED = TRUE


__FRIEND_ACCESS_DISK_ENCRYPTION += SEC_CRYPTO



__FRIEND_ACCESS_SEC_CRYPTO += SEC_CRYPTO


__SUBSCRIBE_ACCESS_SEC_CRYPTO = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/SEC_CRYPTO),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME),DISK_ENCRYPTION SEC_CRYPTO))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/SEC_CRYPTO
endif
endif

endif

endif

