
ifndef __HEADER_ACCESS_SNMP_AGENT_INCLUDED
__HEADER_ACCESS_SNMP_AGENT_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_SNMP_AGENT = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/SNMP_AGENT),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), SNMP_AGENT))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/SNMP_AGENT
endif
endif

endif

endif

