
ifndef __HEADER_ACCESS_FONT_FREETYPE2_INCLUDED
__HEADER_ACCESS_FONT_FREETYPE2_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_FONT_FREETYPE2 = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/FONT_FREETYPE2),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), FONT_FREETYPE2))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/FONT_FREETYPE2
endif
endif

endif

endif

