
ifndef __HEADER_ACCESS_BRANSON_LAYER_TIDSSFB_INCLUDED
__HEADER_ACCESS_BRANSON_LAYER_TIDSSFB_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BRANSON_LAYER_TIDSSFB = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/BRANSON_LAYER_TIDSSFB),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BRANSON_LAYER_TIDSSFB))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/BRANSON_LAYER_TIDSSFB
endif
endif

endif

endif

