
ifndef __HEADER_ACCESS_USB_HCORE_INCLUDED
__HEADER_ACCESS_USB_HCORE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_USB_HCORE = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/USB_HCORE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), USB_HCORE))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/USB_HCORE
endif
endif

endif

endif

