
ifndef __HEADER_ACCESS_USB_CTLR_INCLUDED
__HEADER_ACCESS_USB_CTLR_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_USB_CTLR = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/USB_CTLR),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), USB_CTLR))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/USB_CTLR
endif
endif

endif

endif

