
ifndef __HEADER_ACCESS_TILCON_KERNEL_INCLUDED
__HEADER_ACCESS_TILCON_KERNEL_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_TILCON_KERNEL = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/TILCON_KERNEL),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), TILCON_KERNEL))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/TILCON_KERNEL
endif
endif

endif

endif

