
ifndef __HEADER_ACCESS_WEBCLI_COMMON_INCLUDED
__HEADER_ACCESS_WEBCLI_COMMON_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_WEBCLI_COMMON = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/WEBCLI_COMMON),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), WEBCLI_COMMON))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/WEBCLI_COMMON
endif
endif

endif

endif

