
ifndef __HEADER_ACCESS_ARM_KERNEL_INCLUDED
__HEADER_ACCESS_ARM_KERNEL_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_ARM_KERNEL = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/ARM_KERNEL),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), ARM_KERNEL))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/ARM_KERNEL
endif
endif

endif

endif

