
ifndef __HEADER_ACCESS_WEBCLI_CURL_INCLUDED
__HEADER_ACCESS_WEBCLI_CURL_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_WEBCLI_CURL = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/WEBCLI_CURL),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), WEBCLI_CURL))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/WEBCLI_CURL
endif
endif

endif

endif

