
ifndef __HEADER_ACCESS_USB_HELPER_INCLUDED
__HEADER_ACCESS_USB_HELPER_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_USB_HELPER = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/USB_HELPER),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), USB_HELPER))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/USB_HELPER
endif
endif

endif

endif

