
#
# This file is automatically generated by mk/krnl/defs.fastlibgen.mk .
#
# build configuration :
#	VSB : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB
#	CPU : ARMARCH7
#	TOOL : diab
#	FP : vector
# 	ENDIAN : little
#	LIB_DIR_TAG = 
#	LIBDIRBASE = krnl/ARMARCH7/common
#	LIBDIRBASE = krnl/$(CPU)$(CPU_OPTION_SUFFIX)/$(TOOL_COMMON_DIR)$(LIB_DIR_TAG)$(MINOR_OPTION_SUFFIX)



include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_aes.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_asn1.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_bf.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_bio.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_bn.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_buffer.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_cast.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_cmac.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_cms.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_comp.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_conf.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_des.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_dh.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_dsa.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_dso.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_ec.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_ecdh.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_ecdsa.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_engine.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_err.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_evp.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_hmac.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_krb5.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_lhash.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_modes.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_objects.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_ocsp.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_pem.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_pkcs12.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_pkcs7.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_pqueue.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_rand.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_rc2.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_rc4.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_rsa.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_seed.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_srp.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_stack.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_ts.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_txt_db.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_ui.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_x509.mk 
include kernel_top_OPENSSL_openssl-1_0_2_crypto_diab_x509v3.mk



LIBOBJS = $(LIBOBJS_OPENSSL)

# DEP_OBJS = (DEP_OBJS)

 
LIBOBJS_krnl_ARMARCH7_common_OPENSSL_kernel_top_OPENSSL_openssl-1_0_2_crypto_diab =  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/cpt_err.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/constant_time_test.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/cryptlib.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/cversion.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/ebcdic.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/ex_data.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/fips_ers.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/mem.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/mem_clr.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/mem_dbg.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/o_time.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/o_dir.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/o_fips.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/o_init.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/o_str.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/o_time.o  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL/uid.o 

arcmdfile_krnl_ARMARCH7_common_OPENSSL : $(LIBOBJS_krnl_ARMARCH7_common_OPENSSL_kernel_top_OPENSSL_openssl-1_0_2_crypto_diab)

LIBOBJS_krnl_ARMARCH7_common_OPENSSL_OPENSSL += $(LIBOBJS_krnl_ARMARCH7_common_OPENSSL_kernel_top_OPENSSL_openssl-1_0_2_crypto_diab)

LIBOBJS_krnl_ARMARCH7_common_OPENSSL += $(LIBOBJS_krnl_ARMARCH7_common_OPENSSL_kernel_top_OPENSSL_openssl-1_0_2_crypto_diab)

__OBJS_TO_CLEAN_OPENSSL += $(LIBOBJS_krnl_ARMARCH7_common_OPENSSL_kernel_top_OPENSSL_openssl-1_0_2_crypto_diab) $(LIBOBJS_krnl_ARMARCH7_common_OPENSSL_kernel_top_OPENSSL_openssl-1_0_2_crypto_diab:.o=.d)

ifndef _DONEBASE_LIB_krnl_ARMARCH7_common_OPENSSL

_DONEBASE_LIB_krnl_ARMARCH7_common_OPENSSL = TRUE

# LIBBASES += OPENSSL

__LIBS_TO_BUILD += krnl_ARMARCH7_common_OPENSSL

__LIBS_TO_BUILD_OPENSSL += krnl_ARMARCH7_common_OPENSSL

__BUILT_LIBS += krnl_ARMARCH7_common_OPENSSL

__LIB_krnl_ARMARCH7_common_OPENSSL = C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL$(OPT).a


C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/objOPENSSL :
	$(MKDIR) $@


lib : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL$(OPT).a  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL.cdf

# need to pass the lib.a file twice to C:/WindRiverSR500New/compilers/diab-5.9.6.1/WIN32/bin/ddump -Ng to workaround ddump problem
C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL.nm : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL$(OPT).a
	$(if $(wildcard $<),cd C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common && $(NM) libOPENSSL$(OPT).a libOPENSSL$(OPT).a > $@, $(info skipping $@ : non existant $<))

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL.cdf : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL.nm 
	$(if $(wildcard $<),$(LIB2CDF) -i $< -a libOPENSSL.a -o $@, $(info skipping $@ : non existant $<))

arcmdfiles : arcmdfile_krnl_ARMARCH7_common_OPENSSL

arcmdfile_krnl_ARMARCH7_common_OPENSSL :
	$(file >$@,$(LIBOBJS_krnl_ARMARCH7_common_OPENSSL))
	@echo created $@

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL$(OPT).a : arcmdfile_krnl_ARMARCH7_common_OPENSSL
	C:/WindRiverSR500New/compilers/diab-5.9.6.1/WIN32/bin/dar crusv $@ @arcmdfile_krnl_ARMARCH7_common_OPENSSL


clean _layer_clean_OPENSSL : _clean_LIB_BASE_krnl_ARMARCH7_common_OPENSSL

_clean_LIB_BASE_krnl_ARMARCH7_common_OPENSSL :
	rm -f C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL$(OPT).a


endif

ifndef _DONEBASE_LIB_OPENSSL_krnl_ARMARCH7_common_OPENSSL

_DONEBASE_LIB_OPENSSL_krnl_ARMARCH7_common_OPENSSL = TRUE

lib : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/layerOPENSSL_libOPENSSL.cdf

C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/layerOPENSSL_libOPENSSL.cdf :  C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL$(OPT).a
	$(file >$@, $(call __tmpl_layercdf,OPENSSL,libOPENSSL.a,$(LIBOBJS_krnl_ARMARCH7_common_OPENSSL)))

endif


C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/ARMARCH7/common/libOPENSSL$(OPT).a : $(LIBOBJS_krnl_ARMARCH7_common_OPENSSL)




 

################
# rules defined locally in Makefile
##



################

objs : $(LIBOBJS)
 
# this is the end of the file 
