
#
# This file is automatically generated by mk/usr/defs.fastlibgen.mk.
#
# build configuration :
#	VSB : C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB
#	CPU : ARMARCH7
#	TOOL : diab
#	FP : vector
# 	ENDIAN : little
#	LIB_DIR_TAG = 
#	LIBDIRBASE = common
#	LIBDIRBASE = $(TOOL_COMMON_DIR)$(LIB_DIR_TAG)



-include user_static_top_CORE_USER_src_diab_wind.mk 
-include user_static_top_CORE_USER_src_diab_posix.mk 
-include user_static_top_CORE_USER_src_diab_mm.mk 
-include user_static_top_CORE_USER_src_diab_sys.mk 
-include user_static_top_CORE_USER_src_diab_util.mk 
-include user_static_top_CORE_USER_src_diab_random.mk



ifeq (,)



endif


# DEP_OBJS = (DEP_OBJS)

# LIB_BASE_NAMES = 







################
# rules defined locally in Makefile
##





################

objs : $(LIBOBJS)
 
# this is the end of the file 
