

/* this file is automatically generated */


Layer Layer::USB_HELPER {
}




/*********************************
 Component INCLUDE_USB_HOST_CLASS_INIT 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 49 57  
**********************************/
Component	INCLUDE_USB_HOST_CLASS_INIT {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 49 57 }
}


/*********************************
 Component INCLUDE_USB_GEN2_HELPER 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 59 66  
**********************************/
Component	INCLUDE_USB_GEN2_HELPER {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 59 66 }
}


/*********************************
 Component INCLUDE_USB_TRACK_HUB 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 109 115  
**********************************/
Component	INCLUDE_USB_TRACK_HUB {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 109 115 }
}


/*********************************
 Component INCLUDE_USB_TRACK_GEN2_HLP 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 123 129  
**********************************/
Component	INCLUDE_USB_TRACK_GEN2_HLP {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 123 129 }
}


/*********************************
 Folder FOLDER_USB_HOST_DEVICES 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 29 35  
**********************************/
Folder	FOLDER_USB_HOST_DEVICES {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 29 35 }
}


/*********************************
 Folder FOLDER_USB_GEN2_DEVICES 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 37 41  
**********************************/
Folder	FOLDER_USB_GEN2_DEVICES {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 37 41 }
}


/*********************************
 Folder FOLDER_USB_GEN2_DEVICES_INIT 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 43 47  
**********************************/
Folder	FOLDER_USB_GEN2_DEVICES_INIT {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 43 47 }
}


/*********************************
 Folder FOLDER_USB_TRACK_CLASS_DRIVERS 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 87 93  
**********************************/
Folder	FOLDER_USB_TRACK_CLASS_DRIVERS {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 87 93 }
}


/*********************************
 Folder FOLDER_USB_TRACK_HUB 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 95 100  
**********************************/
Folder	FOLDER_USB_TRACK_HUB {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 95 100 }
}


/*********************************
 Folder FOLDER_USB_TRACK_GEN2 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 102 107  
**********************************/
Folder	FOLDER_USB_TRACK_GEN2 {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 102 107 }
}


/*********************************
 Layer Layer::USB_HELPER 
 original object sources located at 
  "C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_USB_HELPER.tmp" 13 15  
**********************************/
Layer	Layer::USB_HELPER {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_USB_HELPER.tmp" 13 15 }
}


/*********************************
 Parameter USB_GEN2_HELPER_LATENCY 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 68 72  
**********************************/
Parameter	USB_GEN2_HELPER_LATENCY {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 68 72 }
}


/*********************************
 Parameter USB_GEN2_HELPER_PRIORITY 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 74 78  
**********************************/
Parameter	USB_GEN2_HELPER_PRIORITY {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 74 78 }
}


/*********************************
 Parameter USB_GEN2_HELPER_DELETABLE_QUEUE_SIZE 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 79 83  
**********************************/
Parameter	USB_GEN2_HELPER_DELETABLE_QUEUE_SIZE {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 79 83 }
}


/*********************************
 Parameter USB_TRACK_HUB 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 117 121  
**********************************/
Parameter	USB_TRACK_HUB {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 117 121 }
}


/*********************************
 Parameter USB_TRACK_GEN2_HLP 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 131 135  
**********************************/
Parameter	USB_TRACK_GEN2_HLP {
		LAYER += Layer::USB_HELPER
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/helper-1.0.0.6/cdf/40usb_host_class.cdf" 131 135 }
}
