

/* this file is automatically generated */


Layer Layer::BDM_NFTL {
}




/*********************************
 Component INCLUDE_FTL 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 61 78  
**********************************/
Component	INCLUDE_FTL {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 61 78 }
}


/*********************************
 Component INCLUDE_FTL_FORMAT 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 80 95  
**********************************/
Component	INCLUDE_FTL_FORMAT {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 80 95 }
}


/*********************************
 Component INCLUDE_FTL_SHOW 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 97 107  
**********************************/
Component	INCLUDE_FTL_SHOW {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 97 107 }
}


/*********************************
 Component INCLUDE_FTL_DISCARD 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 109 117  
**********************************/
Component	INCLUDE_FTL_DISCARD {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 109 117 }
}


/*********************************
 Component INCLUDE_FTL_CACHE 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 119 130  
**********************************/
Component	INCLUDE_FTL_CACHE {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 119 130 }
}


/*********************************
 Component INCLUDE_FLASH_SIM 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 132 138  
**********************************/
Component	INCLUDE_FLASH_SIM {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 132 138 }
}


/*********************************
 Component INCLUDE_FLASH_SIM_FTL 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 140 144  
**********************************/
Component	INCLUDE_FLASH_SIM_FTL {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 140 144 }
}


/*********************************
 Component INCLUDE_FLASH_SIM_TFFS 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 146 150  
**********************************/
Component	INCLUDE_FLASH_SIM_TFFS {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 146 150 }
}


/*********************************
 Folder FOLDER_FTL 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 152 167  
**********************************/
Folder	FOLDER_FTL {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 152 167 }
}


/*********************************
 Layer Layer::BDM_NFTL 
 original object sources located at 
  "C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_BDM_NFTL.tmp" 13 15  
**********************************/
Layer	Layer::BDM_NFTL {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_BDM_NFTL.tmp" 13 15 }
}


/*********************************
 Parameter FTL_SERVICE_TASK_ENABLE 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 29 35  
**********************************/
Parameter	FTL_SERVICE_TASK_ENABLE {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 29 35 }
}


/*********************************
 Parameter FTL_MEM_BUDGET_CFG_PROFILE 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 37 43  
**********************************/
Parameter	FTL_MEM_BUDGET_CFG_PROFILE {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 37 43 }
}


/*********************************
 Parameter FTL_AUTO_MOUNT 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 45 51  
**********************************/
Parameter	FTL_AUTO_MOUNT {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 45 51 }
}


/*********************************
 Parameter FTL_DATA_CACHE_SIZE 
 original object sources located at 
  "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 53 59  
**********************************/
Parameter	FTL_DATA_CACHE_SIZE {
		LAYER += Layer::BDM_NFTL
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.1/cdf/40ftl.cdf" 53 59 }
}
