

/* this file is automatically generated */


Layer Layer::VIP_PROFILES {
}




/*********************************
 Layer Layer::VIP_PROFILES 
 original object sources located at 
  "C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/profiles_PRENOBUILD_VIP_PROFILES.tmp" 12 14  
**********************************/
Layer	Layer::VIP_PROFILES {
		LAYER += Layer::VIP_PROFILES
		LAYER_SOURCE		{ "C:/ScriptGSX2_4/GSX2_4Stream/AM5728_VSB/krnl/cdf/profiles_PRENOBUILD_VIP_PROFILES.tmp" 12 14 }
}
