

/* this file is automatically generated */


Layer Layer::SDMMC_TIMMCHS {
}




/*********************************
 Component INCLUDE_SDMMC_CFG 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/sdmmc-1.0.1.3/host/timmchs-1.1.0.10/cdf/40vxbTiMmchsCtrl.cdf" 20 29  
**********************************/
Component	INCLUDE_SDMMC_CFG {
		LAYER += Layer::SDMMC_TIMMCHS
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/sdmmc-1.0.1.3/host/timmchs-1.1.0.10/cdf/40vxbTiMmchsCtrl.cdf" 20 29 }
}


/*********************************
 Component DRV_TI_MMCHS_CTRL 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/sdmmc-1.0.1.3/host/timmchs-1.1.0.10/cdf/40vxbTiMmchsCtrl.cdf" 31 61  
**********************************/
Component	DRV_TI_MMCHS_CTRL {
		LAYER += Layer::SDMMC_TIMMCHS
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/sdmmc-1.0.1.3/host/timmchs-1.1.0.10/cdf/40vxbTiMmchsCtrl.cdf" 31 61 }
}


/*********************************
 Layer Layer::SDMMC_TIMMCHS 
 original object sources located at 
  "C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/cdf_PRENOBUILD_SDMMC_TIMMCHS.tmp" 13 15  
**********************************/
Layer	Layer::SDMMC_TIMMCHS {
		LAYER += Layer::SDMMC_TIMMCHS
		LAYER_SOURCE		{ "C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/cdf_PRENOBUILD_SDMMC_TIMMCHS.tmp" 13 15 }
}
