/*
 *  wmb_webclidemo.h
 *
 *  This is a part of a Wind River Management SDK source code library.
 *
 *  Copyright (C) 2014 WindRiver Systems.
 *  All rights reserved.
 *  Version 4.9
 *
 */

/* WARNING:  This file is generated by a Wind River Management Integration
 * Tool.  Any changes made to this file may be overwritten by
 * subsequent uses of the tool. */

#ifndef __WMB_WEBCLIDEMO_HEADER__
#define __WMB_WEBCLIDEMO_HEADER__

#ifdef __cplusplus
extern "C" {
#endif

/* Begin the header's Private Section */
#ifdef __WMB_WEBCLIDEMO_PRIVATE_HEADER__
 
/* Defines */
/* %%BeginUserCode webclidemo_Defs */
/* %%EndUserCode   webclidemo_Defs */

/* %%BeginUserCode webclidemo_Enums */
/* %%EndUserCode   webclidemo_Enums */

/* Structures */
/* %%BeginUserCode webclidemo_Structs */
/* %%EndUserCode   webclidemo_Structs */

/* Prototypes */
/* %%BeginUserCode webclidemo_Protos */
/* %%EndUserCode   webclidemo_Protos */


/* Access Options Structure, Shared Defines */
#define ENUM_ACCESS_EMPTY               (1 << __RLI_ACCESS_LEVEL_SHIFT__)


/* Resource Entries Unique ID defines */
enum {
    WMID_BoolTest,
    WMID_CHECKED,
    WMID_CharTest,
    WMID_DoubleTest,
    WMID_ERROR,
    WMID_FloatTest,
    WMID_IF,
    WMID_LiveCounter,
    WMID_LongTest,
    WMID_REPEAT,
    WMID_SELECTED,
    WMID_ShortTest,
    WMID_atIfIndex,
    WMID_atNetAddress,
    WMID_atPhysAddress,
    WMID_createTable,
    WMID_egpAs,
    WMID_egpInErrors,
    WMID_egpInMsgs,
    WMID_egpNeighAddr,
    WMID_egpNeighAs,
    WMID_egpNeighEventTrigger,
    WMID_egpNeighInErrMsgs,
    WMID_egpNeighInErrs,
    WMID_egpNeighInMsgs,
    WMID_egpNeighIntervalHello,
    WMID_egpNeighIntervalPoll,
    WMID_egpNeighMode,
    WMID_egpNeighOutErrMsgs,
    WMID_egpNeighOutErrs,
    WMID_egpNeighOutMsgs,
    WMID_egpNeighState,
    WMID_egpNeighStateDowns,
    WMID_egpNeighStateUps,
    WMID_egpOutErrors,
    WMID_egpOutMsgs,
    WMID_endRow,
    WMID_endTable,
    WMID_err_noReadNoWrite,
    WMID_err_readButNotWrite,
    WMID_fFlag,
    WMID_fFloat,
    WMID_fileInclude,
    WMID_getInstance,
    WMID_icmpInAddrMaskReps,
    WMID_icmpInAddrMasks,
    WMID_icmpInDestUnreachs,
    WMID_icmpInEchoReps,
    WMID_icmpInEchos,
    WMID_icmpInErrors,
    WMID_icmpInMsgs,
    WMID_icmpInParmProbs,
    WMID_icmpInRedirects,
    WMID_icmpInSrcQuenchs,
    WMID_icmpInTimeExcds,
    WMID_icmpInTimestampReps,
    WMID_icmpInTimestamps,
    WMID_icmpOutAddrMaskReps,
    WMID_icmpOutAddrMasks,
    WMID_icmpOutDestUnreachs,
    WMID_icmpOutEchoReps,
    WMID_icmpOutEchos,
    WMID_icmpOutErrors,
    WMID_icmpOutMsgs,
    WMID_icmpOutParmProbs,
    WMID_icmpOutRedirects,
    WMID_icmpOutSrcQuenchs,
    WMID_icmpOutTimeExcds,
    WMID_icmpOutTimestampReps,
    WMID_icmpOutTimestamps,
    WMID_ifAdminStatus,
    WMID_ifDescr,
    WMID_ifInDiscards,
    WMID_ifInErrors,
    WMID_ifInNUcastPkts,
    WMID_ifInOctets,
    WMID_ifInUcastPkts,
    WMID_ifInUnknownProtos,
    WMID_ifIndex,
    WMID_ifLastChange,
    WMID_ifMtu,
    WMID_ifNumber,
    WMID_ifOperStatus,
    WMID_ifOutDiscards,
    WMID_ifOutErrors,
    WMID_ifOutNUcastPkts,
    WMID_ifOutOctets,
    WMID_ifOutQLen,
    WMID_ifOutUcastPkts,
    WMID_ifPhysAddress,
    WMID_ifSpecific,
    WMID_ifSpeed,
    WMID_ifType,
    WMID_ipAdEntAddr,
    WMID_ipAdEntBcastAddr,
    WMID_ipAdEntIfIndex,
    WMID_ipAdEntNetMask,
    WMID_ipAdEntReasmMaxSize,
    WMID_ipDefaultTTL,
    WMID_ipForwDatagrams,
    WMID_ipForwarding,
    WMID_ipFragCreates,
    WMID_ipFragFails,
    WMID_ipFragOKs,
    WMID_ipInAddrErrors,
    WMID_ipInDelivers,
    WMID_ipInDiscards,
    WMID_ipInHdrErrors,
    WMID_ipInReceives,
    WMID_ipInUnknownProtos,
    WMID_ipNetToMediaIfIndex,
    WMID_ipNetToMediaNetAddress,
    WMID_ipNetToMediaPhysAddress,
    WMID_ipNetToMediaType,
    WMID_ipOutDiscards,
    WMID_ipOutNoRoutes,
    WMID_ipOutRequests,
    WMID_ipReasmFails,
    WMID_ipReasmOKs,
    WMID_ipReasmReqds,
    WMID_ipReasmTimeout,
    WMID_ipRouteAge,
    WMID_ipRouteDest,
    WMID_ipRouteIfIndex,
    WMID_ipRouteInfo,
    WMID_ipRouteMask,
    WMID_ipRouteMetric1,
    WMID_ipRouteMetric2,
    WMID_ipRouteMetric3,
    WMID_ipRouteMetric4,
    WMID_ipRouteMetric5,
    WMID_ipRouteNextHop,
    WMID_ipRouteProto,
    WMID_ipRouteType,
    WMID_ipRoutingDiscards,
    WMID_mark,
    WMID_number,
    WMID_sListIndex,
    WMID_sRadioIndex,
    WMID_smtp_domain,
    WMID_smtp_emailBody,
    WMID_smtp_emailTextInfo,
    WMID_smtp_mailFrom,
    WMID_smtp_mailServer,
    WMID_smtp_mailTo,
    WMID_smtp_sendNow,
    WMID_smtp_subjectHeading,
    WMID_snmpEnableAuthenTraps,
    WMID_snmpInASNParseErrs,
    WMID_snmpInBadCommunityNames,
    WMID_snmpInBadCommunityUses,
    WMID_snmpInBadValues,
    WMID_snmpInBadVersions,
    WMID_snmpInGenErrs,
    WMID_snmpInGetNexts,
    WMID_snmpInGetRequests,
    WMID_snmpInGetResponses,
    WMID_snmpInNoSuchNames,
    WMID_snmpInPkts,
    WMID_snmpInReadOnlys,
    WMID_snmpInSetRequests,
    WMID_snmpInTooBigs,
    WMID_snmpInTotalReqVars,
    WMID_snmpInTotalSetVars,
    WMID_snmpInTraps,
    WMID_snmpOutBadValues,
    WMID_snmpOutGenErrs,
    WMID_snmpOutGetNexts,
    WMID_snmpOutGetRequests,
    WMID_snmpOutGetResponses,
    WMID_snmpOutNoSuchNames,
    WMID_snmpOutPkts,
    WMID_snmpOutSetRequests,
    WMID_snmpOutTooBigs,
    WMID_snmpOutTraps,
    WMID_sysContact,
    WMID_sysDescr,
    WMID_sysLocation,
    WMID_sysName,
    WMID_sysObjectID,
    WMID_sysServices,
    WMID_sysUpTime,
    WMID_szAreaBuffer,
    WMID_szString,
    WMID_tcpActiveOpens,
    WMID_tcpAttemptFails,
    WMID_tcpConnLocalAddress,
    WMID_tcpConnLocalPort,
    WMID_tcpConnRemAddress,
    WMID_tcpConnRemPort,
    WMID_tcpConnState,
    WMID_tcpCurrEstab,
    WMID_tcpEstabResets,
    WMID_tcpInErrs,
    WMID_tcpInSegs,
    WMID_tcpMaxConn,
    WMID_tcpOutRsts,
    WMID_tcpOutSegs,
    WMID_tcpPassiveOpens,
    WMID_tcpRetransSegs,
    WMID_tcpRtoAlgorithm,
    WMID_tcpRtoMax,
    WMID_tcpRtoMin,
    WMID_udpInDatagrams,
    WMID_udpInErrors,
    WMID_udpLocalAddress,
    WMID_udpLocalPort,
    WMID_udpNoPorts,
    WMID_udpOutDatagrams,
    WMID_xsysContact,
    WMID_xsysDescr,
    WMID_xsysName,
    WMID_nonce,
    WMID_myCheckbox,
    WMID_first_i,
    WMID_a,
    WMID_b,
    WMID_c,
    WMID_d,
    WMID_first_s,
    WMID_first_pi,
    WMID_first_p,
    WMID_myIpAddress,
    WMID_nameCase,
    WMID_nameLetter,
    WMID_nameToAdd,
    WMID_nameToDelete,
    WMID_nameToModify,
    WMID_changeNameTo,
    WMID_first_name,
    WMID_key_s,
    WMID_last_name,
    WMID_offset_i,
    WMID_value_i,
    WMID_value_p,
    WMID_offset_p,
    WMID_pointer_p,
    WMID_offset_pi,
    WMID_pointer_pi,
    WMID_value_pi,
    WMID__COMPONENTNAME_,
    WMID__COMPONENTDATE_,
    WMID_RESOURCEMAX_WEBCLIDEMO
};

/* Table Entries Unique ID defines */
enum {
    WGID_atTable,                            /* 0     */
    WGID_egpNeighTable,                      /* 1     */
    WGID_ifTable,                            /* 2     */
    WGID_ipAddrTable,                        /* 3     */
    WGID_ipNetToMediaTable,                  /* 4     */
    WGID_ipRouteTable,                       /* 5     */
    WGID_tcpConnTable,                       /* 6     */
    WGID_udpTable,                           /* 7     */
    WGID_stringTbl,                          /* 8     */
    WGID_numberTblInt,                       /* 9     */
    WGID_numberTblPtr,                       /* 10    */
    WGID_numberTblPtrInt,                    /* 11    */
    WGID_TABLEMAX_WEBCLIDEMO                 /* 12    */
};

#endif /* __WMB_WEBCLIDEMO_PRIVATE_HEADER__ */
 
#define k_webclidemo_Timeout    100

STATUS WMB_WEBCLI_COMPONENT_Start(void);
STATUS WMB_WEBCLI_COMPONENT_Stop(void* deregCookie);



#ifdef __cplusplus
}
#endif

#endif /* __WMB_WEBCLIDEMO_HEADER__*/

