/*****************************************************************
 *
 *  This file automatically generated - DO NOT EDIT!
 *
 *****************************************************************/

#ifndef EPILOGUE_INSTALL_H
#define EPILOGUE_INSTALL_H
#include _VSB_CONFIG_FILE

#define INSTALL_ON_LITTLE_ENDIAN 0
#define INSTALL_ON_BIG_ENDIAN 0
#define INSTALL_OEM_LAYOUT_GLUE_MACROS 0
#define INSTALL_TYPECHECKING_LAYOUT_GLUE_MACROS 0
#define INSTALL_UNALIGNED_BIGENDIAN_LAYOUT_GLUE_MACROS 0
#define INSTALL_COMMON 1
#define INSTALL_COMMON_FIXED64 1
#define INSTALL_COMMON_PRNG 0
#define INSTALL_COMMON_MD4 0
#define INSTALL_COMMON_MD5 1
#define INSTALL_COMMON_SHA 1
#define INSTALL_COMMON_HMAC 1
#define INSTALL_COMMON_DES 1
#define INSTALL_COMMON_3DES 0
#define INSTALL_COMMON_ESP_3DES 0
#define INSTALL_COMMON_DES_TEST 0
#define INSTALL_COMMON_DES_FAKE 0
#define INSTALL_COMMON_STRTOL 0
#define INSTALL_COMMON_STRTOUL 0
#define INSTALL_COMMON_STRICMP 0
#define INSTALL_COMMON_STRNICMP 0
#define INSTALL_COMMON_MEMCMP 0
#define INSTALL_COMMON_SNPRINTF 0
#define INSTALL_COMMON_DYNAMIC_COMP_CONFIG 1
#define INSTALL_ENVOY 1
#define INSTALL_ENVOY_SNMP_GROUP_V1 1
#define INSTALL_ENVOY_SNMP_GROUP_V2 1
#define INSTALL_ENVOY_SNMP_VERSION_1 1
#define INSTALL_ENVOY_SNMP_VERSION_2 1
#if (_WRS_CONFIG_FEATURE_SNMP_V3 == 1)
#define INSTALL_ENVOY_SNMP_VERSION_3 1
#else
#define INSTALL_ENVOY_SNMP_VERSION_3 0
#endif
#define INSTALL_ENVOY_USE_MIBCOMPILER 1
#define INSTALL_ENVOY_MAIN_AGENT 1
#define INSTALL_ENVOY_SNMP_UTIL_MACROS 0
#define INSTALL_ENVOY_MD5 1
#define INSTALL_ENVOY_SHA 1
#define INSTALL_ENVOY_DES 1
#define INSTALL_ENVOY_AESCFB128 1
#define INSTALL_ENVOY_SNMP_RFC1445_VIEWS 0
#define INSTALL_ENVOY_SNMP_RFC2275_VIEWS 1
#define INSTALL_ENVOY_TWO_CHAR_MACROS 0
#if (_WRS_CONFIG_FEATURE_SNMP_V3 == 1)
#define INSTALL_ENVOY_SNMP_V3_TARGET 1
#define INSTALL_ENVOY_SNMP_V3_NOTIFY 1
#define INSTALL_ENVOY_SNMP_V3_PROXY 1
#define INSTALL_ENVOY_SNMP_COEXISTENCE 1
#else
#define INSTALL_ENVOY_SNMP_V3_TARGET 0
#define INSTALL_ENVOY_SNMP_V3_NOTIFY 0
#define INSTALL_ENVOY_SNMP_V3_PROXY 0
#define INSTALL_ENVOY_SNMP_COEXISTENCE 0
#endif
#define INSTALL_SNMP_V3_DIFFIE_HELLMAN 0
#define INSTALL_ENVOY_SNMP_PROXY 0
#define INSTALL_ENVOY_AGENTX 1
#define INSTALL_ENVOY_AGENTX_MASTER 1
#define INSTALL_ENVOY_AGENTX_SUB 1
#define INSTALL_ENVOY_AGENTX_INDEX 1
#define INSTALL_ENVOY_AGENTX_NEXT_CHECK 1
#define INSTALL_ENVOY_AGENTX_2257_RANGE 0
#define INSTALL_ENVOY_ENTITY_MIB 0
#define INSTALL_ENVOY_SNMP_LOCK 1
#define INSTALL_ENVOY_LOCK_INDEPENDENT 0
#define INSTALL_ENVOY_CONTINUE_REENTRANT 1
#define INSTALL_ENVOY_SNMP_SERIALIZE 0
#define INSTALL_SNMP_VXWORKS_VIRTUAL_STACK 0
#define INSTALL_SNMP_VXWORKS_VS_ENTITY 0
#define INSTALL_SNMP_VXWORKS_MESSAGE_CHANNELS 0
#define INSTALL_ENVOY_HEAP_LARGE_VARS 0
#define INSTALL_ENVOY_SNMP_USE_V2_TYPES 0
#define INSTALL_ENVOY_PSOS 0
#define INSTALL_ENVOY_PSOS_CONFIG 0
#if((_WRS_CONFIG_FEATURE_IPNET_INET6==1)||(_WRS_CONFIG_FEATURE_IPNET_INET6_ONLY==1))
#define INSTALL_INETV6 1
#else
#define INSTALL_INETV6 0
#endif
#if(_WRS_CONFIG_FEATURE_IPNET_INET6_ONLY==1)
#define INSTALL_INETV4 0
#else
#define INSTALL_INETV4 1
#endif
#define INSTALL_ENVOY_TEST 0
#define INSTALL_ATTACHE 0
#define INSTALL_ATTACHE_MIB 0
#define INSTALL_ENVOY_VXWORKS_RFC2233 1
#define INSTALL_ENVOY_VXWORKS 1
#define INSTALL_SNARK_LIB 0

#endif /* EPILOGUE_INSTALL_H */
