/************************************************************************** 

      Copyright (c) Branson Ultrasonics Corporation, 1996-2018
 
     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.
 
***************************************************************************/


#ifndef RECIPE_H_
#define RECIPE_H_

#include "Common.h"
#include "CommonProperty.h"
#include "commons.h"
#include  <sdLib.h>
#include  <ioLib.h>
#include  <map>
#include "UIDBInterface.h"

enum RecipePramIDs
{
	// SC Parameters
	RECIPE_PARAM_IDS_START = 0,
	WELD_MODE,
	MODE_VALUE, 
	AMPLITUDESTEPSCNT, 
	AMPLITUDE_STEP_AT, 
	AMPLITUDE_STEP_VALUE1, 
	AMPLITUDE_STEP_VALUE2, 
	AMPLITUDE_STEP_VALUE3, 
	AMPLITUDE_STEP_VALUE4, 
	AMPLITUDE_STEP_VALUE5, 
	AMPLITUDE_STEP_VALUE6, 
	AMPLITUDE_STEP_VALUE7, 
	AMPLITUDE_STEP_VALUE8, 
	AMPLITUDE_STEP_VALUE9, 
	AMPLITUDE_STEP_VALUE10, 
	AMPLITUDE_STEP1, 
	AMPLITUDE_STEP2, 
	AMPLITUDE_STEP3, 
	AMPLITUDE_STEP4, 
	AMPLITUDE_STEP5, 
	AMPLITUDE_STEP6, 
	AMPLITUDE_STEP7, 
	AMPLITUDE_STEP8, 
	AMPLITUDE_STEP9, 
	AMPLITUDE_STEP10, 
	TRIGGER_FORCE, 
	NUM_FORCE_STEPS, 
	FORCE_STEP_AT, 
	FORCE_STEP1, 
	FORCE_STEP2, 
	FORCE_STEP3, 
	FORCE_STEP4, 
	FORCE_STEP5, 
	FORCE_STEP6, 
	FORCE_STEP7, 
	FORCE_STEP8, 
	FORCE_STEP9, 
	FORCE_STEP10, 
	HOLD_TIME, 
	PRETRIGGER, 
	AUTO_PRETRIGGER, 
	DISTANCE_PRETRIGGER, 
	PRETRIGGER_AMPLITUDE, 
	PRETRIGGER_DISTANCE, 
	ENERGY_BRAKE, 
	ENERGY_BRAKE_TIME, 
	ENERGY_BRAKE_AMPLITUDE, 
	AFTER_BRUST, 
	AFTER_BRUST_DELAY, 
	AFTER_BRUST_TIME, 
	AFTER_BRUST_AMPLITUDE, 
	EXTRA_COOLING, 
	MAX_WELD_TIMEOUT,
	POST_WELD_SEEK, 
	PRE_WELD_SEEK, 
	TIMED_SEEK, 
	TIMED_SEEK_PERIOD, 
	GLOBALSUSPECT, 
	GLOBALREJECT, 
	SUSPECT_TIME_ENABLED,  
	SUSPECT_TIME_LOW_VALUE, 
	SUSPECT_TIME_HIGH_VALUE, 
	REJECT_TIME_ENABLED,  
	REJECT_TIME_LOW_VALUE, 
	REJECT_TIME_HIGH_VALUE, 
	SUSPECT_ENERGY_ENABLED,
	SUSPECT_ENERGY_LOW_VALUE, 
	SUSPECT_ENERGY_HIGH_VALUE, 
	REJECT_ENERGY_ENABLED,  
	REJECT_ENERGY_LOW_VALUE, 
	REJECT_ENERGY_HIGH_VALUE, 
	SUSPECT_PEAKPOWER_ENABLED, 
	SUSPECT_PEAKPOWER_LOW_VALUE, 
	SUSPECT_PEAKPOWER_HIGH_VALUE, 
	REJECT_PEAKPOWER_ENABLED,  
	REJECT_PEAKPOWER_LOW_VALUE, 
	REJECT_PEAKPOWER_HIGH_VALUE, 
	SUSPECT_ABSOLUTEDISTANCE_ENABLED, 
	SUSPECT_ABSOLUTEDISTANCE_LOW_VALUE, 
	SUSPECT_ABSOLUTEDISTANCE_HIGH_VALUE, 
	REJECT_ABSOLUTEDISTANCE_ENABLED,  
	REJECT_ABSOLUTEDISTANCE_LOW_VALUE, 
	REJECT_ABSOLUTEDISTANCE_HIGH_VALUE, 
	SUSPECT_COLLAPSEDISTANCE_ENABLED, 
	SUSPECT_COLLAPSEDISTANCE_LOW_VALUE, 
	SUSPECT_COLLAPSEDISTANCE_HIGH_VALUE, 
	REJECT_COLLAPSEDISTANCE_ENABLED,  
	REJECT_COLLAPSEDISTANCE_LOW_VALUE, 
	REJECT_COLLAPSEDISTANCE_HIGH_VALUE, 
	SUSPECT_TRIGGERDISTANCE_ENABLED,  
	SUSPECT_TRIGGERDISTANCE_LOW_VALUE, 
	SUSPECT_TRIGGERDISTANCE_HIGH_VALUE, 
	REJECT_TRIGGERDISTANCE_ENABLED,  
	REJECT_TRIGGERDISTANCE_LOW_VALUE, 
	REJECT_TRIGGERDISTANCE_HIGH_VALUE, 
	SUSPECT_ENDWELDFORCE_ENABLED,  
	SUSPECT_ENDWELDFORCE_LOW_VALUE, 
	SUSPECT_ENDWELDFORCE_HIGH_VALUE, 
	REJECT_ENDWELDFORCE_ENABLED,  
	REJECT_ENDWELDFORCE_LOW_VALUE, 
	REJECT_ENDWELDFORCE_HIGH_VALUE, 
	SUSPECT_FREQUENCY_ENABLED,  
	SUSPECT_FREQUENCY_LOW_VALUE, 
	SUSPECT_FREQUENCY_HIGH_VALUE, 
	REJECT_FREQUENCY_ENABLED,  
	REJECT_FREQUENCY_LOW_VALUE, 
	REJECT_FREQUENCY_HIGH_VALUE, 
	GLOBALCONTROL, 
	PEAKPOWERCUTOFF, 
	PEAKPOWERCUTOFFENABLE, 
	FREQUENCYLOWCUTOFF, 
	FREQUENCYLOWCUTOFFENABLE, 
	ABSOLUTECUTOFF, 
	ABSOLUTECUTOFFENABLE, 
	FREQUENCYHIGHCUTOFF, 
	FREQUENCYHIGHCUTOFFENABLE, 
	COLLAPSECUTOFF, 
	COLLAPSECUTOFFENABLE, 
	ENERGYCUTOFF, 
	ENERGYCUTOFFENABLE,
	TIMECUTOFF, 
	TIMECUTOFFENABLE, 
	GROUNDDETECTENABLE,
	// AC Parameters
	FORCE_STEP_VALUE1, 
	FORCE_STEP_VALUE2,
	FORCE_STEP_VALUE3, 
	FORCE_STEP_VALUE4, 
	FORCE_STEP_VALUE5, 
	FORCE_STEP_VALUE6, 
	FORCE_STEP_VALUE7, 
	FORCE_STEP_VALUE8, 
	FORCE_STEP_VALUE9, 
	FORCE_STEP_VALUE10, 
	FORCE_STEP_RAMP_VALUE1, 
	FORCE_STEP_RAMP_VALUE2, 
	FORCE_STEP_RAMP_VALUE3, 
	FORCE_STEP_RAMP_VALUE4, 
	FORCE_STEP_RAMP_VALUE5, 
	FORCE_STEP_RAMP_VALUE6, 
	FORCE_STEP_RAMP_VALUE7, 
	FORCE_STEP_RAMP_VALUE8, 
	FORCE_STEP_RAMP_VALUE9, 
	FORCE_STEP_RAMP_VALUE10, 
	FORCE_RAMP_TIME, 
	HOLD_FORCE, 
	HOLD_FORCE_RAMP_TIME, 
	READY_POSITION, 
	WELD_FORCE_CONTROL, 
	READY_POSITION_TOGGLE, 
	EXPECTED_PART_CONTACT_POSITION, 
	PART_CONTACT_WINDOW_OFFSET, 
	PART_CONTACT_WINDOW_MINUS, 
	PART_CONTACT_WINDOW_PLUS, 
	DOWN_ACCELERATION, 
	DOWN_MAX_VELOCITY, 
	DOWN_DECELERATION, 
	RETURN_ACCELERATION, 
	RETURN_MAX_VELOCITY, 
	RETURN_DECELERATION, 
	// PC Parameters
	WELD_RAMP_TIME,
	//Start of Dynamic mode Parameters
    REACTIVITY,
    FORCE_LEVEL_ENABLED,
	FORCE_LEVEL,
	FORCE_LEVEL_TIME,
	//End of Dynamic mode Parameters
	SCRUB_AMPLITUDE,
	
	RECIPE_PARAM_IDS_FINISH,
	//Local Validation Parameters
	SUSPECT_TIME_LOW_ENABLED, 
	SUSPECT_TIME_HIGH_ENABLED, 
	REJECT_TIME_LOW_ENABLED, 
	REJECT_TIME_HIGH_ENABLED, 
	SUSPECT_ENERGY_LOW_ENABLED, 
	SUSPECT_ENERGY_HIGH_ENABLED, 
	REJECT_ENERGY_LOW_ENABLED, 
	REJECT_ENERGY_HIGH_ENABLED, 
	SUSPECT_PEAKPOWER_LOW_ENABLED, 
	SUSPECT_PEAKPOWER_HIGH_ENABLED, 
	REJECT_PEAKPOWER_LOW_ENABLED, 
	REJECT_PEAKPOWER_HIGH_ENABLED, 
	SUSPECT_ABSOLUTEDISTANCE_LOW_ENABLED, 
	SUSPECT_ABSOLUTEDISTANCE_HIGH_ENABLED, 
	REJECT_ABSOLUTEDISTANCE_LOW_ENABLED, 
	REJECT_ABSOLUTEDISTANCE_HIGH_ENABLED, 
	SUSPECT_COLLAPSEDISTANCE_LOW_ENABLED, 
	SUSPECT_COLLAPSEDISTANCE_HIGH_ENABLED, 
	REJECT_COLLAPSEDISTANCE_LOW_ENABLED, 
	REJECT_COLLAPSEDISTANCE_HIGH_ENABLED, 
	SUSPECT_TRIGGERDISTANCE_LOW_ENABLED, 
	SUSPECT_TRIGGERDISTANCE_HIGH_ENABLED, 
	REJECT_TRIGGERDISTANCE_LOW_ENABLED, 
	REJECT_TRIGGERDISTANCE_HIGH_ENABLED, 
	SUSPECT_ENDWELDFORCE_LOW_ENABLED, 
	SUSPECT_ENDWELDFORCE_HIGH_ENABLED, 
	REJECT_ENDWELDFORCE_LOW_ENABLED, 
	REJECT_ENDWELDFORCE_HIGH_ENABLED, 
	SUSPECT_FREQUENCY_LOW_ENABLED, 
	SUSPECT_FREQUENCY_HIGH_ENABLED, 
	REJECT_FREQUENCY_LOW_ENABLED, 
	REJECT_FREQUENCY_HIGH_ENABLED
};

enum RecipeParamDBIDs
{
	WR_DB_RECIPE_NUMBER = 0,
	WR_DB_WELD_RECIPE_NAME,
	WR_DB_WELD_RECIPE_VERSION_NUMBER,
	WR_DB_WELD_MODE,
	WR_DB_MODE_VALUE,
	WR_DB_HOLD_TIME,
	WR_DB_TRIGGER_FORCE,
	WR_DB_TRIGGER_DISTANCE,
	WR_DB_AMPLITUDE_STEPS_CNT,
	WR_DB_AMPLITUDE_STEP_AT,
	WR_DB_AMPLITUDE_STEP_VALUE1,
	WR_DB_AMPLITUDE_STEP_VALUE2,
	WR_DB_AMPLITUDE_STEP_VALUE3,
	WR_DB_AMPLITUDE_STEP_VALUE4,
	WR_DB_AMPLITUDE_STEP_VALUE5,
	WR_DB_AMPLITUDE_STEP_VALUE6,
	WR_DB_AMPLITUDE_STEP_VALUE7,
	WR_DB_AMPLITUDE_STEP_VALUE8,
	WR_DB_AMPLITUDE_STEP_VALUE9,
	WR_DB_AMPLITUDE_STEP_VALUE10,
	WR_DB_AMPLITUDE_STEP1,
	WR_DB_AMPLITUDE_STEP2,
	WR_DB_AMPLITUDE_STEP3,
	WR_DB_AMPLITUDE_STEP4,
	WR_DB_AMPLITUDE_STEP5,
	WR_DB_AMPLITUDE_STEP6,
	WR_DB_AMPLITUDE_STEP7,
	WR_DB_AMPLITUDE_STEP8,
	WR_DB_AMPLITUDE_STEP9,
	WR_DB_AMPLITUDE_STEP10,
	WR_DB_WELD_FORCE,
	WR_DB_FORCE_RAMP_TIME,
	WR_DB_TOTAL_COLLAPSE_TARGET,
	WR_DB_HOLD_FORCE,
	WR_DB_HOLD_FORCE_RAMP_TIME,
	WR_DB_EXPECTED_PART_CONTACT_POSITION,
	WR_DB_READY_POSITION,
	WR_DB_DOWN_ACCELERATION,
	WR_DB_DOWN_MAX_VELOCITY,
	WR_DB_DOWN_DECELERATION,
	WR_DB_RETURN_ACCELERATION,
	WR_DB_RETURN_MAX_VELOCITY,
	WR_DB_RETURN_DECELERATION,
	WR_DB_NUM_FORCE_STEPS,
	WR_DB_FORCE_STEP_AT,
	WR_DB_FORCE_STEP_VALUE1,
	WR_DB_FORCE_STEP_VALUE2,
	WR_DB_FORCE_STEP_VALUE3,
	WR_DB_FORCE_STEP_VALUE4,
	WR_DB_FORCE_STEP_VALUE5,
	WR_DB_FORCE_STEP_VALUE6,
	WR_DB_FORCE_STEP_VALUE7,
	WR_DB_FORCE_STEP_VALUE8,
	WR_DB_FORCE_STEP_VALUE9,
	WR_DB_FORCE_STEP_VALUE10,
	WR_DB_FORCE_STEP_RAMP_VALUE1,
	WR_DB_FORCE_STEP_RAMP_VALUE2,
	WR_DB_FORCE_STEP_RAMP_VALUE3,
	WR_DB_FORCE_STEP_RAMP_VALUE4,
	WR_DB_FORCE_STEP_RAMP_VALUE5,
	WR_DB_FORCE_STEP_RAMP_VALUE6,
	WR_DB_FORCE_STEP_RAMP_VALUE7,
	WR_DB_FORCE_STEP_RAMP_VALUE8,
	WR_DB_FORCE_STEP_RAMP_VALUE9,
	WR_DB_FORCE_STEP_RAMP_VALUE10,
	WR_DB_FORCE_STEP1,
	WR_DB_FORCE_STEP2,
	WR_DB_FORCE_STEP3,
	WR_DB_FORCE_STEP4,
	WR_DB_FORCE_STEP5,
	WR_DB_FORCE_STEP6,
	WR_DB_FORCE_STEP7,
	WR_DB_FORCE_STEP8,
	WR_DB_FORCE_STEP9,
	WR_DB_FORCE_STEP10,
	WR_DB_WELD_RAMP_TIME,
	WR_DB_AFTER_BRUST,
	WR_DB_AB_DELAY,
	WR_DB_AB_TIME,
	WR_DB_AB_AMPLITUDE,
	WR_DB_PRETRIGGER,
	WR_DB_AUTO_PRETRIGGER,
	WR_DB_DISTANCE_PRETRIGGER,
	WR_DB_PRETRIGGER_AMPLITUDE,
	WR_DB_PRETRIGGER_DISTANCE,
	WR_DB_ENERGY_BRAKE,
	WR_DB_ENERGY_BRAKE_TIME,
	WR_DB_ENERGY_BRAKE_AMPLITUDE,
	WR_DB_COOLING_VALVE,
	WR_DB_MAX_WELD_TIMEOUT,
	WR_DB_TIMED_SEEK,
	WR_DB_PRE_WELD_SEEK,
	WR_DB_POST_WELD_SEEK,
	WR_DB_TIMED_SEEK_PERIOD,
	WR_DB_PART_CONTACT_WINDOW_MINUS,
	WR_DB_PART_CONTACT_WINDOW_PLUS,
	WR_DB_PART_CONTACT_WINDOW_OFFSET,
	WR_DB_GLOBAL_CONTROL,
	WR_DB_PEAKPOWER_CUTOFF,
	WR_DB_PEAKPOWER_CUTOFF_ENABLE,
	WR_DB_FREQUENCY_LOW_CUTOFF,
	WR_DB_FREQUENCY_LOW_CUTOFF_ENABLE,
	WR_DB_ABSOLUTE_CUTOFF,
	WR_DB_ABSOLUTE_CUTOFF_ENABLE,
	WR_DB_FREQUENCY_HIGH_CUTOFF,
	WR_DB_FREQUENCY_HIGH_CUTOFFENABLE,
	WR_DB_COLLAPSE_CUTOFF,
	WR_DB_COLLAPSE_CUTOFF_ENABLE,
	WR_DB_ENERGY_CUTOFF,
	WR_DB_ENERGY_CUTOFF_ENABLE,
	WR_DB_TIME_CUTOFF,
	WR_DB_TIME_CUTOFF_ENABLE,
	WR_DB_GROUND_DETECT_ENABLE,
	WR_DB_IS_ACTIVE,
	WR_DB_IS_LOCKED,
	WR_DB_COMPANY_NAME,
	WR_DB_IS_VALIDATE,
	WR_DB_READY_POSITION_TOGGLE,
	WR_DB_WELD_FORCE_CONTROL,
	//Start of Dynamic mode Parameters
	WR_DB_REACTIVITY,
	WR_DB_FORCE_LEVEL_ENABLED,
	WR_DB_FORCE_LEVEL,
	WR_DB_FORCE_LEVEL_TIME,
	//End of Dynamic mode Parameters
	WR_DB_SCRUB_AMPLITUDE,
	
	END_OF_WR_PARAMETERS,
	
	SR_DB_RECIPE_NUMBER,
	SR_DB_WELD_RECIPE_VERSION_NUMBER,
	SR_DB_GLOBALSUSPECT, 
	SR_DB_GLOBALREJECT, 
	SR_DB_SUSPECT_TIME_ENABLED, 
	SR_DB_SUSPECT_TIME_LOW_ENABLED, 
	SR_DB_SUSPECT_TIME_HIGH_ENABLED, 
	SR_DB_SUSPECT_TIME_LOW_VALUE, 
	SR_DB_SUSPECT_TIME_HIGH_VALUE, 
	SR_DB_REJECT_TIME_ENABLED, 
	SR_DB_REJECT_TIME_LOW_ENABLED, 
	SR_DB_REJECT_TIME_HIGH_ENABLED, 
	SR_DB_REJECT_TIME_LOW_VALUE, 
	SR_DB_REJECT_TIME_HIGH_VALUE, 
	SR_DB_SUSPECT_ENERGY_ENABLED, 
	SR_DB_SUSPECT_ENERGY_LOW_ENABLED,
	SR_DB_SUSPECT_ENERGY_HIGH_ENABLED,
	SR_DB_SUSPECT_ENERGY_LOW_VALUE, 
	SR_DB_SUSPECT_ENERGY_HIGH_VALUE, 
	SR_DB_REJECT_ENERGY_ENABLED, 
	SR_DB_REJECT_ENERGY_LOW_ENABLED, 
	SR_DB_REJECT_ENERGY_HIGH_ENABLED, 
	SR_DB_REJECT_ENERGY_LOW_VALUE, 
	SR_DB_REJECT_ENERGY_HIGH_VALUE, 
	SR_DB_SUSPECT_PEAKPOWER_ENABLED, 
	SR_DB_SUSPECT_PEAKPOWER_LOW_ENABLED, 
	SR_DB_SUSPECT_PEAKPOWER_HIGH_ENABLED, 
	SR_DB_SUSPECT_PEAKPOWER_LOW_VALUE, 
	SR_DB_SUSPECT_PEAKPOWER_HIGH_VALUE, 
	SR_DB_REJECT_PEAKPOWER_ENABLED, 
	SR_DB_REJECT_PEAKPOWER_LOW_ENABLED, 
	SR_DB_REJECT_PEAKPOWER_HIGH_ENABLED, 
	SR_DB_REJECT_PEAKPOWER_LOW_VALUE, 
	SR_DB_REJECT_PEAKPOWER_HIGH_VALUE, 
	SR_DB_SUSPECT_ABSOLUTEDISTANCE_ENABLED, 
	SR_DB_SUSPECT_ABSOLUTEDISTANCE_LOW_ENABLED, 
	SR_DB_SUSPECT_ABSOLUTEDISTANCE_HIGH_ENABLED, 
	SR_DB_SUSPECT_ABSOLUTEDISTANCE_LOW_VALUE, 
	SR_DB_SUSPECT_ABSOLUTEDISTANCE_HIGH_VALUE, 
	SR_DB_REJECT_ABSOLUTEDISTANCE_ENABLED, 
	SR_DB_REJECT_ABSOLUTEDISTANCE_LOW_ENABLED, 
	SR_DB_REJECT_ABSOLUTEDISTANCE_HIGH_ENABLED, 
	SR_DB_REJECT_ABSOLUTEDISTANCE_LOW_VALUE, 
	SR_DB_REJECT_ABSOLUTEDISTANCE_HIGH_VALUE, 
	SR_DB_SUSPECT_COLLAPSEDISTANCE_ENABLED, 
	SR_DB_SUSPECT_COLLAPSEDISTANCE_LOW_ENABLED, 
	SR_DB_SUSPECT_COLLAPSEDISTANCE_HIGH_ENABLED, 
	SR_DB_SUSPECT_COLLAPSEDISTANCE_LOW_VALUE, 
	SR_DB_SUSPECT_COLLAPSEDISTANCE_HIGH_VALUE, 
	SR_DB_REJECT_COLLAPSEDISTANCE_ENABLED, 
	SR_DB_REJECT_COLLAPSEDISTANCE_LOW_ENABLED, 
	SR_DB_REJECT_COLLAPSEDISTANCE_HIGH_ENABLED, 
	SR_DB_REJECT_COLLAPSEDISTANCE_LOW_VALUE, 
	SR_DB_REJECT_COLLAPSEDISTANCE_HIGH_VALUE, 
	SR_DB_SUSPECT_TRIGGERDISTANCE_ENABLED, 
	SR_DB_SUSPECT_TRIGGERDISTANCE_LOW_ENABLED, 
	SR_DB_SUSPECT_TRIGGERDISTANCE_HIGH_ENABLED, 
	SR_DB_SUSPECT_TRIGGERDISTANCE_LOW_VALUE, 
	SR_DB_SUSPECT_TRIGGERDISTANCE_HIGH_VALUE, 
	SR_DB_REJECT_TRIGGERDISTANCE_ENABLED, 
	SR_DB_REJECT_TRIGGERDISTANCE_LOW_ENABLED, 
	SR_DB_REJECT_TRIGGERDISTANCE_HIGH_ENABLED, 
	SR_DB_REJECT_TRIGGERDISTANCE_LOW_VALUE, 
	SR_DB_REJECT_TRIGGERDISTANCE_HIGH_VALUE, 
	SR_DB_SUSPECT_ENDWELDFORCE_ENABLED, 
	SR_DB_SUSPECT_ENDWELDFORCE_LOW_ENABLED, 
	SR_DB_SUSPECT_ENDWELDFORCE_HIGH_ENABLED, 
	SR_DB_SUSPECT_ENDWELDFORCE_LOW_VALUE, 
	SR_DB_SUSPECT_ENDWELDFORCE_HIGH_VALUE, 
	SR_DB_REJECT_ENDWELDFORCE_ENABLED, 
	SR_DB_REJECT_ENDWELDFORCE_LOW_ENABLED, 
	SR_DB_REJECT_ENDWELDFORCE_HIGH_ENABLED, 
	SR_DB_REJECT_ENDWELDFORCE_LOW_VALUE, 
	SR_DB_REJECT_ENDWELDFORCE_HIGH_VALUE, 
	SR_DB_SUSPECT_FREQUENCY_ENABLED, 
	SR_DB_SUSPECT_FREQUENCY_LOW_ENABLED, 
	SR_DB_SUSPECT_FREQUENCY_HIGH_ENABLED, 
	SR_DB_SUSPECT_FREQUENCY_LOW_VALUE, 
	SR_DB_SUSPECT_FREQUENCY_HIGH_VALUE, 
	SR_DB_REJECT_FREQUENCY_ENABLED, 
	SR_DB_REJECT_FREQUENCY_LOW_ENABLED, 
	SR_DB_REJECT_FREQUENCY_HIGH_ENABLED, 
	SR_DB_REJECT_FREQUENCY_LOW_VALUE, 
	SR_DB_REJECT_FREQUENCY_HIGH_VALUE
};

enum SuspectRejectIndexes
{
	SR_RECIPE_NUMBER = 0,
	SR_RECIPE_VERSION_NUMBER,
	SR_GLOBAL_SUSPECT,
	SR_GLOBAL_REJECT,
	SR_TIME,
	SR_ENERGY,
	SR_POWER,
	SR_ABSOLUTE_DISTANCE,
	SR_COLLAPSE_DISTANCE,
	SR_TRIGGER_DISTANCE,
	SR_END_WELD_FORCE,
	SR_FREQUENCY
};

enum SuspectRejectInternalIndexes
{
	GLOBAL_SUSPECT = 1,
	GLOBAL_REJECT,
	SUSPECT_ENABLED,
	SUSPECT_LOW_ENABLED,
	SUSPECT_HIGH_ENABLED,
	SUSPECT_LOW_VALUE,
	SUSPECT_HIGH_VALUE,
	REJECT_ENABLED,
	REJECT_LOW_ENABLED,
	REJECT_HIGH_ENABLED,
	REJECT_LOW_VALUE,
	REJECT_HIGH_VALUE
};

enum SetupLimitsIndexes
{
	SETUP_RECIPE_NUMBER = 0,
	SETUP_RECIPE_VERSION_NUMBER,
	SETUP_GLOBAL_SETUP,
	SETUP_WELD_MODE,
	SETUP_WELD_AMP,
	SETUP_WELD_FORCE,
	SETUP_TRIGGER_FORCE,
	SETUP_HOLD_FORCE,
	SETUP_HOLD_TIME,
	SETUP_SCRUB_AMP,
	SETUP_SCRUB_TIME,
	SETUP_REACTIVITY,
	SETUP_FORCE_LEVEL
};

enum WeldModes
{
	WM_TIME = 1,
	WM_ENERGY,
	WM_POWER,
	WM_GROUND_DETECT,
	WM_ABSOLUTE_DISTANCE,
	WM_COLLAPSE_DISTANCE,
	WM_DYNAMIC
};

enum StepAtValues
{
	STEP_AT_TIME = 1,
	STEP_AT_ENERGY,
	STEP_AT_POWER,
	STEP_AT_ABSOLUTE_DISTANCE,
	STEP_AT_COLLAPSE_DISTANCE,
	STEP_AT_EXTERNAL_SIGNAL,
};

enum WeldModeValueIndexInMAP
{
	WELD_MODE_TIME = 600,
	WELD_MODE_ENERGY,
	WELD_MODE_POWER,
	WELD_MODE_ABSOLUTE_DISTANCE,
	WELD_MODE_COLLAPSE_DISTANCE,
	WELD_MODE_SCRUB_TIME,
	WELD_MODE_DENSITY
};

enum RecipeValidateStatus
{
	VALUE_INRANGE = 0,
	MIN_MAX_RANGE_MISMATCH,
	SUSPECT_REJECT__LIMITS_RANGE_MISMATCH,
	CONTROL_LIMITS__RANGE_MISMATCH,
	WRONG_DECIMAL_VALUE,
	EXPECTED_PART_CONTACT_NOT_SET
};

struct stRecipeParmInfo
{
	int dwIndexInDB;
    string ParamUnit;
    string ParamDefaultValue[3];
    string ParamMinValue[3];
    string ParamMaxValue[3];
};

enum SystemFreq
{
    SYSTEM_TYPE_20KHZ =0,
    SYSTEM_TYPE_30KHZ,
    SYSTEM_TYPE_40KHZ
};

typedef enum
{
	UNKNOWN_PARAM = 0,
	SC_PARAM,
	AC_PARAM,
	PC_PARAM
}ParamType;

enum SRIndividualIndex
{
	SUS_ENABLED,
	SUS_LOW_ENABLED,
	SUS_HIGH_ENABLED,
	SUS_LOW_VALUE,
	SUS_HIGH_VALUE,
	REJ_ENABLED,
	REJ_LOW_ENABLED,
	REJ_HIGH_ENABLED,
	REJ_LOW_VALUE,
	REJ_HIGH_VALUE
};

class Recipe
{
public:
	
	Recipe();
	~Recipe();
	bool 		InitializeRecipeMapWithDefaultValues();
	bool 		ValidateParamID(int dwParamID, char *dParamValue);
	WS_STATUS 	GetParamValue(int dwParamID, char *chParamValue);
	WS_STATUS 	SetParamValue(int dwParamID, char *chParamValue);
	ParamType	GetParamType(int dwParamID);
	
	MSG_Q_ID  	UI_MSG_Q_ID;
private:
	WS_STATUS 	GetParamValueByID(int dwParamID, int &dwParamValue);
	WS_STATUS 	SetParamValueByID(int dwParamID, double dwParamValue);
	WS_STATUS 	SetParamValueInStructure(int dwParamID, int dwParamValue);
	bool		ValidateParamValueRangeInSuspectRejectLimits(int dwParamID, int dwParamValue);
	bool		ValidateSuspectRejectLimitsWithParamValue(int dwParamID, int dwParamValue);
	void		AddNewParamToMap( string strMetricUnit,
				string str20KDefaultValue, string str20KMinValue, string str20KMaxValue,
				string str30KDefaultValue, string str30KMinValue, string str30KMaxValue,
				string str40KDefaultValue, string str40KMinValue, string str40KMaxValue,
				int dwDBIndex, int dwIndex);
	bool 		ValidateValueWithSuspectRejectByID(int dwParamID, int dwValidateValue, int dwSRModifiedParam=0, int dwSRModifidParamValue=0);
	bool 		ValidateValueWithSuspectRejectByValues(int dwParamValue,
				int dwGlobalSuspect, int dwSuspect, 
				int dwSuspectLow, int dwSuspectLowValue, int dwSuspectHigh, int dwSuspectHighValue, 
				int dwGlobalReject, int dwReject, 
				int dwRejectLow, int dwRejectLowValue, int dwRejectHigh, int dwRejectHighValue);
	void 		CreateRecipeParamaterStructure();
	void 		AddASXRecipeParamaterToStructure();
	void 		AddGSXE1RecipeParamaterToStructure();
	int 		GetModeValueIndexByWeldMode();
	int			GetDefaultValue(int dwParamID);
	int 		GetMinValue(int dwParamID);
	int 		GetMaxValue(int dwParamID);
	RecipeValidateStatus	ValidateParamValueByID(int dwParamID, char *dParamValue);
	void 		ConvertValueUnitForID(int dwParamID, double dOriginalValue, char *chConvertedValue, bool bIsValueReadingFromDB);
	CommonProperty 			*CP;
	map<int,stRecipeParmInfo> m_MapRecipeParams;
	
	int			dwSystemFrequnecyType;
};
#endif /* RECIPE_H_ */
