# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_RPC  {}
set _VSB_LAYER_CDFPATH_RPC [concat  $_VSB_LAYER_CDFPATH_RPC C:/WindRiver/vxworks-7/pkgs/os/service/rpc-1.0.0.12/cdf]
