# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_SDMMC_CORE  {}
set _VSB_LAYER_CDFPATH_SDMMC_CORE [concat  $_VSB_LAYER_CDFPATH_SDMMC_CORE C:/WindRiver/vxworks-7/pkgs/connectivity/sdmmc-1.0.1.3/core-1.0.0.12/cdf]
