# this file is automatically generated by mk/krnl/rules.layers.mk
VSBL_CDFPATH_RUNTIME_ANALYSIS =
VSBL_CDFPATH_RUNTIME_ANALYSIS += C:/WindRiver/vxworks-7/pkgs/rttools/cafe-1.1.3.6/src/osconfig/vxworks/cdf/common
VSBL_CDFPATH_RUNTIME_ANALYSIS += C:/WindRiver/vxworks-7/pkgs/rttools/cafe-1.1.3.6/src/osconfig/vxworks/cdf/arch/common
VSBL_CDFPATH_RUNTIME_ANALYSIS += C:/WindRiver/vxworks-7/pkgs/rttools/cafe-1.1.3.6/src/osconfig/vxworks/cdf/arch/arm
