

/* this file is automatically generated */


Layer Layer::USB_CORE {
}




/*********************************
 Component INCLUDE_USB 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 197 212  
**********************************/
Component	INCLUDE_USB {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 197 212 }
}


/*********************************
 Component INCLUDE_USB_INIT 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 214 222  
**********************************/
Component	INCLUDE_USB_INIT {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 214 222 }
}


/*********************************
 Component INCLUDE_USB_SHOW 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 293 299  
**********************************/
Component	INCLUDE_USB_SHOW {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 293 299 }
}


/*********************************
 Component INCLUDE_USB_TRACK_TU 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 330 336  
**********************************/
Component	INCLUDE_USB_TRACK_TU {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 330 336 }
}


/*********************************
 Folder FOLDER_CONNECTIVITY 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 171 175  
**********************************/
Folder	FOLDER_CONNECTIVITY {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 171 175 }
}


/*********************************
 Folder FOLDER_USB 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 179 183  
**********************************/
Folder	FOLDER_USB {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 179 183 }
}


/*********************************
 Folder FOLDER_USB_COMMON 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 185 189  
**********************************/
Folder	FOLDER_USB_COMMON {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 185 189 }
}


/*********************************
 Folder FOLDER_USB_CONTROLLER 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 191 195  
**********************************/
Folder	FOLDER_USB_CONTROLLER {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 191 195 }
}


/*********************************
 Folder FOLDER_USB_SHOW 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 286 291  
**********************************/
Folder	FOLDER_USB_SHOW {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 286 291 }
}


/*********************************
 Folder FOLDER_USB_DEBUG 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 311 315  
**********************************/
Folder	FOLDER_USB_DEBUG {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 311 315 }
}


/*********************************
 Folder FOLDER_USB_TRACK 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 317 321  
**********************************/
Folder	FOLDER_USB_TRACK {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 317 321 }
}


/*********************************
 Folder FOLDER_USB_TRACK_TU 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 323 328  
**********************************/
Folder	FOLDER_USB_TRACK_TU {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 323 328 }
}


/*********************************
 InitGroup usrUsbPerStageInit 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 225 238  
**********************************/
InitGroup	usrUsbPerStageInit {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 225 238 }
}


/*********************************
 InitGroup usrUsbGroupInit 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 241 250  
**********************************/
InitGroup	usrUsbGroupInit {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 241 250 }
}


/*********************************
 Layer Layer::USB_CORE 
 original object sources located at 
  "C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/cdf_PRENOBUILD_USB_CORE.tmp" 13 15  
**********************************/
Layer	Layer::USB_CORE {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "C:/ScriptGSX2_4/GSX2_4Stream/AM4377_VSB/krnl/cdf/cdf_PRENOBUILD_USB_CORE.tmp" 13 15 }
}


/*********************************
 Parameter USB_HUB_POLLING_INTERVAL 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 252 258  
**********************************/
Parameter	USB_HUB_POLLING_INTERVAL {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 252 258 }
}


/*********************************
 Parameter USB_MEM_PART_SIZE 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 260 266  
**********************************/
Parameter	USB_MEM_PART_SIZE {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 260 266 }
}


/*********************************
 Parameter USB_CHECK_RESUBMIT_URB_FLAG 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 268 274  
**********************************/
Parameter	USB_CHECK_RESUBMIT_URB_FLAG {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 268 274 }
}


/*********************************
 Parameter USB_WAIT_TIME_OUT_VALUE 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 276 282  
**********************************/
Parameter	USB_WAIT_TIME_OUT_VALUE {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 276 282 }
}


/*********************************
 Parameter USB_SHOW_LEVEL 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 301 305  
**********************************/
Parameter	USB_SHOW_LEVEL {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 301 305 }
}


/*********************************
 Parameter USB_TRACK_TU 
 original object sources located at 
  "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 338 342  
**********************************/
Parameter	USB_TRACK_TU {
		LAYER += Layer::USB_CORE
		LAYER_SOURCE		{ "$(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/core-1.0.2.9/cdf/40usb.cdf" 338 342 }
}
