# Automatically generated file: do not edit

##########################
# CORE_IO_VXTEST Section
##########################


ifdef _WRS_CONFIG_CORE_IO_VXTEST
VSBL_CORE_IO_VXTEST_SRC = 
VSBL_CORE_IO_VXTEST_DEPEND = 
ifdef _WRS_CONFIG_CORE_IO_1_2_6_0_VXTEST_1_0_0_1
VSBL_CORE_IO_VXTEST_SRC += CORE_IO_VXTEST
VSBL_CORE_IO_VXTEST_DEPEND += CORE_KERNEL_VXTEST
CORE_IO_VXTEST_FASTBUILD = YES
VSBL_CORE_IO_VXTEST_PATH = $(WIND_BASE)/pkgs/os/core/io-1.2.6.0/vxTest
VSBL_CORE_IO_VXTEST_VERSION = CORE_IO_1_2_6_0_VXTEST_1_0_0_1
endif
endif

