# Automatically generated file: do not edit

##########################
# CRYPTOMISC_IPFREESCALE Section
##########################


ifdef _WRS_CONFIG_CRYPTOMISC_IPFREESCALE
VSBL_CRYPTOMISC_IPFREESCALE_SRC = 
VSBL_CRYPTOMISC_IPFREESCALE_DEPEND = 
ifdef _WRS_CONFIG_CRYPTOMISC_1_0_0_7_IPFREESCALE_1_0_0_4
VSBL_CRYPTOMISC_IPFREESCALE_SRC += CRYPTOMISC_IPFREESCALE
VSBL_CRYPTOMISC_IPFREESCALE_DEPEND += CRYPTOMISC_IPHWCRYPTO
CRYPTOMISC_IPFREESCALE_FASTBUILD = YES
VSBL_CRYPTOMISC_IPFREESCALE_PATH = $(WIND_BASE)/pkgs/security/crypto_misc-1.0.0.7/ipfreescale
VSBL_CRYPTOMISC_IPFREESCALE_VERSION = CRYPTOMISC_1_0_0_7_IPFREESCALE_1_0_0_4
endif
endif

