# Automatically generated file: do not edit

##########################
# USER_PRIVILEGES Section
##########################


ifdef _WRS_CONFIG_USER_PRIVILEGES
VSBL_USER_PRIVILEGES_SRC = 
VSBL_USER_PRIVILEGES_DEPEND = 
ifdef _WRS_CONFIG_USER_PRIVILEGES_1_1_0_3
VSBL_USER_PRIVILEGES_SRC += USER_PRIVILEGES
VSBL_USER_PRIVILEGES_DEPEND += CORE_KERNEL
VSBL_USER_PRIVILEGES_DEPEND += SHELL
VSBL_USER_PRIVILEGES_DEPEND += USER_MANAGEMENT
VSBL_USER_PRIVILEGES_DEPEND += CORE_KERNEL
USER_PRIVILEGES_FASTBUILD = YES
VSBL_USER_PRIVILEGES_PATH = $(WIND_BASE)/pkgs/security/user_privileges-1.1.0.3
VSBL_USER_PRIVILEGES_VERSION = USER_PRIVILEGES_1_1_0_3
endif
endif

