# Automatically generated file: do not edit

##########################
# HDC_CCG_BROKER Section
##########################


ifdef _WRS_CONFIG_HDC_CCG_BROKER
VSBL_HDC_CCG_BROKER_SRC = 
VSBL_HDC_CCG_BROKER_DEPEND = 
ifdef _WRS_CONFIG_HDC_2_2_0_1_CCG_BROKER_1_0_0_1
VSBL_HDC_CCG_BROKER_SRC += HDC_CCG_BROKER
VSBL_HDC_CCG_BROKER_DEPEND += JSON
VSBL_HDC_CCG_BROKER_DEPEND += OPENSSL
VSBL_HDC_CCG_BROKER_DEPEND += JSON
HDC_CCG_BROKER_FASTBUILD = YES
VSBL_HDC_CCG_BROKER_PATH = $(WIND_BASE)/pkgs/app/hdc-2.2.0.1/ccg
VSBL_HDC_CCG_BROKER_VERSION = HDC_2_2_0_1_CCG_BROKER_1_0_0_1
endif
endif

