# Automatically generated file: do not edit

##########################
# VXBUS_LEGACY_VXTEST Section
##########################


ifdef _WRS_CONFIG_VXBUS_LEGACY_VXTEST
VSBL_VXBUS_LEGACY_VXTEST_SRC = 
VSBL_VXBUS_LEGACY_VXTEST_DEPEND = 
ifdef _WRS_CONFIG_VXBUS_LEGACY_1_1_3_7_VXTEST_1_0_0_1
VSBL_VXBUS_LEGACY_VXTEST_SRC += VXBUS_LEGACY_VXTEST
VSBL_VXBUS_LEGACY_VXTEST_DEPEND += CORE_KERNEL_VXTEST
VXBUS_LEGACY_VXTEST_FASTBUILD = YES
VSBL_VXBUS_LEGACY_VXTEST_PATH = $(WIND_BASE)/pkgs/os/drv/vxbus_legacy-1.1.3.7/vxTest
VSBL_VXBUS_LEGACY_VXTEST_VERSION = VXBUS_LEGACY_1_1_3_7_VXTEST_1_0_0_1
endif
endif

