# Automatically generated file: do not edit

##########################
# WIBU_BASIC_SECURITY Section
##########################


ifdef _WRS_CONFIG_WIBU_BASIC_SECURITY
VSBL_WIBU_BASIC_SECURITY_SRC = 
VSBL_WIBU_BASIC_SECURITY_DEPEND = 
ifdef _WRS_CONFIG_WIBU_BASIC_SECURITY_1_0_2_2
VSBL_WIBU_BASIC_SECURITY_SRC += WIBU_BASIC_SECURITY
VSBL_WIBU_BASIC_SECURITY_DEPEND += LOADER
WIBU_BASIC_SECURITY_FASTBUILD = YES
VSBL_WIBU_BASIC_SECURITY_PATH = $(WIND_BASE)/pkgs/security/wibu_basic_security-1.0.2.2
VSBL_WIBU_BASIC_SECURITY_VERSION = WIBU_BASIC_SECURITY_1_0_2_2
endif
endif

