# Automatically generated file: do not edit

##########################
# TROUSERS Section
##########################


ifdef _WRS_CONFIG_TROUSERS
VSBL_TROUSERS_SRC = 
VSBL_TROUSERS_DEPEND = 
ifdef _WRS_CONFIG_TROUSERS_1_0_1_1
VSBL_TROUSERS_SRC += TROUSERS
VSBL_TROUSERS_DEPEND += FS_HRFS
VSBL_TROUSERS_DEPEND += SEC_CRYPTO
TROUSERS_FASTBUILD = YES
VSBL_TROUSERS_PATH = $(WIND_BASE)/pkgs/security/TrouSerS-1.0.1.1
VSBL_TROUSERS_VERSION = TROUSERS_1_0_1_1
endif
endif

