# Automatically generated file: do not edit

##########################
# USER_MANAGEMENT_LDAP Section
##########################


ifdef _WRS_CONFIG_USER_MANAGEMENT_LDAP
VSBL_USER_MANAGEMENT_LDAP_SRC = 
VSBL_USER_MANAGEMENT_LDAP_DEPEND = 
ifdef _WRS_CONFIG_USER_MANAGEMENT_LDAP_1_0_0_0
VSBL_USER_MANAGEMENT_LDAP_SRC += USER_MANAGEMENT_LDAP
VSBL_USER_MANAGEMENT_LDAP_DEPEND += CORE_KERNEL
VSBL_USER_MANAGEMENT_LDAP_DEPEND += LDAPC
VSBL_USER_MANAGEMENT_LDAP_DEPEND += OPENSSL
VSBL_USER_MANAGEMENT_LDAP_DEPEND += USER_MANAGEMENT
VSBL_USER_MANAGEMENT_LDAP_DEPEND += USER_MANAGEMENT
USER_MANAGEMENT_LDAP_FASTBUILD = YES
VSBL_USER_MANAGEMENT_LDAP_PATH = $(WIND_BASE)/pkgs/security/user_management_ldap-1.0.0.0
VSBL_USER_MANAGEMENT_LDAP_VERSION = USER_MANAGEMENT_LDAP_1_0_0_0
endif
endif

