# Automatically generated file: do not edit

##########################
# CRYPTOMISC_IPHWCRYPTO Section
##########################


ifdef _WRS_CONFIG_CRYPTOMISC_IPHWCRYPTO
VSBL_CRYPTOMISC_IPHWCRYPTO_SRC = 
VSBL_CRYPTOMISC_IPHWCRYPTO_DEPEND = 
ifdef _WRS_CONFIG_CRYPTOMISC_1_0_0_7_IPHWCRYPTO_1_0_0_3
VSBL_CRYPTOMISC_IPHWCRYPTO_SRC += CRYPTOMISC_IPHWCRYPTO
VSBL_CRYPTOMISC_IPHWCRYPTO_DEPEND += OPENSSL
CRYPTOMISC_IPHWCRYPTO_FASTBUILD = YES
VSBL_CRYPTOMISC_IPHWCRYPTO_PATH = $(WIND_BASE)/pkgs/security/crypto_misc-1.0.0.7/iphwcrypto
VSBL_CRYPTOMISC_IPHWCRYPTO_VERSION = CRYPTOMISC_1_0_0_7_IPHWCRYPTO_1_0_0_3
endif
endif

