# Automatically generated file: do not edit

##########################
# IPNET_QAVQBV Section
##########################


ifdef _WRS_CONFIG_IPNET_QAVQBV
VSBL_IPNET_QAVQBV_SRC = 
VSBL_IPNET_QAVQBV_DEPEND = 
ifdef _WRS_CONFIG_IPNET_1_1_1_2_TSN_1_0_0_1_QAVQBV_1_0_0_1
VSBL_IPNET_QAVQBV_SRC += IPNET_QAVQBV
VSBL_IPNET_QAVQBV_DEPEND += END_LIB
VSBL_IPNET_QAVQBV_DEPEND += END
IPNET_QAVQBV_FASTBUILD = YES
VSBL_IPNET_QAVQBV_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/tsn-1.0.0.1/qavqbv
VSBL_IPNET_QAVQBV_VERSION = IPNET_1_1_1_2_TSN_1_0_0_1_QAVQBV_1_0_0_1
endif
endif

