# Automatically generated file: do not edit

##########################
# VXBUS_VXTEST_SUBSYSTEM Section
##########################


ifdef _WRS_CONFIG_VXBUS_VXTEST_SUBSYSTEM
VSBL_VXBUS_VXTEST_SUBSYSTEM_SRC = 
VSBL_VXBUS_VXTEST_SUBSYSTEM_DEPEND = 
ifdef _WRS_CONFIG_VXBUS_1_0_5_0_SUBSYSTEM_1_0_10_0_VXTEST_SUBSYSTEM_1_0_0_1
VSBL_VXBUS_VXTEST_SUBSYSTEM_SRC += VXBUS_VXTEST_SUBSYSTEM
VSBL_VXBUS_VXTEST_SUBSYSTEM_DEPEND += CORE_KERNEL_VXTEST
VXBUS_VXTEST_SUBSYSTEM_FASTBUILD = YES
VSBL_VXBUS_VXTEST_SUBSYSTEM_PATH = $(WIND_BASE)/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/vxTest
VSBL_VXBUS_VXTEST_SUBSYSTEM_VERSION = VXBUS_1_0_5_0_SUBSYSTEM_1_0_10_0_VXTEST_SUBSYSTEM_1_0_0_1
endif
endif

