# Automatically generated file: do not edit

##########################
# FSAPI_TCPLAY Section
##########################


ifdef _WRS_CONFIG_FSAPI_TCPLAY
VSBL_FSAPI_TCPLAY_SRC = 
VSBL_FSAPI_TCPLAY_DEPEND = 
ifdef _WRS_CONFIG_FSAPI_1_0_0_1_TCPLAY_2_0_3_2
VSBL_FSAPI_TCPLAY_SRC += FSAPI_TCPLAY
VSBL_FSAPI_TCPLAY_DEPEND += BDM_LOOPFS
VSBL_FSAPI_TCPLAY_DEPEND += ERF
VSBL_FSAPI_TCPLAY_DEPEND += FS_COMMON
VSBL_FSAPI_TCPLAY_DEPEND += SEC_CRYPTO
VSBL_FSAPI_TCPLAY_DEPEND += FS_COMMON
FSAPI_TCPLAY_FASTBUILD = YES
VSBL_FSAPI_TCPLAY_PATH = $(WIND_BASE)/pkgs/storage/api-1.0.0.1/tcplay-2.0.3.2
VSBL_FSAPI_TCPLAY_VERSION = FSAPI_1_0_0_1_TCPLAY_2_0_3_2
endif
endif

