# Automatically generated file: do not edit

##########################
# CORE_KERNEL_VXTEST Section
##########################


ifdef _WRS_CONFIG_CORE_KERNEL_VXTEST
VSBL_CORE_KERNEL_VXTEST_SRC = 
VSBL_CORE_KERNEL_VXTEST_DEPEND = 
ifdef _WRS_CONFIG_CORE_KERNEL_1_2_3_0_VXTEST_1_0_0_2
VSBL_CORE_KERNEL_VXTEST_SRC += CORE_KERNEL_VXTEST
ifdef _WRS_CONFIG_CORE_USER
VSBL_CORE_KERNEL_VXTEST_DEPEND += CORE_USER
endif
ifdef _WRS_CONFIG_CORE_USER*
VSBL_CORE_KERNEL_VXTEST_DEPEND += CORE_USER
endif
CORE_KERNEL_VXTEST_FASTBUILD = YES
VSBL_CORE_KERNEL_VXTEST_PATH = $(WIND_BASE)/pkgs/os/core/kernel-1.2.3.0/vxTest
VSBL_CORE_KERNEL_VXTEST_VERSION = CORE_KERNEL_1_2_3_0_VXTEST_1_0_0_2
endif
endif

