#ifndef LOCALIZEHEADER_H
#define LOCALIZEHEADER_H

#endif // LOCALIZEHEADER_H

#define CUST_NAME_TIME                      QObject::tr("Time")
#define CUST_NAME_ENERGY                    QObject::tr("Energy")
#define CUST_NAME_PEAK                      QObject::tr("Peak power")
#define CUST_NAME_ABSOLUTE                  QObject::tr("Absolute Distance")
#define CUST_NAME_COLLAPSE                  QObject::tr("Collapse Distance")
#define CUST_NAME_SCRUB                     QObject::tr("Scrub Time")
#define CUST_NAME_GROUND                    QObject::tr("Ground Detect")
#define CUST_NAME_DENSITY                   QObject::tr("Density")
#define CUST_NAME_DYNAMIC                   QObject::tr("Dynamic")

#define CUST_NAME_WELD_TIME                 QObject::tr("WeldTime")
#define CUST_NAME_WELD_FORCE                QObject::tr("WeldForce")
#define CUST_NAME_WELD_ENERGY               QObject::tr("WeldEnergy")
#define CUST_NAME_HOLD_FORCE                QObject::tr("HoldForce")
#define CUST_NAME_AMPLITUDE                 QObject::tr("Amplitude")
#define CUST_NAME_CURRENT                   QObject::tr("Rated Current")
#define CUST_NAME_PHASE                     QObject::tr("Phase")
#define CUST_NAME_IMPEDANCE                 QObject::tr("Impedance")
#define CUST_NAME_WELD                      QObject::tr("Weld Mode")
#define CUST_NAME_REACTIVITY                QObject::tr("Reactivity")
#define CUST_NAME_FREQUENCY                 QObject::tr("Frequency")
#define CUST_NAME_POWER                     QObject::tr("Power")
#define CUST_NAME_MEMORY                    QObject::tr("Memory")


#define NO_VALUE                QObject::tr("NA")
#define DAS_NO_ACTIVE_RECIPE    QObject::tr("No Active Recipe Available")

#define RECIPE_NEW              QObject::tr("New")
#define RECIPE_SAVE             QObject::tr("Save")
#define RECIPE_COPY             QObject::tr("Copy")
#define RECIPE_SYNC             QObject::tr("Sync")
#define RECIPE_ACTIVE           QObject::tr("Set as Active")
#define RECIPE_VALIDATE         QObject::tr("Validate")
#define RECIPE_INVALIDATE       QObject::tr("Invalidate")
#define RECIPE_REPORT           QObject::tr("Generate Report")

#define RECIPE_PARAM_STEP_TIME               QObject::tr("Step@Time")
#define RECIPE_PARAM_STEP_ENERGY             QObject::tr("Step@Energy")
#define RECIPE_PARAM_STEP_POWER              QObject::tr("Step@Pk Power")
#define RECIPE_PARAM_STEP_AD                 QObject::tr("Step@Absolute")
#define RECIPE_PARAM_STEP_CD                 QObject::tr("Step@Collapse")
#define RECIPE_PARAM_STEP_EXT_SIG            QObject::tr("Step@Ext. Signal")
#define RECIPE_PARAM_TIME                    QObject::tr("TIME")
#define RECIPE_PARAM_ENERGY                  QObject::tr("ENERGY")
#define RECIPE_PARAM_PEAK_POWER              QObject::tr("PEAK POWER")
#define RECIPE_PARAM_PEAK_POWER_SHORT_NAME   QObject::tr("POWER")
#define RECIPE_PARAM_AD                      QObject::tr("ABSOLUTE DISTANCE")
#define RECIPE_PARAM_AD_SHORT_NAME           QObject::tr("ABS DIS", "Short name for Absolute Distance")
#define RECIPE_PARAM_CD                      QObject::tr("COLLAPSE DISTANCE")
#define RECIPE_PARAM_CD_SHORT_NAME           QObject::tr("COL DIS", "Short name for Collapse Distance")
#define RECIPE_PARAM_ST                      QObject::tr("SCRUB TIME")
#define RECIPE_PARAM_GD                      QObject::tr("GROUND DETECT")
#define RECIPE_PARAM_GD_SHORT_NAME           QObject::tr("GND DET", "Short name for Ground Detect")
#define RECIPE_PARAM_DY                      QObject::tr("DYNAMIC")
#define RECIPE_PARAM_DENSITY                 QObject::tr("DENSITY")
#define RECIPE_PARAM_REACTIVITY              QObject::tr("REACTIVITY")
#define RECIPE_PARAM_MULTI_MODE              QObject::tr("MULTI MODE")
#define RECIPE_PARAM_FORCE_LEVEL_ENABLE      QObject::tr("FORCE LEVEL ENABLE")
#define RECIPE_PARAM_FORCE_LEVEL             QObject::tr("FORCE LEVEL")
#define RECIPE_PARAM_FORCE_LEVEL_TIME        QObject::tr("FORCE LEVEL TIME")
#define RECIPE_PARAM_HOLD_TIME               QObject::tr("HOLD TIME")
#define RECIPE_PARAM_SCRUB_AMP               QObject::tr("SCRUB AMPLITUDE")
#define RECIPE_PARAM_TRI_FORCE               QObject::tr("TRIGGER FORCE")
#define RECIPE_PARAM_TRI_DIS                 QObject::tr("TRIGGER DISTANCE")
#define RECIPE_PARAM_MAX_TIMEOUT             QObject::tr("MAX TIMEOUT")
#define RECIPE_PARAM_WELD_AMP                QObject::tr("WELD AMPLITUDE")
#define RECIPE_PARAM_EXTRA_COOLING           QObject::tr("EXTRA COOLING")
#define RECIPE_PARAM_G_SUSPECT               QObject::tr("GLOBAL SUSPECT")
#define RECIPE_PARAM_G_REJECT                QObject::tr("GLOBAL REJECT")
#define RECIPE_PARAM_CONTROL                 QObject::tr("CONTROL")
#define RECIPE_PARAM_POWER_CO                QObject::tr("PEAK POWER CUTOFF")
#define RECIPE_PARAM_AD_CO                   QObject::tr("ABSOLUTE DISTANCE CUTOFF")
#define RECIPE_PARAM_CD_CO                   QObject::tr("COLLAPSE DISTANCE CUTOFF")
#define RECIPE_PARAM_TIME_CO                 QObject::tr("TIME CUTOFF")
#define RECIPE_PARAM_FREQ_LO_CO              QObject::tr("FREQUENCY LOW CUTOFF")
#define RECIPE_PARAM_FREQ_HI_CO              QObject::tr("FREQUENCY HIGH CUTOFF")
#define RECIPE_PARAM_ENERGY_CO               QObject::tr("ENERGY CUTOFF")
#define RECIPE_PARAM_GD_CO                   QObject::tr("GROUND DETECT CUTOFF")
#define RECIPE_PARAM_PRETRIGGER              QObject::tr("PRETRIGGER")
#define RECIPE_PARAM_PRE_DIS                 QObject::tr("PRETRIGGER DISTANCE")
#define RECIPE_PARAM_PRE_AMP                 QObject::tr("PRETRIGGER AMPLITUDE")
#define RECIPE_PARAM_AB                      QObject::tr("AFTERBURST")
#define RECIPE_PARAM_AB_AMP                  QObject::tr("AFTERBURST AMPLITUDE")
#define RECIPE_PARAM_AB_DELAY                QObject::tr("AFTERBURST DELAY")
#define RECIPE_PARAM_AB_TIME                 QObject::tr("AFTERBURST TIME")
#define RECIPE_PARAM_EB                      QObject::tr("ENERGY BRAKE")
#define RECIPE_PARAM_EB_AMP                  QObject::tr("ENERGY BRAKE AMPLITUDE")
#define RECIPE_PARAM_EB_TIME                 QObject::tr("ENERGY BRAKE TIME")
#define RECIPE_PARAM_END_WELD_FORCE          QObject::tr("END WELD FORCE")
#define RECIPE_PARAM_FREQ                    QObject::tr("FREQUENCY")
#define RECIPE_PARAM_TIMED_SEEK_PERIOD       QObject::tr("TIMED SEEK PERIOD")
#define RECIPE_PARAM_TIMED_SEEK              QObject::tr("TIMED SEEK")
#define RECIPE_PARAM_PRE_WELD_SEEK           QObject::tr("PRE-WELD SEEK")
#define RECIPE_PARAM_POST_WELD_SEEK          QObject::tr("POST-WELD SEEK")
#define RECIPE_PARAM_AMP_C1                  QObject::tr("AMPLITUDELOOPC1")
#define RECIPE_PARAM_AMP_C2                  QObject::tr("AMPLITUDELOOPC2")
#define RECIPE_PARAM_PHASE_LOOP              QObject::tr("PHASE LOOP")
#define RECIPE_PARAM_PHASE_LOOP_CF           QObject::tr("PHASE LOOP CF")
#define RECIPE_PARAM_FREQ_LOW                QObject::tr("FREQUENCY LOW")
#define RECIPE_PARAM_FREQ_HIGH               QObject::tr("FREQUENCY HIGH")
#define RECIPE_PARAM_PHASE_LIMIT_TIME        QObject::tr("PHASE LIMIT TIME")
#define RECIPE_PARAM_PHASE_LIMIT             QObject::tr("PHASE LIMIT")
#define RECIPE_PARAM_CONTROL_MODE            QObject::tr("CONTROL MODE")
#define RECIPE_PARAM_BLIND_TIME_SEEK         QObject::tr("BLIND TIME SEEK")
#define RECIPE_PARAM_BLIND_TIME_WELD         QObject::tr("BLIND TIME WELD")
#define RECIPE_PARAM_DDS_SWITCH_TIME         QObject::tr("DDS SWITCH TIME")
#define RECIPE_PARAM_PARAMETER_7             QObject::tr("PARAMETER7")
#define RECIPE_PARAM_PARAMETER_8             QObject::tr("PARAMETER8")
#define RECIPE_PARAM_PARAMETER_9             QObject::tr("PARAMETER9")
#define RECIPE_PARAM_PARAMETER_10            QObject::tr("PARAMETER10")
#define RECIPE_PARAM_PARAMETER_11            QObject::tr("PARAMETER11")
#define RECIPE_PARAM_PARAMETER_12            QObject::tr("PARAMETER12")
#define RECIPE_PARAM_PARAMETER_13            QObject::tr("PARAMETER13")
#define RECIPE_PARAM_PARAMETER_14            QObject::tr("PARAMETER14")
#define RECIPE_PARAM_PARAMETER_15            QObject::tr("PARAMETER15")
#define RECIPE_PARAM_F_LIMIT_TIME            QObject::tr("F_LIMIT TIME")
#define RECIPE_PARAM_AMP_PROP_GAIN           QObject::tr("AMP PROPORTIONAL GAIN")
#define RECIPE_PARAM_AMP_INT_GAIN            QObject::tr("AMP INTEGRAL GAIN")
#define RECIPE_PARAM_PHASE_INT_GAIN          QObject::tr("PHASE INTEGRAL GAIN")
#define RECIPE_PARAM_PHASE_PROP_GAIN         QObject::tr("PHASE PROPORTIONAL GAIN")
#define RECIPE_PARAM_FREQ_WIN_SIZE           QObject::tr("FREQUENCY WINDOW SIZE")
#define RECIPE_PARAM_PF_PHASE_CONTROL_LOOP   QObject::tr("PF PHASE CONTROL LOOP")
#define RECIPE_PARAM_PI_FREQ_LOW             QObject::tr("PI FREQUENCY LOW")
#define RECIPE_PARAM_PI_FREQ_HIGH            QObject::tr("PI FREQUENCY HIGH")
#define RECIPE_PARAM_PI_PHASE_LIMIT_TIME     QObject::tr("PI PHASE LIMIT TIME")
#define RECIPE_PARAM_PI_PHASE_LIMIT          QObject::tr("PI PHASE LIMIT")
#define RECIPE_PARAM_WELD_RAMP_TIME          QObject::tr("WELD RAMP TIME")
#define RECIPE_PARAM_START_FREQ              QObject::tr("START FREQUENCY")
#define RECIPE_PARAM_MEMORY_OFFSET           QObject::tr("MEMORY OFFSET")
#define RECIPE_PARAM_DIGITAL_TUNE            QObject::tr("DIGITAL TUNE")
#define RECIPE_PARAM_FREQ_OFFSET             QObject::tr("FREQUENCY OFFSET")
#define RECIPE_PARAM_WELD_FORCE              QObject::tr("WELD FORCE")
#define RECIPE_PARAM_FORCE_RAMP_TIME         QObject::tr("FORCE RAMP TIME")
#define RECIPE_PARAM_HOLD_MODE               QObject::tr("HOLDMODE")
#define RECIPE_PARAM_TOTAL_COLLAPSE_TARGET   QObject::tr("TOTAL COLLAPSE TARGET")
#define RECIPE_PARAM_HOLD_FORCE              QObject::tr("HOLD FORCE")
#define RECIPE_PARAM_HOLD_FORCE_RAMP_TIME    QObject::tr("HOLD FORCE RAMP TIME")
#define RECIPE_PARAM_EXP_PART_CONT           QObject::tr("EXPECTED PART CONTACT")
#define RECIPE_PARAM_READY_OFFSET            QObject::tr("READY OFFSET")
#define RECIPE_PARAM_DOWN_ACC                QObject::tr("DOWN ACCELERATION")
#define RECIPE_PARAM_DOWN_DEC                QObject::tr("DOWN DECELERATION")
#define RECIPE_PARAM_DOWN_MAX_VEL            QObject::tr("DOWN MAX VELOCITY")
#define RECIPE_PARAM_RET_ACC                 QObject::tr("RETURN ACCELERATION")
#define RECIPE_PARAM_RET_MAX_VEL             QObject::tr("RETURN MAX VELOCITY")
#define RECIPE_PARAM_RET_DEC                 QObject::tr("RETURN DECELERATION")
#define RECIPE_PARAM_EXP_CONTACT_OFFSET      QObject::tr("EXPECTED CONTACT OFFSET")
#define RECIPE_PARAM_PART_CON_WIN_MINUS      QObject::tr("PART CONTACT WINDOW MINUS")
#define RECIPE_PARAM_PART_CON_WIN_PLUS       QObject::tr("PART CONTACT WINDOW PLUS")
#define RECIPE_PARAM_EXP_CONTACT_WINDOW      QObject::tr("EXPECTED CONTACT WINDOW")
#define RECIPE_PARAM_GLOBAL_SETUP            QObject::tr("GLOBAL SETUP")

#define RECIPE_PARAM_MENU_SETUP              QObject::tr("Setup")
#define RECIPE_PARAM_MENU_CONTROL            QObject::tr("Control")
#define RECIPE_PARAM_MENU_SPT_RJT            QObject::tr("Suspect & Reject")
#define RECIPE_PARAM_WELD_FORCE_CONTROL      QObject::tr("WELD FORCE CONTROL")
