# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_TILCON_DEMO  {}
set _VSB_LAYER_CDFPATH_TILCON_DEMO [concat  $_VSB_LAYER_CDFPATH_TILCON_DEMO C:/WindRiverSR500New/vxworks-7/pkgs/ui/tilcon-7.0.0.1/demo-7.2.1.2/cdf]
