# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_ARM_ARMBASE  {}
set _VSB_LAYER_CDFPATH_ARM_ARMBASE [concat  $_VSB_LAYER_CDFPATH_ARM_ARMBASE C:/WindRiverSR500New/vxworks-7/pkgs/os/arch/arm-1.1.9.1/kernel/armbase/cdf]
