# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_WEBCLI_MIBWAY  {}
set _VSB_LAYER_CDFPATH_WEBCLI_MIBWAY [concat  $_VSB_LAYER_CDFPATH_WEBCLI_MIBWAY C:/WindRiverSR500New/vxworks-7/pkgs/app/webcli-1.0.0.3/mibway-1.0.0.4/cdf]
