# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_FONT_FREETYPE2  {}
set _VSB_LAYER_CDFPATH_FONT_FREETYPE2 [concat  $_VSB_LAYER_CDFPATH_FONT_FREETYPE2 C:/WindRiverSR500New/vxworks-7/pkgs/ui/font-1.0.0.1/freetype2-2.3.2.3/cdf]
