# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_USB_MOUSE  {}
set _VSB_LAYER_CDFPATH_USB_MOUSE [concat  $_VSB_LAYER_CDFPATH_USB_MOUSE C:/WindRiverSR500New/vxworks-7/pkgs/connectivity/usb-1.1.0.6/host/class/mouse-1.0.0.4/cdf]
