
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_VXBUS_SUBSYSTEM)


LIB_BASE_NAMES += vxbus

	
	

	
# copying directory h to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/timestampDev.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/timestampDev.h





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/timestampDev.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/timestampDev.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/timerDev.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/timerDev.h





C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/timerDev.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/timerDev.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory h/subsys to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys




# copying directory h/subsys/pinmux to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/pinmux




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/pinmux/vxbPinMuxLib.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/pinmux/vxbPinMuxLib.h





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/pinmux/vxbPinMuxLib.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/subsys/pinmux/vxbPinMuxLib.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/pinmux
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory h/subsys/timer to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/timer




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/timer/vxbTimerLib.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/timer/vxbTimerLib.h





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/timer/vxbTimerLib.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/subsys/timer/vxbTimerLib.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/timer
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory h/subsys/dma to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/dma




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/dma/vxbDmaLib.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/dma/vxbDmaLib.h





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/dma/vxbDmaLib.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/subsys/dma/vxbDmaLib.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/dma
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory h/subsys/flash to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/flash




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/flash/vxbFlashLib.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/flash/vxbFlashLib.h





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/flash/vxbFlashLib.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/subsys/flash/vxbFlashLib.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/flash
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory h/subsys/int to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxbIntLib.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxbIntLib.h





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxbIntLib.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/subsys/int/vxbIntLib.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxIpiLib.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxIpiLib.h





C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxIpiLib.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/subsys/int/vxIpiLib.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxbDyncIntLib.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxbDyncIntLib.h





C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxbDyncIntLib.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/subsys/int/vxbDyncIntLib.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxbIsrHandler.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxbIsrHandler.h





C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int/vxbIsrHandler.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/subsys/int/vxbIsrHandler.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory h/subsys/gpio to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/gpio




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/gpio/vxbGpioLib.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/gpio/vxbGpioLib.h





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/gpio/vxbGpioLib.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/subsys/gpio/vxbGpioLib.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/gpio
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory h/subsys/clk to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/clk




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/clk/vxbClkLib.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/clk/vxbClkLib.h





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/clk/vxbClkLib.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/h/subsys/clk/vxbClkLib.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/clk
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif






	
	
	
	
	
	
	
	
	
	
# copying directory user_h to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public




# copying directory user_h/subsys to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/subsys




# copying directory user_h/subsys/int to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/subsys/int




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/subsys/int/vxbIntLib.h

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/subsys/int/vxbIntLib.h





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/subsys/int/vxbIntLib.h : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/user_h/subsys/int/vxbIntLib.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/subsys/int
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif




	
	
	
	
	
	
	


	
PREBUILD_GENHEADERS : VXBUS_SUBSYSTEM_src/int_diab__PREBUILD_GENHEADERS



VXBUS_SUBSYSTEM_src/int_diab__PREBUILD_GENHEADERS : 
	@ echo building VXBUS_SUBSYSTEM directory src/int
	+ @ cd C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/src/int && C:/WindRiver/vxworks-7/host/binutils/x86-win32/bin/make CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=kernel _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=VXBUS_SUBSYSTEM VSB_DIR=C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=_PREBUILD_GENHEADERS_VXBUS_SUBSYSTEM_src_int_diab __WRS_TARGET=PREBUILD_GENHEADERS BSPNAME=ti_sitara_ctxa9_branson_1_0_0_0  BUILDSTAGE=PREBUILD_GENHEADERS
 
PREBUILD_GENHEADERS : VXBUS_SUBSYSTEM_src/dma_diab__PREBUILD_GENHEADERS



VXBUS_SUBSYSTEM_src/dma_diab__PREBUILD_GENHEADERS : 
	@ echo building VXBUS_SUBSYSTEM directory src/dma
	+ @ cd C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/src/dma && C:/WindRiver/vxworks-7/host/binutils/x86-win32/bin/make CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=kernel _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=VXBUS_SUBSYSTEM VSB_DIR=C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=_PREBUILD_GENHEADERS_VXBUS_SUBSYSTEM_src_dma_diab __WRS_TARGET=PREBUILD_GENHEADERS BSPNAME=ti_sitara_ctxa9_branson_1_0_0_0  BUILDSTAGE=PREBUILD_GENHEADERS
 
PREBUILD_GENHEADERS : VXBUS_SUBSYSTEM_src/pinmux_diab__PREBUILD_GENHEADERS



VXBUS_SUBSYSTEM_src/pinmux_diab__PREBUILD_GENHEADERS : 
	@ echo building VXBUS_SUBSYSTEM directory src/pinmux
	+ @ cd C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/src/pinmux && C:/WindRiver/vxworks-7/host/binutils/x86-win32/bin/make CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=kernel _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=VXBUS_SUBSYSTEM VSB_DIR=C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=_PREBUILD_GENHEADERS_VXBUS_SUBSYSTEM_src_pinmux_diab __WRS_TARGET=PREBUILD_GENHEADERS BSPNAME=ti_sitara_ctxa9_branson_1_0_0_0  BUILDSTAGE=PREBUILD_GENHEADERS

	
	
	
	
	
	
BUILD : VXBUS_SUBSYSTEM_src_diab__BUILD

.PHONY : VXBUS_SUBSYSTEM_src_diab__BUILD

__BUILD_FB_IDS += kernel_top_VXBUS_SUBSYSTEM_src_diab

VXBUS_SUBSYSTEM_src_diab__BUILD : 
	@ echo building VXBUS_SUBSYSTEM directory src
	+ @ cd C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/src && C:/WindRiver/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=kernel _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=VXBUS_SUBSYSTEM VSB_DIR=C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_VXBUS_SUBSYSTEM_src_diab BSPNAME=ti_sitara_ctxa9_branson_1_0_0_0 BUILDSTAGE=BUILD


	
BUILD_USR_STATIC : VXBUS_SUBSYSTEM_user_src_diab__BUILD_USR_STATIC

.PHONY : VXBUS_SUBSYSTEM_user_src_diab__BUILD_USR_STATIC

__BUILD_USR_STATIC_FB_IDS += user_static_top_VXBUS_SUBSYSTEM_user_src_diab

VXBUS_SUBSYSTEM_user_src_diab__BUILD_USR_STATIC : 
	@ echo building VXBUS_SUBSYSTEM directory user_src
	+ @ cd C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/user_src && C:/WindRiver/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=user LAYER_FORMAT=static _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=VXBUS_SUBSYSTEM VSB_DIR=C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=user_static_top_VXBUS_SUBSYSTEM_user_src_diab BSPNAME=ti_sitara_ctxa9_branson_1_0_0_0 BUILDSTAGE=BUILD_USR_STATIC

	
	
BUILD_USR_SHARED : VXBUS_SUBSYSTEM_user_src_diab__BUILD_USR_SHARED

.PHONY : VXBUS_SUBSYSTEM_user_src_diab__BUILD_USR_SHARED

__BUILD_USR_SHARED_FB_IDS += user_shared_top_VXBUS_SUBSYSTEM_user_src_diab

VXBUS_SUBSYSTEM_user_src_diab__BUILD_USR_SHARED : 
	@ echo building VXBUS_SUBSYSTEM directory user_src
	+ @ cd C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/user_src && C:/WindRiver/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=user LAYER_FORMAT=shared _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=VXBUS_SUBSYSTEM VSB_DIR=C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=user_shared_top_VXBUS_SUBSYSTEM_user_src_diab BSPNAME=ti_sitara_ctxa9_branson_1_0_0_0 BUILDSTAGE=BUILD_USR_SHARED


	
	
	

	

	


	
# copying directory cdf to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10pinmux.cdf

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10pinmux.cdf





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10pinmux.cdf : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/cdf/10pinmux.cdf | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10dma.cdf

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10dma.cdf





C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10dma.cdf : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/cdf/10dma.cdf | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10flash.cdf

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10flash.cdf





C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10flash.cdf : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/cdf/10flash.cdf | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10gpio.cdf

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10gpio.cdf





C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10gpio.cdf : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/cdf/10gpio.cdf | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10devclk.cdf

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10devclk.cdf





C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10devclk.cdf : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/cdf/10devclk.cdf | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10interrupt.cdf

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10interrupt.cdf





C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10interrupt.cdf : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/cdf/10interrupt.cdf | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10subsystem.cdf

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10subsystem.cdf





C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/10subsystem.cdf : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/cdf/10subsystem.cdf | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	
cdf_PRENOBUILD_VXBUS_SUBSYSTEM_FILES = cdf/10pinmux.cdf cdf/10dma.cdf cdf/10flash.cdf cdf/10gpio.cdf cdf/10devclk.cdf cdf/10interrupt.cdf cdf/10subsystem.cdf

cdf_PRENOBUILD_VXBUS_SUBSYSTEM_DIR = C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0

PRENOBUILD_FILES += $(addprefix $(cdf_PRENOBUILD_VXBUS_SUBSYSTEM_DIR)/,$(cdf_PRENOBUILD_VXBUS_SUBSYSTEM_FILES))

PRENOBUILD : PRENOBUILD_VXBUS_SUBSYSTEM

PRENOBUILD_VXBUS_SUBSYSTEM : cdf_PRENOBUILD_VXBUS_SUBSYSTEM

cdf_PRENOBUILD_VXBUS_SUBSYSTEM : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/cdf_PRENOBUILD_VXBUS_SUBSYSTEM.cdf

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/cdf_PRENOBUILD_VXBUS_SUBSYSTEM.cdf : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/cdf_PRENOBUILD_VXBUS_SUBSYSTEM.tmp
	$(CDFCOMP) -i $^ -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer VXBUS_SUBSYSTEM

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf/cdf_PRENOBUILD_VXBUS_SUBSYSTEM.tmp : | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf
	$(file >$@,$(call __vsb_tmpl_cdf_inter,$(addprefix $(cdf_PRENOBUILD_VXBUS_SUBSYSTEM_DIR)/,$(sort $(cdf_PRENOBUILD_VXBUS_SUBSYSTEM_FILES))),VXBUS_SUBSYSTEM))



	

	
# copying directory cfg to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/configlette




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/configlette/usrVxbTimerSys.c

__FILES_TO_COPY_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/configlette/usrVxbTimerSys.c





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/configlette/usrVxbTimerSys.c : C:/WindRiver/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.10.0/cfg/usrVxbTimerSys.c | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



	
__DIR_TARGETS += $(__DIR_TARGETS_VXBUS_SUBSYSTEM)

__DIR_TARGETS_VXBUS_SUBSYSTEM += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/configlette C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/clk C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/dma C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/flash C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/gpio C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/int C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/pinmux C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h/public/subsys/timer C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/share/h C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/subsys/int C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/vsblCdf

