
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_LANG_LIB_TOOL_TOOLSRC_COMMON_USER)




	
	

	


	
	
	
	
	
	
	
	
	
	
# copying directory h to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public




# copying directory h/tool to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/tool




# copying directory h/tool/common to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/tool/common




# copying directory h/tool/common/private to C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/tool/common/private




PRENOBUILD : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/tool/common/private/toolMacrosP.h

__FILES_TO_COPY_LANG_LIB_TOOL_TOOLSRC_COMMON_USER += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/tool/common/private/toolMacrosP.h





 

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/tool/common/private/toolMacrosP.h : C:/WindRiver/vxworks-7/pkgs/os/lang-lib/tool-1.0.0.3/common-1.0.3.4/usr/h/tool/common/private/toolMacrosP.h | C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/tool/common/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif





	
	
	
	
	
	
	


	
	
	
	
	
	
	

	
BUILD_USR_STATIC : LANG_LIB_TOOL_TOOLSRC_COMMON_USER_src_diab__BUILD_USR_STATIC

.PHONY : LANG_LIB_TOOL_TOOLSRC_COMMON_USER_src_diab__BUILD_USR_STATIC

__BUILD_USR_STATIC_FB_IDS += user_static_top_LANG_LIB_TOOL_TOOLSRC_COMMON_USER_src_diab

LANG_LIB_TOOL_TOOLSRC_COMMON_USER_src_diab__BUILD_USR_STATIC : 
	@ echo building LANG_LIB_TOOL_TOOLSRC_COMMON_USER directory src
	+ @ cd C:/WindRiver/vxworks-7/pkgs/os/lang-lib/tool-1.0.0.3/common-1.0.3.4/usr/src && C:/WindRiver/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=user LAYER_FORMAT=static _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=LANG_LIB_TOOL_TOOLSRC_COMMON_USER VSB_DIR=C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=user_static_top_LANG_LIB_TOOL_TOOLSRC_COMMON_USER_src_diab BSPNAME=ti_sitara_ctxa9_branson_1_0_0_0 BUILDSTAGE=BUILD_USR_STATIC

	
	
BUILD_USR_SHARED : LANG_LIB_TOOL_TOOLSRC_COMMON_USER_src_diab__BUILD_USR_SHARED

.PHONY : LANG_LIB_TOOL_TOOLSRC_COMMON_USER_src_diab__BUILD_USR_SHARED

__BUILD_USR_SHARED_FB_IDS += user_shared_top_LANG_LIB_TOOL_TOOLSRC_COMMON_USER_src_diab

LANG_LIB_TOOL_TOOLSRC_COMMON_USER_src_diab__BUILD_USR_SHARED : 
	@ echo building LANG_LIB_TOOL_TOOLSRC_COMMON_USER directory src
	+ @ cd C:/WindRiver/vxworks-7/pkgs/os/lang-lib/tool-1.0.0.3/common-1.0.3.4/usr/src && C:/WindRiver/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=ARMARCH7 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_1 SPACE=user LAYER_FORMAT=shared _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=LANG_LIB_TOOL_TOOLSRC_COMMON_USER VSB_DIR=C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB _WRS_CONFIG_FP=vector _WRS_CLI_CFLAGS="-I. " _FB_ID=user_shared_top_LANG_LIB_TOOL_TOOLSRC_COMMON_USER_src_diab BSPNAME=ti_sitara_ctxa9_branson_1_0_0_0 BUILDSTAGE=BUILD_USR_SHARED


	
	
	

	

	


	
	
	

	

	
__DIR_TARGETS += $(__DIR_TARGETS_LANG_LIB_TOOL_TOOLSRC_COMMON_USER)

__DIR_TARGETS_LANG_LIB_TOOL_TOOLSRC_COMMON_USER += C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/cdf C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/configlette C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/h C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/share/h C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/usr/h/public/tool/common/private C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/vsblCdf

