
ifndef __HEADER_ACCESS_ARM_ARMBASE_INCLUDED
__HEADER_ACCESS_ARM_ARMBASE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_ARM_ARMBASE = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/ARM_ARMBASE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), ARM_ARMBASE))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/ARM_ARMBASE
endif
endif

endif

endif

