
ifndef __HEADER_ACCESS_ARM_USER_INCLUDED
__HEADER_ACCESS_ARM_USER_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_ARM_USER = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/ARM_USER),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), ARM_USER))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/ARM_USER
endif
endif

endif

endif

