
ifndef __HEADER_ACCESS_SDMMC_STORAGE_INCLUDED
__HEADER_ACCESS_SDMMC_STORAGE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_SDMMC_STORAGE = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/SDMMC_STORAGE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), SDMMC_STORAGE))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/SDMMC_STORAGE
endif
endif

endif

endif

