
#
# This file is automatically generated by mk/krnl/defs.fastlibgen.mk .
#
# build configuration :
#	VSB : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB
#	CPU : ARMARCH7
#	TOOL : diab
#	FP : vector
# 	ENDIAN : little
#	LIB_DIR_TAG = 
#	LIBDIRBASE = krnl/ARMARCH7/common
#	LIBDIRBASE = krnl/$(CPU)$(CPU_OPTION_SUFFIX)/$(TOOL_COMMON_DIR)$(LIB_DIR_TAG)$(MINOR_OPTION_SUFFIX)






LIBOBJS = $(LIBOBJS_rtp)

# DEP_OBJS = (DEP_OBJS)

 
LIBOBJS_krnl_ARMARCH7_common_rtp_kernel_top_CORE_KERNEL_src_diab_rtp =  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objrtp/rtpFuncBind.o  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objrtp/usrRtpStartup.o 

arcmdfile_krnl_ARMARCH7_common_rtp : $(LIBOBJS_krnl_ARMARCH7_common_rtp_kernel_top_CORE_KERNEL_src_diab_rtp)

LIBOBJS_krnl_ARMARCH7_common_rtp_CORE_KERNEL += $(LIBOBJS_krnl_ARMARCH7_common_rtp_kernel_top_CORE_KERNEL_src_diab_rtp)

LIBOBJS_krnl_ARMARCH7_common_rtp += $(LIBOBJS_krnl_ARMARCH7_common_rtp_kernel_top_CORE_KERNEL_src_diab_rtp)

__OBJS_TO_CLEAN_CORE_KERNEL += $(LIBOBJS_krnl_ARMARCH7_common_rtp_kernel_top_CORE_KERNEL_src_diab_rtp) $(LIBOBJS_krnl_ARMARCH7_common_rtp_kernel_top_CORE_KERNEL_src_diab_rtp:.o=.d)

ifndef _DONEBASE_LIB_krnl_ARMARCH7_common_rtp

_DONEBASE_LIB_krnl_ARMARCH7_common_rtp = TRUE

# LIBBASES += rtp

__LIBS_TO_BUILD += krnl_ARMARCH7_common_rtp

__LIBS_TO_BUILD_CORE_KERNEL += krnl_ARMARCH7_common_rtp

__BUILT_LIBS += krnl_ARMARCH7_common_rtp

__LIB_krnl_ARMARCH7_common_rtp = C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp$(OPT).a


C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objrtp :
	$(MKDIR) $@


lib : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp$(OPT).a  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp.cdf

# need to pass the lib.a file twice to C:/WindRiver/compilers/diab-5.9.6.1/WIN32/bin/ddump -Ng to workaround ddump problem
C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp.nm : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp$(OPT).a
	$(if $(wildcard $<),cd C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common && $(NM) librtp$(OPT).a librtp$(OPT).a > $@, $(info skipping $@ : non existant $<))

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp.cdf : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp.nm 
	$(if $(wildcard $<),$(LIB2CDF) -i $< -a librtp.a -o $@, $(info skipping $@ : non existant $<))

arcmdfiles : arcmdfile_krnl_ARMARCH7_common_rtp

arcmdfile_krnl_ARMARCH7_common_rtp :
	$(file >$@,$(LIBOBJS_krnl_ARMARCH7_common_rtp))
	@echo created $@

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp$(OPT).a : arcmdfile_krnl_ARMARCH7_common_rtp
	C:/WindRiver/compilers/diab-5.9.6.1/WIN32/bin/dar crusv $@ @arcmdfile_krnl_ARMARCH7_common_rtp


clean _layer_clean_CORE_KERNEL : _clean_LIB_BASE_krnl_ARMARCH7_common_rtp

_clean_LIB_BASE_krnl_ARMARCH7_common_rtp :
	rm -f C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp$(OPT).a


endif

ifndef _DONEBASE_LIB_CORE_KERNEL_krnl_ARMARCH7_common_rtp

_DONEBASE_LIB_CORE_KERNEL_krnl_ARMARCH7_common_rtp = TRUE

lib : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/layerCORE_KERNEL_librtp.cdf

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/layerCORE_KERNEL_librtp.cdf :  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp$(OPT).a
	$(file >$@, $(call __tmpl_layercdf,CORE_KERNEL,librtp.a,$(LIBOBJS_krnl_ARMARCH7_common_rtp)))

endif


C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/librtp$(OPT).a : $(LIBOBJS_krnl_ARMARCH7_common_rtp)




 

################
# rules defined locally in Makefile
##



################

objs : $(LIBOBJS)
 
# this is the end of the file 
