
#
# This file is automatically generated by mk/krnl/defs.fastlibgen.mk .
#
# build configuration :
#	VSB : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB
#	CPU : ARMARCH7
#	TOOL : diab
#	FP : vector
# 	ENDIAN : little
#	LIB_DIR_TAG = 
#	LIBDIRBASE = krnl/ARMARCH7/common
#	LIBDIRBASE = krnl/$(CPU)$(CPU_OPTION_SUFFIX)/$(TOOL_COMMON_DIR)$(LIB_DIR_TAG)$(MINOR_OPTION_SUFFIX)






LIBOBJS = $(LIBOBJS_stacktrace)

# DEP_OBJS = (DEP_OBJS)

 
LIBOBJS_krnl_ARMARCH7_common_stacktrace_kernel_top_STACKTRACE_src_diab =  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objstacktrace/context_memtest.o  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objstacktrace/context.o  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objstacktrace/context_region.o  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objstacktrace/arm_os.o  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objstacktrace/arm_crawl.o  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objstacktrace/memory_map_vx.o  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objstacktrace/memory_map_module_vx.o  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objstacktrace/memory_map_shd_vx.o 

arcmdfile_krnl_ARMARCH7_common_stacktrace : $(LIBOBJS_krnl_ARMARCH7_common_stacktrace_kernel_top_STACKTRACE_src_diab)

LIBOBJS_krnl_ARMARCH7_common_stacktrace_STACKTRACE += $(LIBOBJS_krnl_ARMARCH7_common_stacktrace_kernel_top_STACKTRACE_src_diab)

LIBOBJS_krnl_ARMARCH7_common_stacktrace += $(LIBOBJS_krnl_ARMARCH7_common_stacktrace_kernel_top_STACKTRACE_src_diab)

__OBJS_TO_CLEAN_STACKTRACE += $(LIBOBJS_krnl_ARMARCH7_common_stacktrace_kernel_top_STACKTRACE_src_diab) $(LIBOBJS_krnl_ARMARCH7_common_stacktrace_kernel_top_STACKTRACE_src_diab:.o=.d)

ifndef _DONEBASE_LIB_krnl_ARMARCH7_common_stacktrace

_DONEBASE_LIB_krnl_ARMARCH7_common_stacktrace = TRUE

# LIBBASES += stacktrace

__LIBS_TO_BUILD += krnl_ARMARCH7_common_stacktrace

__LIBS_TO_BUILD_STACKTRACE += krnl_ARMARCH7_common_stacktrace

__BUILT_LIBS += krnl_ARMARCH7_common_stacktrace

__LIB_krnl_ARMARCH7_common_stacktrace = C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace$(OPT).a


C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/objstacktrace :
	$(MKDIR) $@


lib : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace$(OPT).a  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace.cdf

# need to pass the lib.a file twice to C:/WindRiver/compilers/diab-5.9.6.1/WIN32/bin/ddump -Ng to workaround ddump problem
C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace.nm : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace$(OPT).a
	$(if $(wildcard $<),cd C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common && $(NM) libstacktrace$(OPT).a libstacktrace$(OPT).a > $@, $(info skipping $@ : non existant $<))

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace.cdf : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace.nm 
	$(if $(wildcard $<),$(LIB2CDF) -i $< -a libstacktrace.a -o $@, $(info skipping $@ : non existant $<))

arcmdfiles : arcmdfile_krnl_ARMARCH7_common_stacktrace

arcmdfile_krnl_ARMARCH7_common_stacktrace :
	$(file >$@,$(LIBOBJS_krnl_ARMARCH7_common_stacktrace))
	@echo created $@

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace$(OPT).a : arcmdfile_krnl_ARMARCH7_common_stacktrace
	C:/WindRiver/compilers/diab-5.9.6.1/WIN32/bin/dar crusv $@ @arcmdfile_krnl_ARMARCH7_common_stacktrace


clean _layer_clean_STACKTRACE : _clean_LIB_BASE_krnl_ARMARCH7_common_stacktrace

_clean_LIB_BASE_krnl_ARMARCH7_common_stacktrace :
	rm -f C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace$(OPT).a


endif

ifndef _DONEBASE_LIB_STACKTRACE_krnl_ARMARCH7_common_stacktrace

_DONEBASE_LIB_STACKTRACE_krnl_ARMARCH7_common_stacktrace = TRUE

lib : C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/layerSTACKTRACE_libstacktrace.cdf

C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/layerSTACKTRACE_libstacktrace.cdf :  C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace$(OPT).a
	$(file >$@, $(call __tmpl_layercdf,STACKTRACE,libstacktrace.a,$(LIBOBJS_krnl_ARMARCH7_common_stacktrace)))

endif


C:/Users/builder5/Desktop/Paul/MyWorkspaces/NextGen/Integration/AM4377_VSB/krnl/ARMARCH7/common/libstacktrace$(OPT).a : $(LIBOBJS_krnl_ARMARCH7_common_stacktrace)




 

################
# rules defined locally in Makefile
##



################

objs : $(LIBOBJS)
 
# this is the end of the file 
