/*
 * Copyright (c) 2022 Wind River Systems, Inc.
 *
 * The right to copy, distribute, modify or otherwise make use
 * of this software may be licensed only pursuant to the terms
 * of an applicable Wind River license agreement.
 */

/*
 *  DO NOT MODIFY THIS FILE MANUALLY
 *
 *  This file is automatically generated from
 *  the method file (extended with *.m).
 *
 */

#ifndef _INCvxbParamMethodh
#define _INCvxbParamMethodh

VXB_DEVMETHOD_DECL(vxbParamChg)
typedef STATUS vxbParamChg_t (VXB_DEV_ID pDev, VXB_PARAMS * pParam);
STATUS VXB_PARAM_CHG (VXB_DEV_ID pDev, VXB_PARAMS * pParam);

#endif /* _INCvxbParamMethodh */

