# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_IPNET_PPP  {}
set _VSB_LAYER_CDFPATH_IPNET_PPP [concat  $_VSB_LAYER_CDFPATH_IPNET_PPP C:/WindRiverSR500New/vxworks-7/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.3/cdf]
