# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_JOBQUEUE  {}
set _VSB_LAYER_CDFPATH_JOBQUEUE [concat  $_VSB_LAYER_CDFPATH_JOBQUEUE C:/WindRiverSR500New/vxworks-7/pkgs/os/service/jobqueue-1.0.2.2/cdf]
