# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_FDT  {}
set _VSB_LAYER_CDFPATH_FDT [concat  $_VSB_LAYER_CDFPATH_FDT C:/WindRiverSR500New/vxworks-7/pkgs/os/firmware/fdt-1.0.9.3/cdf]
