# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_VXBUS_DRV  {}
set _VSB_LAYER_CDFPATH_VXBUS_DRV [concat  $_VSB_LAYER_CDFPATH_VXBUS_DRV C:/WindRiverSR500New/vxworks-7/pkgs/os/drv/vxbus-1.0.5.0/drv-1.2.5.0/cdf]
